#!/usr/bin/env python3
"""course19-agent-incident-response 의 15주 × (ai/nonai) lab YAML 일괄 생성.

이전 과목들과 동일 포맷(lab_id, version, course, week, steps[order, category, points,
instruction, hint, answer, answer_detail, verify, target_vm, script, risk_level,
bastion_prompt])으로 출력.
"""
from __future__ import annotations
import os, yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LABS = os.path.join(ROOT, "contents", "labs")

BASE_COURSE_AI = "agent-ir-ai"
BASE_COURSE_NONAI = "agent-ir-nonai"

# 주차별 설계
WEEKS = {
    1: {
        "title": "AI Vulnerability Storm 관전과 기준선 설정",
        "description": (
            "공격 에이전트의 자율 동작을 관전하며, 방어 측이 관찰할 수 있는 신호의 *기준선*을 수집한다."
            " 본 주차는 관전·수집 중심이며 이후 주차 실습의 원천 자료를 남긴다."
        ),
        "objectives": [
            "과목의 위치·목표·평가를 정확히 이해한다",
            "Claude Code 관전 세션에서 방어 측이 볼 수 있는 신호를 식별한다",
            "기준선(Wazuh rule hits, Suricata alerts, access.log 분포)을 수집한다",
        ],
        "steps": [
            ("관전 준비: siem의 Wazuh 대시보드가 정상 접속되는지 확인하라",
             "curl -sk https://10.20.30.100:443/ -o /tmp/wazuh.html && head -5 /tmp/wazuh.html",
             "siem", "Wazuh 대시보드 접속 가능성을 기초로 확인한다.",
             "html", "output_contains", "html"),
            ("secu에서 10분간 트래픽 캡처 시작 후 중지, pcap을 /tmp/w01-baseline.pcap 로 저장",
             "sudo timeout 60 tcpdump -i any -nn -w /tmp/w01-baseline.pcap 'host 10.20.30.80' 2>/dev/null; ls -la /tmp/w01-baseline.pcap",
             "secu", "기준선 트래픽 캡처. 강사 시연 직전 수행한다.",
             "w01-baseline.pcap", "output_contains", "w01-baseline.pcap"),
            ("web의 access.log 최근 200줄을 읽어 403/404/200 비율을 간단히 요약하라",
             "sudo tail -200 /var/log/apache2/access.log | awk '{c[$9]++} END{for(k in c) print k, c[k]}'",
             "web", "403/404/200 비율의 기준선 기록.",
             "200", "output_contains", ""),
            ("관전 노트용 디렉토리를 bastion에 만들고 기본 양식을 저장",
             "mkdir -p ~/w01-notes && echo 'T+MM:SS | step | tool | result' > ~/w01-notes/template.md && cat ~/w01-notes/template.md",
             "bastion", "학생 관전 노트의 템플릿.",
             "template", "output_contains", "template"),
            ("Bastion에 첫 Experience 엔트리를 메모로 남겨둔다 (관전 시작)",
             "mkdir -p ~/ccc/data/bastion/experience && echo '{\"id\":\"w01-baseline\",\"note\":\"observation_baseline\"}' > ~/ccc/data/bastion/experience/w01.json && cat ~/ccc/data/bastion/experience/w01.json",
             "bastion", "Bastion Experience 메모(초기 기록).",
             "baseline", "output_contains", "baseline"),
        ],
    },
    2: {
        "title": "공격자 해부 — tool-use 루프와 지문 점수",
        "description": "에이전트 호스트가 아닌 방어자 측 관측만으로 공격자 지문(fingerprint)을 계산하는 파이프라인을 구축한다.",
        "objectives": [
            "공격 세션의 요청 간격 CoV, 경로 다양성, 실패 재시도를 계산한다",
            "에이전트 점수 함수의 결과를 해석한다",
            "Bastion에서 점수 임계 기반 초기 대응의 기준을 정한다",
        ],
        "steps": [
            ("w01 pcap에서 요청 간격(IAT) 평균·표준편차를 계산한다",
             "tshark -r /tmp/w01-baseline.pcap -Y 'http.request' -T fields -e frame.time_epoch | awk 'NR>1{print $1-p} {p=$1}' | awk '{sum+=$1; sumsq+=$1*$1; n++} END{if(n){m=sum/n; print \"mean=\" m \" stdev=\" sqrt(sumsq/n - m*m)}}'",
             "secu", "IAT 평균·표준편차. CoV=stdev/mean 기준 0.3 미만이면 에이전트 지문.",
             "mean=", "output_contains", "mean"),
            ("경로 다양성: 고유 URI 수",
             "tshark -r /tmp/w01-baseline.pcap -Y 'http.request' -T fields -e http.request.uri | sort -u | wc -l",
             "secu", "고유 URI 수가 클수록 정찰성 증가.",
             "0", "output_contains", ""),
            ("4xx 응답 후 3초 내 재시도 비율 샘플링",
             "sudo awk '{print $1, $4, $9}' /var/log/apache2/access.log | tail -500 | awk '{print $3}' | awk '/^4/{c4++} /^2/{c2++} END{print \"4xx=\" c4 \" 2xx=\" c2}'",
             "web", "재시도 분포의 기초 통계.",
             "4xx=", "output_contains", "4xx"),
            ("에이전트 점수 스크립트 골격을 bastion에 저장",
             "mkdir -p ~/ccc/scripts && cat > ~/ccc/scripts/agent_score.py <<'PY'\ndef score(iat_cov, path_div, retry_ratio): s=0.0\\nif iat_cov<0.3: s+=0.3\\nif path_div>=10: s+=0.3\\nif retry_ratio>0.2: s+=0.2\\nreturn s\\nprint(score(0.2, 15, 0.3))\\nPY\npython3 ~/ccc/scripts/agent_score.py",
             "bastion", "점수 함수의 골격과 테스트 실행.",
             "0.", "output_contains", "0."),
            ("Bastion 점수 결과를 Experience로 기록",
             "echo '{\"id\":\"w02-score\",\"metrics\":{\"iat_cov\":0.18,\"path_div\":14,\"retry_ratio\":0.32},\"score\":0.8}' >> ~/ccc/data/bastion/experience/w02.json && tail -1 ~/ccc/data/bastion/experience/w02.json",
             "bastion", "점수 산출 결과를 Experience 저장.",
             "score", "output_contains", "score"),
        ],
    },
    3: {
        "title": "초지능 정찰 — 에이전트 정찰을 학생이 직접 의뢰",
        "description": "학생이 Claude Code(또는 Bastion의 recon 스킬)에게 JuiceShop 정찰을 의뢰하고, 결과를 방어 관점에서 재구성한다.",
        "objectives": [
            "에이전트 정찰의 단계별 속도·병렬성을 관찰한다",
            "ATT&CK Reconnaissance(TA0043) 기법 매핑",
            "정찰 신호 5원자(ReqBurst/FailSeq/FingerQuery/ToolMix/SessionSilence) 수집",
        ],
        "steps": [
            ("web의 `/robots.txt`, `/sitemap.xml`, `/api/`의 존재 여부를 curl로 조사",
             "for p in /robots.txt /sitemap.xml /api/; do curl -s -o /dev/null -w \"%{http_code} $p\\n\" http://10.20.30.80$p; done",
             "web", "정찰성 요청에 대한 응답 코드 분포.",
             "200", "output_contains", ""),
            ("JuiceShop의 Score Board 경로 접근이 공격자 시선에 어떻게 보이는지 확인",
             "curl -s -o /dev/null -w \"%{http_code}\\n\" http://10.20.30.80:3000/#/score-board",
             "web", "Score Board 접근 응답.",
             "200", "output_contains", ""),
            ("에이전트 정찰 시뮬레이션: 다수 경로 연속 요청 후 access.log에서 ReqBurst 신호 확인",
             "for i in $(seq 1 20); do curl -s -o /dev/null http://10.20.30.80:3000/rest/user/login -X POST -d '{\"email\":\"a'$i'@x.y\"}' -H 'Content-Type: application/json'; done; sudo tail -30 /var/log/apache2/access.log | awk '{print $9}' | sort | uniq -c",
             "web", "에이전트 유사 정찰 트래픽의 로그 지문 확인.",
             "20", "output_contains", ""),
            ("Suricata가 이 정찰을 잡는지 확인",
             "sudo tail -50 /var/log/suricata/fast.log | grep -Ei 'scan|enum' || echo 'NO_RECON_ALERT'",
             "secu", "정찰 시그니처가 기본셋에서 거의 안 뜨는 현상 확인.",
             "NO_RECON_ALERT", "output_contains", ""),
            ("Bastion에 정찰 Experience 등록",
             "echo '{\"id\":\"w03-recon\",\"ttp\":\"TA0043\",\"signals\":[\"ReqBurst\",\"SessionSilence\"]}' >> ~/ccc/data/bastion/experience/w03.json && tail -1 ~/ccc/data/bastion/experience/w03.json",
             "bastion", "정찰 경험 저장.",
             "TA0043", "output_contains", "TA0043"),
        ],
    },
    4: {
        "title": "자동 익스플로잇 — Transient Tool 추적",
        "description": "에이전트가 세션 안에서 작성·수정·폐기한 Transient Tool의 흔적을 방어자 관점으로 추적한다.",
        "objectives": [
            "공격 세션 아티팩트 번들을 구조화한다",
            "세션 내 도구 진화(버전 증가)를 관찰한다",
            "시그니처 공백(signature gap)에 대응하는 행위 기반 탐지 후보를 제안한다",
        ],
        "steps": [
            ("web의 auditd가 /tmp 쓰기를 감시하도록 설정",
             "sudo auditctl -w /tmp -p wa -k tmpwrites 2>&1 | head -3 || true",
             "web", "임시 도구 쓰기 감시 설정.",
             "", "output_contains", ""),
            ("간단한 공격 스크립트 위장 파일을 3버전 생성(실제 실행 없음)",
             "for v in 1 2 3; do echo \"# exploit v$v - $(date +%s)\" > /tmp/exp_v$v.py; done; ls -la /tmp/exp_v*.py",
             "web", "Transient Tool의 버전 증가를 모사.",
             "exp_v", "output_contains", "exp_v"),
            ("auditd에서 tmpwrites 최근 이벤트 조회",
             "sudo ausearch -k tmpwrites --start recent 2>/dev/null | tail -20 | head -20 || echo 'AUDIT_NO_EVENTS'",
             "web", "파일 쓰기 이벤트 관찰 — Transient Tool 표식.",
             "", "output_contains", ""),
            ("공격 세션 아티팩트 번들 디렉토리 구조 생성",
             "mkdir -p ~/ccc/artifacts/w04/{pcap,server-logs,tools,session} && ls ~/ccc/artifacts/w04",
             "bastion", "아티팩트 표준 폴더 구조.",
             "tools", "output_contains", "tools"),
            ("Transient Tool 탐지 후보를 Experience로 등록",
             "echo '{\"id\":\"w04-transient\",\"hint\":\"same_file_modified_multiple_times_in_short_window\"}' >> ~/ccc/data/bastion/experience/w04.json && tail -1 ~/ccc/data/bastion/experience/w04.json",
             "bastion", "행위 기반 탐지 후보 저장.",
             "transient", "output_contains", "transient"),
        ],
    },
    5: {
        "title": "측면이동·지속성 — 내부 행위 기록",
        "description": "측면이동 시도를 관전하고, Bastion이 가진 측면이동 탐지 신호의 초안을 만든다.",
        "objectives": [
            "측면이동 단계의 관측 가능한 신호를 식별한다",
            "지속성 메커니즘(cron/ssh-key/systemd)의 생성 이벤트를 감지한다",
            "Bastion 스킬 초안(detect_internal_scan 등)을 작성한다",
        ],
        "steps": [
            ("web에서 내부 arp 테이블을 조회(정찰 모사)",
             "ip neigh show | head -10",
             "web", "내부 ARP 테이블 관찰 (측면이동의 초기 신호).",
             "lladdr", "output_contains", ""),
            ("web의 ssh 디렉토리 권한 확인 (자격증명 접근 경로)",
             "ls -la ~/.ssh 2>/dev/null | head -10 || echo 'no_ssh_dir'",
             "web", "자격증명 접근 경로 감사.",
             "", "output_contains", ""),
            ("web에서 secu로의 접속 시도 (차단 예상) — 탐지 입증용",
             "timeout 3 ssh -o BatchMode=yes -o StrictHostKeyChecking=no ccc@10.20.30.1 'echo ok' 2>&1 | head -5 || echo 'BLOCKED_OR_TIMEOUT'",
             "web", "차단된 이동 시도의 로그.",
             "", "output_contains", ""),
            ("secu의 auth.log에서 ssh 접속 시도 흔적 확인",
             "sudo tail -40 /var/log/auth.log | grep -Ei 'sshd|Failed|Accepted' | tail -10",
             "secu", "내부 측면이동 시그널.",
             "sshd", "output_contains", ""),
            ("Bastion 스킬 초안 파일 생성",
             "mkdir -p ~/ccc/skills && cat > ~/ccc/skills/detect_internal_scan.md <<'MD'\n# skill: detect_internal_scan\n# input: secu connection logs (10m window)\n# logic: same src -> >=3 distinct dst OR >=20 new ports\n# action: tar_pit add 10m\nMD\ncat ~/ccc/skills/detect_internal_scan.md",
             "bastion", "측면이동 탐지 스킬 명세 초안.",
             "detect_internal_scan", "output_contains", "detect_internal_scan"),
        ],
    },
    6: {
        "title": "회피·다형성 — 변형 진화 탐지",
        "description": "에이전트가 WAF에 막힌 뒤 페이로드를 변형하는 과정을 관찰하고, 변형 진화 자체를 탐지하는 룰을 설계한다.",
        "objectives": [
            "동일 페이로드의 인코딩 변형 3종을 만들어 WAF 반응을 비교한다",
            "ModSecurity 감사 로그에서 룰 매칭 분포를 읽는다",
            "변형 진화 기반 세션 탐지 로직 초안을 만든다",
        ],
        "steps": [
            ("JuiceShop 로그인 폼에 기본 SQLi 페이로드 시도",
             "curl -s -o /dev/null -w '%{http_code}\\n' -X POST http://10.20.30.80:8082/rest/user/login -d '{\"email\":\"admin\\'\\' OR 1=1--\",\"password\":\"x\"}' -H 'Content-Type: application/json'",
             "web", "1차 페이로드 반응.",
             "", "output_contains", ""),
            ("동일 페이로드의 URL 인코딩 변형",
             "curl -s -o /dev/null -w '%{http_code}\\n' 'http://10.20.30.80:8082/rest/user/login?email=admin%27%20OR%201%3D1--&password=x'",
             "web", "URL 인코딩 변형 반응.",
             "", "output_contains", ""),
            ("변형 페이로드: 주석 분할 /**/",
             "curl -s -o /dev/null -w '%{http_code}\\n' 'http://10.20.30.80:8082/rest/user/login?email=admin%27%20OR/**/1=1--&password=x'",
             "web", "분할 기법 변형 반응.",
             "", "output_contains", ""),
            ("ModSecurity 감사 로그에서 매칭 룰 ID 확인",
             "sudo tail -30 /var/log/bunkerweb/modsec_audit.log 2>/dev/null | grep -oE 'id=\"[0-9]+\"' | sort | uniq -c | head -10 || echo 'NO_MODSEC_LOG'",
             "web", "ModSec 룰 매칭 분포.",
             "", "output_contains", ""),
            ("Bastion에 변형 진화 탐지 초안 등록",
             "echo '{\"id\":\"w06-evolve\",\"rule\":\"seq_similar_payloads_diff_0.05_0.4_5_times\"}' >> ~/ccc/data/bastion/experience/w06.json && tail -1 ~/ccc/data/bastion/experience/w06.json",
             "bastion", "변형 진화 탐지 로직 초안 저장.",
             "evolve", "output_contains", "evolve"),
        ],
    },
    7: {
        "title": "멀티에이전트 병렬 — 세션 클러스터링",
        "description": "3개 공격 세션을 병렬로 가동하고, 방어 측이 이를 하나의 클러스터로 묶는 로직을 설계한다.",
        "objectives": [
            "3개 병렬 공격 트래픽을 생성한다",
            "JA3/UA/IAT 유사성으로 세션 클러스터 후보를 추출한다",
            "경보 폭주에서 P0~P3 트리아지를 시연한다",
        ],
        "steps": [
            ("병렬 트래픽 1: 정찰",
             "for i in $(seq 1 15); do curl -s -o /dev/null http://10.20.30.80/; done; echo 'recon_done'",
             "web", "세션 A: 단순 GET 반복.",
             "recon_done", "output_contains", "recon_done"),
            ("병렬 트래픽 2: POST 변형",
             "for i in $(seq 1 10); do curl -s -o /dev/null -X POST http://10.20.30.80:3000/rest/user/login -d '{\"email\":\"a'$i'\",\"password\":\"x\"}' -H 'Content-Type: application/json'; done; echo 'web_attack_done'",
             "web", "세션 B: 로그인 브루트.",
             "web_attack_done", "output_contains", "web_attack_done"),
            ("병렬 트래픽 3: API 탐색",
             "for p in /api /rest /admin; do curl -s -o /dev/null -w '%{http_code}\\n' http://10.20.30.80$p; done",
             "web", "세션 C: 경로 탐색.",
             "", "output_contains", ""),
            ("access.log에서 같은 시간대 다수 세션이 관찰되는지 확인",
             "sudo tail -60 /var/log/apache2/access.log | awk '{print $1}' | sort | uniq -c | sort -rn | head",
             "web", "IP별 요청 분포.",
             "", "output_contains", ""),
            ("Bastion에 세션 클러스터 규칙 초안 등록",
             "echo '{\"id\":\"w07-cluster\",\"rule\":\"cluster_by_ja3_ua_iat_sim>=0.7\"}' >> ~/ccc/data/bastion/experience/w07.json && tail -1 ~/ccc/data/bastion/experience/w07.json",
             "bastion", "세션 클러스터링 규칙 저장.",
             "cluster", "output_contains", "cluster"),
        ],
    },
    8: {
        "title": "중간평가 — Blue Team Agent IR CTF",
        "description": "제공된 공격 세션 아티팩트에서 IOC 추출·차단 권고·Bastion 스킬 1건을 설계한다.",
        "objectives": [
            "공격 단계 타임라인을 정확히 복원한다",
            "에이전트 점수 + ATT&CK 5매핑 + 방어 3층 진단",
            "Bastion 스킬 1건의 명세 작성",
        ],
        "steps": [
            ("평가용 번들 경로 확인",
             "ls /opt/ctf/w08/$(whoami) 2>/dev/null || echo 'BUNDLE_NOT_YET'",
             "bastion", "평가 번들 준비 여부 확인.",
             "", "output_contains", ""),
            ("번들의 access.log 요약(404/403 비율)",
             "f=/opt/ctf/w08/$(whoami)/server-logs/access.log; [ -f $f ] && awk '{c[$9]++} END{for(k in c) print k, c[k]}' $f | head || echo 'FILE_NOT_READY'",
             "bastion", "번들 기초 통계.",
             "", "output_contains", ""),
            ("pcap 파일 IAT 평균",
             "f=/opt/ctf/w08/$(whoami)/pcap/attack.pcap; [ -f $f ] && tshark -r $f -Y 'http.request' -T fields -e frame.time_epoch | awk 'NR>1{print $1-p} {p=$1}' | awk '{sum+=$1;n++} END{if(n) print sum/n}' || echo 'NO_PCAP'",
             "bastion", "IAT 평균(에이전트 지문 초안).",
             "", "output_contains", ""),
            ("답안 보고서 템플릿 생성",
             "mkdir -p ~/ctf-w08 && echo '# W08 Report\\n## Timeline\\n## Agent Score\\n## ATT&CK Mapping\\n## Defense Layer Verdict\\n## 3 Block Actions\\n## Skill Spec' > ~/ctf-w08/answers.md && cat ~/ctf-w08/answers.md",
             "bastion", "답안 틀 생성.",
             "Timeline", "output_contains", "Timeline"),
            ("제출용 skill YAML 스켈레톤",
             "cat > ~/ctf-w08/skill.yaml <<YAML\nskill_id: detect_agent_ctf\ntriggers_on: wazuh_alert OR access_log_burst\ninputs: []\nlogic: []\nthresholds: {}\noutputs: {alert_level: 12, action: []}\nfailure_mode: false_positive_mitigation\nYAML\ncat ~/ctf-w08/skill.yaml",
             "bastion", "제출용 skill 명세 스켈레톤.",
             "skill_id", "output_contains", "skill_id"),
        ],
    },
    9: {
        "title": "실시간 탐지 — SIGMA → Wazuh 파이프라인",
        "description": "자체 SIGMA 룰을 작성하여 Wazuh local_rules.xml에 병합하고, 회귀 데이터셋에서 지표를 측정한다.",
        "objectives": [
            "SIGMA 룰 초안 작성",
            "Wazuh로 변환·병합·문법 검증",
            "정밀도·재현율·탐지 지연 측정",
        ],
        "steps": [
            ("siem VM에 접속하고 local_rules.xml 백업",
             "sudo cp /var/ossec/etc/rules/local_rules.xml /tmp/local_rules.xml.bak && ls -la /tmp/local_rules.xml.bak",
             "siem", "수정 전 백업 확보.",
             "local_rules.xml.bak", "output_contains", "local_rules.xml.bak"),
            ("샘플 SIGMA 초안을 저장",
             "mkdir -p ~/sigma && cat > ~/sigma/agent_burst.yml <<'YML'\ntitle: Agent-like request burst\nlogsource: { product: apache, service: access }\ndetection:\n  selection:\n    cs-uri-stem|contains: ['/rest/']\n  timeframe: 120s\n  condition: selection | count() by c-ip > 60\nfalsepositives: [Internal bots]\nlevel: medium\nYML\ncat ~/sigma/agent_burst.yml",
             "siem", "SIGMA 초안.",
             "Agent-like", "output_contains", "Agent-like"),
            ("Wazuh rule 병합(예시 텍스트 추가)",
             "echo '<!-- placeholder by w09 -->' | sudo tee -a /var/ossec/etc/rules/local_rules.xml && tail -3 /var/ossec/etc/rules/local_rules.xml",
             "siem", "룰 병합 위치 확인.",
             "placeholder", "output_contains", "placeholder"),
            ("Wazuh 문법 검증",
             "sudo /var/ossec/bin/wazuh-analysisd -t 2>&1 | tail -10",
             "siem", "문법 오류 여부 확인.",
             "", "output_contains", ""),
            ("logtest로 샘플 입력 확인",
             "echo 'test line' | sudo /var/ossec/bin/wazuh-logtest 2>&1 | head -20",
             "siem", "Phase 1~3 매칭 과정 확인.",
             "Phase", "output_contains", "Phase"),
        ],
    },
    10: {
        "title": "기만·지연 — 허니토큰 + tar-pit",
        "description": "web에 가짜 관리자 경로와 허니토큰을 배치하고 의심 세션에 지연 정책을 적용한다.",
        "objectives": [
            "가짜 관리자 페이지와 허니토큰 배치",
            "Wazuh 고신뢰 경보 룰 작성",
            "의심 세션 지연 프로파일 정의",
        ],
        "steps": [
            ("가짜 관리자 페이지 배치",
             "sudo bash -c 'cat > /var/www/html/fake_admin.html <<HTML\n<!DOCTYPE html>\n<html><body><h1>Internal Admin</h1>\n<!-- API_KEY=HONEY_87af3b1c_DO_NOT_REMOVE --></body></html>\nHTML' && ls -la /var/www/html/fake_admin.html",
             "web", "허니페이지 파일 생성.",
             "fake_admin.html", "output_contains", "fake_admin.html"),
            ("Apache alias 설정 (admin-portal → fake_admin.html)",
             "echo 'Alias /admin-portal /var/www/html/fake_admin.html' | sudo tee /etc/apache2/conf-available/honey.conf && sudo a2enconf honey 2>/dev/null; sudo systemctl reload apache2 2>/dev/null; curl -s http://10.20.30.80/admin-portal | head -3",
             "web", "허니 경로 서비스.",
             "Internal", "output_contains", "Internal"),
            ("Wazuh 고신뢰 경보 룰 초안 저장",
             "echo '<!-- rule 100300: level 15 when /admin-portal in access log -->' | sudo tee -a /var/ossec/etc/rules/local_rules.xml && tail -2 /var/ossec/etc/rules/local_rules.xml",
             "siem", "고신뢰 경보 룰 표식.",
             "100300", "output_contains", "100300"),
            ("허니 경로 접근을 만들어 access.log에 남김",
             "curl -s http://10.20.30.80/admin-portal > /dev/null && sudo grep 'admin-portal' /var/log/apache2/access.log | tail -2",
             "web", "허니 페이지 접근 기록.",
             "admin-portal", "output_contains", "admin-portal"),
            ("지연 프로파일 정의 파일 생성",
             "mkdir -p ~/ccc/skills && cat > ~/ccc/skills/delay_profile.md <<'MD'\n# suspicion_score -> delay(ms)\n# <0.4 : 0\n# 0.4-0.6 : 200\n# 0.6-0.8 : 1000-3000\n# >0.8 : 10000-30000 (tar-pit)\nMD\ncat ~/ccc/skills/delay_profile.md",
             "bastion", "지연 프로파일 정의.",
             "tar-pit", "output_contains", "tar-pit"),
        ],
    },
    11: {
        "title": "Purple Round 1 — Bastion 스킬 추가",
        "description": "공방 결과를 바탕으로 Bastion에 새 스킬을 추가하고 Playbook을 구성한다.",
        "objectives": [
            "공방 아티팩트 기반 포렌식 복기",
            "코치 프롬프트로 개선안 추출",
            "Bastion 스킬·플레이북 등록",
        ],
        "steps": [
            ("새 스킬 소스 파일 생성",
             "mkdir -p ~/ccc/packages/bastion/skills && cat > ~/ccc/packages/bastion/skills/detect_agent_fp.py <<'PY'\ndef detect(session):\n    return session.get('iat_cov',1.0) < 0.3 and session.get('path_div',0) >= 10\nPY\ncat ~/ccc/packages/bastion/skills/detect_agent_fp.py",
             "bastion", "지문 탐지 스킬 소스.",
             "detect_agent_fp", "output_contains", "detect_agent_fp"),
            ("플레이북 YAML 생성",
             "mkdir -p ~/ccc/playbooks/agent_ir && cat > ~/ccc/playbooks/agent_ir/agent-fp.yaml <<YAML\nplaybook_id: pb-agent-fp\ntriggers: { wazuh_rule_id: 100200 }\nsteps:\n  - skill: detect_agent_fp\n  - skill: tar_pit_inject\n    args: { duration_s: 10 }\nrollback:\n  - unblock_nft\nYAML\ncat ~/ccc/playbooks/agent_ir/agent-fp.yaml",
             "bastion", "플레이북 YAML.",
             "pb-agent-fp", "output_contains", "pb-agent-fp"),
            ("Experience 엔트리 추가",
             "echo '{\"id\":\"w11-round1\",\"skill\":\"detect_agent_fp\",\"outcome\":\"success\"}' >> ~/ccc/data/bastion/experience/w11.json && tail -1 ~/ccc/data/bastion/experience/w11.json",
             "bastion", "Round 1 Experience 저장.",
             "round1", "output_contains", "round1"),
            ("재테스트용 트래픽 생성",
             "for i in $(seq 1 20); do curl -s -o /dev/null http://10.20.30.80/rest/user/login -X POST -d '{\"email\":\"a'$i'\"}' -H 'Content-Type: application/json'; done; echo 're_test_done'",
             "web", "재테스트 트래픽.",
             "re_test_done", "output_contains", "re_test_done"),
            ("Bastion diff 문서 생성",
             "echo '# w11 skill_playbook_diff\\n+ detect_agent_fp (skill)\\n+ pb-agent-fp (playbook)' > ~/ccc/data/bastion/skill_playbook_diff.md && cat ~/ccc/data/bastion/skill_playbook_diff.md",
             "bastion", "자산 변화 기록.",
             "detect_agent_fp", "output_contains", "detect_agent_fp"),
        ],
    },
    12: {
        "title": "Purple Round 2 — Experience 자동 승격",
        "description": "반복 Experience를 클러스터링하고 Playbook 후보로 승격하는 파이프라인을 만든다.",
        "objectives": [
            "Experience 클러스터링 스크립트 작성",
            "승격 점수 계산 및 후보 선정",
            "Shadow mode 적용 정의",
        ],
        "steps": [
            ("Experience 파일 합치기",
             "ls ~/ccc/data/bastion/experience/ 2>/dev/null && cat ~/ccc/data/bastion/experience/*.json 2>/dev/null | tail -20",
             "bastion", "경험 로그 현황.",
             "", "output_contains", ""),
            ("클러스터링 스크립트 작성",
             "cat > ~/ccc/scripts/bastion_promote.py <<'PY'\nimport json, glob, collections\nbuckets = collections.defaultdict(list)\nfor f in glob.glob('/root/ccc/data/bastion/experience/*.json'):\n    try:\n        for line in open(f):\n            e=json.loads(line)\n            buckets[e.get('skill') or e.get('id','-')].append(e)\n    except: pass\nfor k,v in buckets.items():\n    if len(v) >= 1: print(k, len(v))\nPY\npython3 ~/ccc/scripts/bastion_promote.py",
             "bastion", "클러스터링 결과.",
             "", "output_contains", ""),
            ("승격 후보 YAML 드래프트",
             "cat > ~/ccc/playbooks/agent_ir/_candidate_promote.yaml <<YAML\nplaybook_id: pb-auto-candidate\nsource_experiences: 1\navg_success: 1.0\nstatus: shadow\nYAML\ncat ~/ccc/playbooks/agent_ir/_candidate_promote.yaml",
             "bastion", "승격 후보 yaml.",
             "pb-auto-candidate", "output_contains", "pb-auto-candidate"),
            ("Canary 트래픽 계획 노트",
             "cat > ~/ccc/skills/canary.md <<'MD'\n# Canary patterns (every 10m)\n- GET / with real browser UA\n- Admin login from trusted IP\n- /api/health check\nMD\ncat ~/ccc/skills/canary.md",
             "bastion", "Canary 트래픽 계획.",
             "Canary", "output_contains", "Canary"),
            ("Round 2 측정 결과 저장",
             "echo '# Round 2 metrics\\n- detection_latency_median: 8s\\n- false_positive: 0\\n- auto_response: 3 steps' > ~/ccc/data/bastion/round2-metrics.md && cat ~/ccc/data/bastion/round2-metrics.md",
             "bastion", "Round 2 지표 저장.",
             "Round", "output_contains", "Round"),
        ],
    },
    13: {
        "title": "사고 보고서 작성",
        "description": "에이전트 IR 특화 섹션을 포함한 보고서 초안을 작성한다.",
        "objectives": [
            "보고서 골격 생성",
            "의사결정 로그 마스킹",
            "Bastion skill/playbook diff 첨부",
        ],
        "steps": [
            ("보고서 디렉토리와 골격",
             "mkdir -p ~/ccc/reports/w13 && cat > ~/ccc/reports/w13/report.md <<'MD'\n# Agent IR Incident Report (Draft)\n## 1. Summary\n## 2. Timeline\n## 3. Attacker Profile\n### 3.1 Model\n### 3.2 Prompt Chain\n### 3.3 Transient Tools\n## 4. Detection & Analysis\n## 5. Response (Bastion Decisions)\n## 6. Recovery\n## 7. Lessons (Bastion Asset Diff)\n## 8. Legal\n## Appendix\nMD\nwc -l ~/ccc/reports/w13/report.md",
             "bastion", "보고서 골격.",
             "8", "output_contains", ""),
            ("의사결정 로그 덤프·마스킹 샘플",
             "echo '{\"decision\":\"block_ip\",\"src\":\"10.xxx.xxx.50\",\"reason\":\"fp_score>0.8\"}' > ~/ccc/reports/w13/decision-sample.json && cat ~/ccc/reports/w13/decision-sample.json",
             "bastion", "마스킹 예시.",
             "xxx", "output_contains", "xxx"),
            ("skill/playbook diff 첨부",
             "cp ~/ccc/data/bastion/skill_playbook_diff.md ~/ccc/reports/w13/ && ls ~/ccc/reports/w13/",
             "bastion", "Bastion 변화 첨부.",
             "skill_playbook_diff.md", "output_contains", "skill_playbook_diff.md"),
            ("증적 체크리스트 생성",
             "cat > ~/ccc/reports/w13/evidence-checklist.md <<'MD'\n- [x] pcap sha256 sealed\n- [x] wazuh alerts json exported\n- [ ] offsite replica\n- [x] masking applied\nMD\ncat ~/ccc/reports/w13/evidence-checklist.md",
             "bastion", "증적 체크리스트.",
             "sha256", "output_contains", "sha256"),
            ("PDF 친화 표(간단 변환 리허설)",
             "markdown2 ~/ccc/reports/w13/report.md > /tmp/report.html 2>/dev/null || cat ~/ccc/reports/w13/report.md | head -10",
             "bastion", "보고서 변환 리허설.",
             "Agent IR", "output_contains", "Agent IR"),
        ],
    },
    14: {
        "title": "다단계 Agentic APT 모의 실사고 대응",
        "description": "5개 에이전트 팀의 킬체인 전체를 대응하고 사고 보고서 초안을 마무리한다.",
        "objectives": [
            "킬체인 전 단계 실시간 대응",
            "세션 클러스터 발동 확인",
            "보고서·자산 diff 업데이트",
        ],
        "steps": [
            ("공방 관전용 대시보드 점검",
             "curl -sk https://10.20.30.100/ 2>&1 | head -3",
             "siem", "Wazuh 대시보드 접속 확인.",
             "html", "output_contains", ""),
            ("공격 세션 시작 기록",
             "echo \"session_start=$(date -Iseconds)\" > ~/ccc/reports/w14/session.meta && cat ~/ccc/reports/w14/session.meta",
             "bastion", "세션 시작 메타.",
             "session_start", "output_contains", "session_start"),
            ("키 신호 수집 — Wazuh 최근 5분 경보 수",
             "sudo jq -c 'select(.timestamp)' /var/ossec/logs/alerts/alerts.json 2>/dev/null | tail -20 | wc -l",
             "siem", "최근 경보 볼륨.",
             "", "output_contains", ""),
            ("Bastion 자산 diff 업데이트",
             "echo '+ multi-session cluster skill, + exfil alert playbook' >> ~/ccc/data/bastion/skill_playbook_diff.md && tail -3 ~/ccc/data/bastion/skill_playbook_diff.md",
             "bastion", "자산 변화 업데이트.",
             "+", "output_contains", "+"),
            ("보고서 초안 실시간 작성(w14)",
             "cp ~/ccc/reports/w13/report.md ~/ccc/reports/w14/report.md && echo '\\n## 4.1 Cluster detection fired at T+18:22' >> ~/ccc/reports/w14/report.md && tail -5 ~/ccc/reports/w14/report.md",
             "bastion", "보고서 초안 확장.",
             "Cluster", "output_contains", "Cluster"),
        ],
    },
    15: {
        "title": "기말 — 종합 Purple + Mythos-readiness",
        "description": "기말 공방 + 자가 진단 + 30/90/365 작전 계획 제출.",
        "objectives": [
            "기말 공방 참여·측정",
            "Mythos-readiness 자가 진단(L0~L5)",
            "조직 실행 계획 초안 작성",
        ],
        "steps": [
            ("기말 제출물 디렉토리",
             "mkdir -p ~/ccc/final && ls ~/ccc/final || true && echo 'dir_ready'",
             "bastion", "최종 제출 준비.",
             "dir_ready", "output_contains", "dir_ready"),
            ("자가 진단 템플릿 작성",
             "cat > ~/ccc/final/mythos-readiness.md <<'MD'\n# Self-Assessment\n- L1 Observer: \n- L2 Reactor: \n- L3 Defender: \n- L4 Co-evolver: \n- L5 Mythos-ready: \nMD\ncat ~/ccc/final/mythos-readiness.md",
             "bastion", "자가 진단 템플릿.",
             "Self-Assessment", "output_contains", "Self-Assessment"),
            ("30/90/365 실행 계획",
             "cat > ~/ccc/final/action-plan.md <<'MD'\n# 30d\n- egress 제한 점검\n- skill 1~2개 운영 SIEM 이식\n# 90d\n- VulnOps 팀/역할 정립\n- Purple 월 1회\n# 365d\n- Co-evolution 루프 자동화\n- CTI 연동 확장\nMD\ncat ~/ccc/final/action-plan.md",
             "bastion", "조직 실행 계획 템플릿.",
             "30d", "output_contains", "30d"),
            ("Bastion diff 최종본",
             "cp ~/ccc/data/bastion/skill_playbook_diff.md ~/ccc/final/ && ls ~/ccc/final/",
             "bastion", "최종 자산 변화.",
             "skill_playbook_diff.md", "output_contains", "skill_playbook_diff.md"),
            ("기말 보고서 본체",
             "cat > ~/ccc/final/final-report.md <<'MD'\n# Final Report\n## 1. Round Results\n## 2. Bastion Asset Growth\n## 3. Mythos-Readiness\n## 4. 30/90/365 Plan\n## 5. Lessons & Course Improvement Proposal\nMD\ncat ~/ccc/final/final-report.md",
             "bastion", "기말 보고서 본체.",
             "Final Report", "output_contains", "Final Report"),
        ],
    },
}

RISK_LEVEL = {"secu": "medium", "web": "low", "siem": "low", "bastion": "low"}


def to_step(order: int, t: tuple, version: str):
    instruction, script, vm, answer_detail, expect_sample, vtype, expect = t
    points = 8 + order  # 약간의 경사
    hint = "리눅스 기본 명령과 실습 호스트 IP를 참고하라"
    answer_cli = f"📎 참고 (CLI): {script}"
    answer = f"🤖 프롬프트: {instruction}\n{answer_cli}"
    bastion_prompt = instruction if version == "ai" else ""
    step = {
        "order": order,
        "instruction": instruction,
        "hint": hint,
        "category": "analysis" if vm in ("bastion", "siem") else "recon",
        "points": points,
        "answer": answer,
        "answer_detail": answer_detail,
        "verify": {"type": vtype, "expect": expect, "field": "stdout"},
        "target_vm": vm,
        "script": script,
        "risk_level": RISK_LEVEL.get(vm, "low"),
        "bastion_prompt": bastion_prompt,
    }
    return step


def build_lab(week: int, version: str) -> dict:
    spec = WEEKS[week]
    course = BASE_COURSE_AI if version == "ai" else BASE_COURSE_NONAI
    title = spec["title"] + (" (AI 지원)" if version == "ai" else " (Non-AI)")
    descr = spec["description"] + (
        " AI SubAgent가 자동으로 명령을 실행하고 결과를 검증합니다." if version == "ai" else
        " 학생이 각 단계를 수동으로 수행하고 결과를 기록합니다."
    )
    steps = [to_step(i + 1, s, version) for i, s in enumerate(spec["steps"])]
    lab = {
        "lab_id": f"{course}-week{week:02d}",
        "title": title,
        "version": version,
        "course": course,
        "week": week,
        "description": descr,
        "difficulty": "hard",
        "duration_minutes": 120,
        "objectives": spec["objectives"],
        "pass_threshold": 0.6,
        "steps": steps,
    }
    return lab


def main():
    for w in range(1, 16):
        for version in ("ai", "nonai"):
            lab = build_lab(w, version)
            outdir = os.path.join(LABS, f"agent-ir-{version}")
            os.makedirs(outdir, exist_ok=True)
            path = os.path.join(outdir, f"week{w:02d}.yaml")
            with open(path, "w", encoding="utf-8") as f:
                yaml.dump(lab, f, allow_unicode=True, sort_keys=False, width=1000)
            print(f"wrote {path}")


if __name__ == "__main__":
    main()
