#!/usr/bin/env python3
"""course19-agent-incident-response 15주 × (ai/nonai) lab YAML 생성 (v2).

v2 개선:
- 주차별 10~12 스텝으로 확장
- 상세 instruction (멀티라인 허용)
- 상세 answer_detail (실제 교육 설명)
- **Non-AI answer**는 CLI만 (🤖 프롬프트 prefix 금지)
- **AI answer**는 🤖 프롬프트 + 📎 참고 CLI
- 교안 내용을 *실제로 재현*하는 실습
"""
from __future__ import annotations
import os, yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LABS = os.path.join(ROOT, "contents", "labs")


def step(order, instruction, cli, vm, detail, expect, vtype="output_contains",
         category="analysis", hint=None, points=None):
    """표준 스텝 구조 반환 (AI/Non-AI 변형은 build_lab에서 처리)."""
    return {
        "order": order,
        "instruction": instruction,
        "hint": hint or f"target_vm={vm}에서 수행. 아래 CLI 예시 참고.",
        "category": category,
        "points": points or (8 + order),
        "_cli": cli,
        "answer_detail": detail,
        "_vtype": vtype,
        "_expect": expect,
        "_vm": vm,
    }


WEEKS = {
    1: {
        "title": "AI Vulnerability Storm 관전과 기준선 설정",
        "description": "과목 첫 주차. 공격 에이전트의 관전 환경을 구축하고, 방어 측에서 관찰 가능한 *기준선 신호*를 모든 VM에서 수집한다. 본 번들이 이후 15주 탐지·분석의 원본 데이터다.",
        "objectives": [
            "실습 인프라 4대 VM의 접속·역할·서비스 상태를 확인한다",
            "Wazuh 대시보드·Suricata 엔진·Apache access 로그의 기준선을 수집한다",
            "학생 개인 Bastion experience 디렉토리를 초기화한다",
            "관전 중 트래픽 캡처와 로그 tail을 동시에 운영할 수 있다",
        ],
        "steps": [
            step(1, "4대 VM(bastion/secu/web/siem) 중 bastion에 SSH로 접속해 hostname·uptime·ip addr 출력으로 VM이 정상 기동됐는지 확인하시오.",
                 "hostname && uptime && ip -4 addr show | grep inet",
                 "bastion",
                 "관전 시작 전 bastion VM의 기본 상태 점검. hostname=bastion, 분 단위 uptime, 10.20.30.201 표시가 정상.",
                 "10.20.30.201"),
            step(2, "secu VM에서 nftables 룰셋을 출력해 방화벽이 로드된 상태인지 확인하시오. `table inet filter` 섹션이 존재해야 한다.",
                 "sudo nft list ruleset | head -50",
                 "secu",
                 "방화벽 기준선. table 정의가 없다면 관전 중 차단 신호 분석이 불가능.",
                 "table"),
            step(3, "secu VM에서 Suricata가 실행 중인지 systemctl로 확인하시오.",
                 "systemctl is-active suricata",
                 "secu",
                 "Suricata 엔진이 활성 상태여야 모든 관전에서 알림 수집 가능.",
                 "active"),
            step(4, "web VM에서 Apache 서비스가 실행 중이며 /var/log/apache2/access.log 파일이 존재하는지 동시에 확인하시오.",
                 "systemctl is-active apache2 && ls -la /var/log/apache2/access.log",
                 "web",
                 "web 측 관전의 원천 로그. 파일 존재 + 서비스 active 모두 필요.",
                 "active"),
            step(5, "siem VM에서 Wazuh Manager 데몬이 실행 중이며 https://10.20.30.100 대시보드가 응답하는지 확인하시오.",
                 "systemctl is-active wazuh-manager && curl -sk -o /dev/null -w 'dashboard=%{http_code}\\n' https://10.20.30.100",
                 "siem",
                 "Wazuh 경보 수집 기준선. active + HTTP 200/302 응답이 정상.",
                 "active"),
            step(6, "siem의 /var/ossec/logs/alerts/alerts.json 파일에서 최근 5개 경보를 확인해 *기준선 경보 분포*를 기록하시오.",
                 "sudo tail -5 /var/ossec/logs/alerts/alerts.json | head -c 2000",
                 "siem",
                 "관전 전 기준선. rule.level·groups 분포를 미리 알아야 공격 관전 중 새 경보를 식별 가능.",
                 "rule"),
            step(7, "bastion에서 w01 관전 아티팩트 디렉토리 구조를 만드시오: artifacts/w01/{pcap,logs,notes,experience}.",
                 "mkdir -p ~/ccc/artifacts/w01/{pcap,logs,notes,experience} && ls ~/ccc/artifacts/w01/",
                 "bastion",
                 "관전 중 생성되는 자료의 저장 공간. 이후 주차에서도 동일 구조 사용.",
                 "experience"),
            step(8, "secu에서 tcpdump로 web 타깃(10.20.30.80)에 대한 60초 트래픽을 /tmp/w01-baseline.pcap 로 캡처하시오. 완료 후 파일 크기를 확인.",
                 "sudo timeout 60 tcpdump -i any -nn -w /tmp/w01-baseline.pcap 'host 10.20.30.80' 2>/dev/null; ls -la /tmp/w01-baseline.pcap",
                 "secu",
                 "기준선 트래픽 — 공격 세션 전의 정상 패턴. 이후 공격 pcap과 delta를 비교해 지문 추출.",
                 "w01-baseline.pcap"),
            step(9, "web VM의 access.log 마지막 100줄에서 HTTP 상태 코드 분포(200/404/403 등)를 집계하시오.",
                 "sudo tail -100 /var/log/apache2/access.log | awk '{c[$9]++} END {for(k in c) print k, c[k]}'",
                 "web",
                 "기준선 상태 코드 분포. 정상 운영에선 200이 압도적, 404는 소수. 공격 중엔 403이 급증하는 패턴을 비교 기준.",
                 "200"),
            step(10, "bastion의 experience 디렉토리에 첫 JSON 엔트리(w01-baseline)를 작성해 관전 시작을 기록하시오.",
                 "mkdir -p ~/ccc/data/bastion/experience && echo '{\"id\":\"w01-baseline\",\"event\":\"observation_started\",\"ts\":\"'$(date -Iseconds)'\"}' > ~/ccc/data/bastion/experience/w01-baseline.json && cat ~/ccc/data/bastion/experience/w01-baseline.json",
                 "bastion",
                 "Bastion Experience의 첫 엔트리. w11 Purple에서 이 기록부터 공격 결과까지 연속된 스토리로 묶인다.",
                 "observation_started"),
            step(11, "4대 VM의 시간이 ±1초 이내로 동기화됐는지 확인하시오 (상관 분석 전제 조건).",
                 "for h in 201 1 80 100; do timeout 3 ssh -o StrictHostKeyChecking=no -o BatchMode=yes ccc@10.20.30.$h 'date -Iseconds' 2>/dev/null || echo skip; done",
                 "bastion",
                 "로그 상관 분석의 기본 조건. NTP 동기화 확인. 1초 이상 어긋나면 w4·w11 타임라인 재구성이 불가능.",
                 "T"),
        ],
    },
    2: {
        "title": "공격자 해부 — Tool-use 루프와 지문 점수",
        "description": "에이전트 실행 프로세스를 방어자 관점에서 관찰하는 도구 세트를 구축한다. pstree·strace·tcpdump·auditd를 결합해 *호스트·네트워크 양측*의 지문을 수집한다.",
        "objectives": [
            "에이전트 호스트의 프로세스 트리와 syscall을 관찰한다",
            "LLM API 호출 패턴(Ollama)의 트래픽 지문을 수집한다",
            "agent_score 함수의 핵심 지표(IAT·경로 다양성 등)를 구현한다",
            "관찰 불가능한 공격자 환경과 관찰 가능한 방어자 환경의 경계를 구분한다",
        ],
        "steps": [
            step(1, "bastion에서 pstree로 ollama 서비스의 프로세스 트리를 표시하시오(에이전트 모델 호출이 이뤄지는 프로세스 관찰 연습).",
                 "pstree -p $(pgrep -f ollama | head -1 || echo 1) | head -30",
                 "bastion",
                 "에이전트 프로세스 계보 관찰법 학습. 공격자 환경에선 못 보지만, Bastion 자체의 LLM 호출 패턴을 관찰하는 훈련.",
                 ""),
            step(2, "bastion에서 `curl -sX POST http://localhost:11434/api/tags`로 Ollama에 로드된 모델 목록을 조회하시오.",
                 "curl -s http://localhost:11434/api/tags | python3 -m json.tool | head -30",
                 "bastion",
                 "에이전트가 사용하는 LLM 추론 지점. 모델 이름·버전이 공격 분석에 중요.",
                 "models",
                 category="recon"),
            step(3, "bastion에서 auditd 서비스 상태를 확인하시오(Transient Tool 관찰의 전제).",
                 "systemctl is-active auditd || echo 'auditd_not_active'",
                 "bastion",
                 "파일 쓰기·프로세스 생성 감사의 기반. 활성이 아니면 w4 실습에서 Transient Tool 추적 불가.",
                 ""),
            step(4, "secu에서 tcpdump로 Ollama API 트래픽(11434 포트)을 30초 캡처하시오.",
                 "sudo timeout 30 tcpdump -i any -nn -w /tmp/w02-ollama.pcap 'port 11434' 2>/dev/null; ls -la /tmp/w02-ollama.pcap",
                 "secu",
                 "LLM API 호출의 네트워크 지문. 요청 간격·크기가 *에이전트 지문*의 핵심 축.",
                 "w02-ollama.pcap"),
            step(5, "bastion에 agent_score.py 스크립트를 생성해 IAT CoV 계산 함수를 정의하시오.",
                 "mkdir -p ~/ccc/scripts && cat > ~/ccc/scripts/agent_score.py <<'PY'\nimport statistics as st\ndef iat_cov(times):\n    if len(times) < 2: return 1.0\n    iat = [b-a for a,b in zip(times, times[1:])]\n    m = st.mean(iat)\n    return st.pstdev(iat)/m if m else 0.0\nprint('iat_cov', iat_cov([1.0, 2.0, 3.0, 4.0]))\nPY\npython3 ~/ccc/scripts/agent_score.py",
                 "bastion",
                 "에이전트 지문 1지표. 정상 사용자는 CoV>0.5, 에이전트는 <0.3 경향.",
                 "iat_cov"),
            step(6, "web에서 access.log 최근 200줄의 고유 경로 수를 계산하시오 (경로 다양성 지표).",
                 "sudo tail -200 /var/log/apache2/access.log | awk '{print $7}' | sort -u | wc -l",
                 "web",
                 "경로 다양성 지표. 정상 사용자는 보통 2~8개, 에이전트는 15+.",
                 ""),
            step(7, "web access.log에서 HTTP 4xx 응답 후 1초 이내 재요청 패턴을 찾으시오 (재시도 지연 지표).",
                 "sudo awk '$9 ~ /^4/ {print $4, $7, $9}' /var/log/apache2/access.log | tail -10",
                 "web",
                 "4xx 응답 후 재시도 지연이 짧으면 에이전트 의심. 정상은 수초~수분.",
                 ""),
            step(8, "bastion에 Tool-use 루프의 방어자 관점 도식 파일을 작성하시오.",
                 "cat > ~/ccc/artifacts/w02/tool_use_layers.md <<'MD'\n# Tool-use 루프 관측 지점\n- 모델 추론(③): 관찰 불가\n- 도구 실행(⑤): 호스트 strace·auditd\n- 도구 결과(⑥): stdout·네트워크 응답\n- 모델 재호출(⑦): LLM API 재호출 트래픽\nMD\ncat ~/ccc/artifacts/w02/tool_use_layers.md",
                 "bastion",
                 "학습한 관측 지점을 문서화. w11 Purple에서 이 표를 기반으로 Bastion 탐지 위치 결정.",
                 "관측 지점"),
            step(9, "secu의 eve.json에서 최근 HTTP 이벤트 샘플 추출(Suricata 지문 수집).",
                 "sudo jq -c 'select(.event_type==\"http\")' /var/log/suricata/eve.json 2>/dev/null | tail -3 | head -c 1500 || echo 'no_http_events_yet'",
                 "secu",
                 "HTTP 이벤트의 구조 파악. w5·w6에서 탐지 룰 설계 시 필드 경로 참고.",
                 ""),
            step(10, "bastion experience에 w02 지문 지표 샘플 저장.",
                 "cat > ~/ccc/data/bastion/experience/w02-fingerprint.json <<'J'\n{\"id\":\"w02-fp\",\"metrics\":{\"iat_cov\":0.25,\"path_div\":14,\"retry_sub_1s\":0.32},\"score\":0.78,\"interpretation\":\"agent-like\"}\nJ\ncat ~/ccc/data/bastion/experience/w02-fingerprint.json",
                 "bastion",
                 "w02 산출물. w11 Purple Round 1의 첫 입력.",
                 "agent-like"),
            step(11, "에이전트 지문 감지 기준 요약 문서 작성.",
                 "cat > ~/ccc/artifacts/w02/fingerprint-criteria.md <<'MD'\n# 에이전트 지문 기준\n| 지표 | 에이전트 | 정상 |\n|---|---|---|\n| IAT CoV | <0.3 | >0.5 |\n| 경로 다양성/3분 | >=10 | <=5 |\n| 4xx→재시도 지연 | <3s | >10s |\nMD\ncat ~/ccc/artifacts/w02/fingerprint-criteria.md",
                 "bastion",
                 "w5의 탐지 룰 설계 기준. 이 표가 곧 룰의 임계값이 된다.",
                 "CoV"),
        ],
    },
    3: {
        "title": "초지능 정찰 — 방어 관점 신호 수집",
        "description": "에이전트 정찰의 전형적 신호 5원자(ReqBurst·FailSeq·FingerQuery·ToolMix·SessionSilence)를 재현·계측한다.",
        "objectives": [
            "에이전트 스타일의 정찰 트래픽을 생성한다",
            "5원자 각각의 측정 지표를 스크립트로 구현한다",
            "ATT&CK Reconnaissance(TA0043) 기법에 로그를 매핑한다",
        ],
        "steps": [
            step(1, "web 타깃의 /robots.txt · /sitemap.xml · /api/ 응답을 하나씩 확인(정찰 초기 패턴 재현).",
                 "for p in /robots.txt /sitemap.xml /api/; do curl -s -o /dev/null -w '%{http_code} %{url_effective}\\n' http://10.20.30.80$p; done",
                 "bastion",
                 "정보 수집형 요청 3종. 응답 코드 분포 기록.",
                 "200",
                 category="recon"),
            step(2, "web에 JuiceShop의 score-board 경로 접근을 시도(유명 프레임워크 지문 추출).",
                 "curl -s -o /dev/null -w '%{http_code}\\n' http://10.20.30.80:3000/#/score-board",
                 "bastion",
                 "JuiceShop 특유 경로. 에이전트가 *내부 지식*으로 즉시 시도하는 대표 예.",
                 "",
                 category="recon"),
            step(3, "web 로그인 엔드포인트에 20회 반복 요청을 생성(ReqBurst 신호 재현).",
                 "for i in $(seq 1 20); do curl -s -o /dev/null -X POST http://10.20.30.80:3000/rest/user/login -H 'Content-Type: application/json' -d '{\"email\":\"a'$i'@x\",\"password\":\"x\"}'; done; echo burst_done",
                 "bastion",
                 "20회 짧은 간격 요청. 에이전트 ReqBurst 지문 핵심 패턴.",
                 "burst_done",
                 category="recon"),
            step(4, "secu에서 Suricata 빠른 로그를 확인해 정찰 탐지 발생 여부를 조사.",
                 "sudo tail -20 /var/log/suricata/fast.log | grep -Ei 'scan|recon|enum' || echo 'NO_RECON_ALERT_YET'",
                 "secu",
                 "기본 Suricata 룰셋이 정찰 패턴을 잘 안 잡는 현상을 직접 확인. w5에서 룰 추가의 동기.",
                 ""),
            step(5, "web access.log에서 같은 IP의 HTTP 상태 코드 분포를 IP별로 집계(ReqBurst 측정 근거).",
                 "sudo tail -200 /var/log/apache2/access.log | awk '{c[$1\"_\"$9]++} END{for(k in c) print k, c[k]}' | sort -rn -k2 | head -10",
                 "web",
                 "IP별 코드 분포. 20+ 4xx가 한 IP에 몰리면 정찰 지문.",
                 ""),
            step(6, "FailSeq 신호 — 4xx 응답 후 3초 이내 재시도 횟수 계산(Python 스니펫).",
                 "python3 -c \"import subprocess; out=subprocess.check_output(['sudo','tail','-500','/var/log/apache2/access.log']).decode(); lines=out.splitlines(); print('total_lines', len(lines))\"",
                 "web",
                 "재시도 분포 계산의 기본형. 실 데이터에선 datetime 파싱 필요.",
                 "total_lines"),
            step(7, "FingerQuery 신호 — 정보 목적 경로(/server-status, /.git/config, /actuator/info 등) 확인.",
                 "for p in /server-status /.git/config /actuator/info /package.json /.env; do curl -s -o /dev/null -w '%{http_code} '$p'\\n' http://10.20.30.80$p; done",
                 "bastion",
                 "기술 스택 지문을 노리는 경로 5개. 404로 귀결되는 게 정상, 일부라도 200이면 정보 누출.",
                 "404",
                 category="recon"),
            step(8, "ToolMix 신호 — 같은 IP에서 User-Agent 3종 혼재 감지.",
                 "sudo tail -200 /var/log/apache2/access.log | awk -F'\"' '{print $6}' | sort | uniq -c | sort -rn | head",
                 "web",
                 "User-Agent 분포. 3종+ 혼재면 에이전트 의심.",
                 ""),
            step(9, "정찰 신호 5원자 기준을 파일로 정리.",
                 "cat > ~/ccc/artifacts/w03/signals.md <<'MD'\n# 정찰 5원자\n| 신호 | 임계 | 탐지 위치 |\n|---|---|---|\n| ReqBurst | >=10 uniq paths/120s | web access.log |\n| FailSeq | 4xx→재시도 5회 <3s | web |\n| FingerQuery | 지문 경로 5+/60s | web |\n| ToolMix | UA 3종+/src | web |\n| SessionSilence | 쿠키 없이 10+요청 | web |\nMD\ncat ~/ccc/artifacts/w03/signals.md",
                 "bastion",
                 "5원자 기준표. w5 SIGMA 룰의 직접 입력.",
                 "ReqBurst"),
            step(10, "ATT&CK 매핑 — 재현한 활동을 Technique ID로 기록.",
                 "cat > ~/ccc/artifacts/w03/attck-map.md <<'MD'\n| 활동 | Tactic | Technique |\n|---|---|---|\n| /robots.txt 탐색 | TA0043 | T1595.002 |\n| JuiceShop 지문 | TA0043 | T1592.002 |\n| 반복 로그인 시도 | TA0043→TA0006 | T1110 |\nMD\ncat ~/ccc/artifacts/w03/attck-map.md",
                 "bastion",
                 "ATT&CK 매핑. w13 보고서의 *분석 섹션*에 그대로 사용.",
                 "TA0043"),
            step(11, "experience 저장.",
                 "mkdir -p ~/ccc/data/bastion/experience && echo '{\"id\":\"w03-recon\",\"signals\":[\"ReqBurst\",\"FailSeq\",\"FingerQuery\"],\"target\":\"10.20.30.80\"}' > ~/ccc/data/bastion/experience/w03-recon.json && cat ~/ccc/data/bastion/experience/w03-recon.json",
                 "bastion",
                 "정찰 시나리오 경험 저장.",
                 "ReqBurst"),
        ],
    },
    4: {
        "title": "자동 익스플로잇 — Transient Tool 아티팩트",
        "description": "에이전트가 세션 내 생성한 공격 도구(Transient Tool)의 흔적을 방어자 관점에서 포렌식으로 재구성한다.",
        "objectives": [
            "Transient Tool 생성·진화·폐기를 auditd로 추적한다",
            "ModSecurity 응답을 비교해 시그니처 공백을 체감한다",
            "3층 방어(메타·응답·기만)의 실무 예시를 각각 구현한다",
        ],
        "steps": [
            step(1, "web VM에 auditd로 /tmp 쓰기 감시 룰을 일시적으로 추가.",
                 "sudo auditctl -w /tmp -p wa -k tmpwrites && sudo auditctl -l | tail -5",
                 "web",
                 "Transient Tool이 /tmp에 생성·수정되는 것을 감시. 실제 운영 환경에서는 *적용 범위*를 좁혀야 부하 감당 가능.",
                 "tmpwrites"),
            step(2, "Transient Tool을 3개 버전으로 시뮬레이션 생성 (공격자 자가 수정 루프 재현).",
                 "for v in 1 2 3; do cat > /tmp/exp_v$v.py <<PY\n# auto-generated exploit v$v — $(date +%s)\nimport requests\nr = requests.post('http://10.20.30.80/test', data={'q':'payload_v$v'})\nPY\ndone; ls -la /tmp/exp_v*.py",
                 "web",
                 "v1→v2→v3 연속 수정. 사람은 같은 파일을 분 단위로 이렇게 고치지 않는 패턴이 지문이 된다.",
                 "exp_v"),
            step(3, "auditd 결과를 조회해 생성 이벤트를 확인.",
                 "sudo ausearch -k tmpwrites --start recent 2>/dev/null | tail -30 | head -30",
                 "web",
                 "auditd가 각 파일 write를 기록. 같은 path에 반복 write가 보이면 자가 수정 루프 증거.",
                 ""),
            step(4, "web에서 단일 SQLi 페이로드 시도(WAF 반응 확인).",
                 "curl -s -o /dev/null -w '%{http_code}\\n' 'http://10.20.30.80:8082/login?q=admin%27%20OR%201=1--'",
                 "web",
                 "WAF가 있으면 403, 없으면 404/200. w6의 변형 공격 대비.",
                 "",
                 category="attack"),
            step(5, "URL 인코딩 2중 적용한 변형 페이로드로 WAF 우회 시도.",
                 "curl -s -o /dev/null -w '%{http_code}\\n' 'http://10.20.30.80:8082/login?q=admin%2527%2520OR%25201=1--'",
                 "web",
                 "에이전트 회피의 기본. 동일 의미·다른 문자열로 시그니처 회피.",
                 "",
                 category="attack"),
            step(6, "ModSecurity 감사 로그가 있으면 매칭 룰 분포 조사.",
                 "sudo tail -50 /var/log/bunkerweb/modsec_audit.log 2>/dev/null | grep -oE 'id \"[0-9]+\"' | sort | uniq -c | sort -rn | head || echo 'no_modsec_log'",
                 "web",
                 "어떤 룰이 얼마나 매칭됐는지. 942xxx (SQLi CRS)가 자주 뜨면 정상.",
                 ""),
            step(7, "1층 방어 — 응답 엔트로피 측정 함수 작성.",
                 "cat > ~/ccc/scripts/entropy.py <<'PY'\nimport math\nfrom collections import Counter\ndef H(s):\n    if not s: return 0.0\n    c = Counter(s); t = len(s)\n    return -sum((f/t)*math.log2(f/t) for f in c.values())\nprint('sample_entropy', H('UNION SELECT user,pass FROM users--'))\nPY\npython3 ~/ccc/scripts/entropy.py",
                 "bastion",
                 "1층(메타 판별) 핵심 도구. 페이로드 본문 엔트로피가 점진 변화하는 세션 식별.",
                 "sample_entropy"),
            step(8, "2층 방어 — 에러 응답 통일화 HTML 파일 생성.",
                 "sudo bash -c 'cat > /var/www/html/error.html <<H\n<!DOCTYPE html><html><body><h1>Not available</h1><p>Reference: <span id=r></span></p><script>document.getElementById(\"r\").textContent=crypto.randomUUID();</script></body></html>\nH' && ls /var/www/html/error.html",
                 "web",
                 "403/404/500을 *동일 본문*으로 통일해 공격자에게 단서 최소화.",
                 "error.html"),
            step(9, "3층 방어 — 허니 API 응답 JSON 파일 생성.",
                 "sudo bash -c 'cat > /var/www/html/honey-users.json <<J\n{\"users\":[{\"id\":1,\"email\":\"admin@example.com\",\"role\":\"superadmin\",\"api_key\":\"HONEY_87af3b1c_DO_NOT_REMOVE\"}]}\nJ' && cat /var/www/html/honey-users.json",
                 "web",
                 "허니 API 응답. 공격자가 이를 사용하면 재관측 룰로 확정 탐지.",
                 "HONEY"),
            step(10, "아티팩트 번들 구조 준비.",
                 "mkdir -p ~/ccc/artifacts/w04/{session,tools,pcap,server-logs,timeline}/ && ls ~/ccc/artifacts/w04",
                 "bastion",
                 "w04 산출물 표준 구조. w11에서 Bastion 스킬 설계에 이 번들을 입력.",
                 "timeline"),
            step(11, "SMART 제안 탐지 룰 작성.",
                 "cat > ~/ccc/artifacts/w04/detection-rules.md <<'MD'\n# 탐지 룰 3개 (SMART)\n1. 500 응답 2회 + 동일 경로 재시도 < 3s → 500 유발 스캔 의심\n2. ModSec 942100 3회 < 60s + 동일 src → SQLi 시도 확정\n3. 세션 중 페이로드 Levenshtein 0.05~0.4 변형 5+회 → 변형 진화\nMD\ncat ~/ccc/artifacts/w04/detection-rules.md",
                 "bastion",
                 "SMART(구체·측정가능·실행가능·관련·시간제한) 탐지 룰. w9 Wazuh 변환의 입력.",
                 "SMART"),
            step(12, "auditd 감시 해제(실습 후 정리).",
                 "sudo auditctl -W /tmp -p wa -k tmpwrites 2>&1 | head -1 || true && sudo auditctl -l | wc -l",
                 "web",
                 "임시 룰 정리. 실 운영은 /etc/audit/rules.d/*.rules로 영속화.",
                 ""),
        ],
    },
    5: {
        "title": "측면이동·지속성 — 내부 행위 감시",
        "description": "에이전트 측면이동의 네트워크·호스트 지문을 재현·수집하고, Bastion 스킬로 연결하는 준비를 완성한다.",
        "objectives": [
            "ARP·라우팅·내부 스캔 패턴을 수집한다",
            "지속성 메커니즘(SSH 키·cron·systemd) 생성 이벤트를 감시한다",
            "Bastion `detect_internal_scan` 스킬의 실제 YAML 명세를 작성한다",
        ],
        "steps": [
            step(1, "web에서 ARP 테이블·라우팅을 조회(측면이동 초기 정찰 시뮬).",
                 "ip neigh show && echo --- && ip route",
                 "web",
                 "에이전트가 내부 대역 구조 파악 시 보는 정보. *정상 관리 활동*과 구분이 어렵다는 점을 체험.",
                 "",
                 category="recon"),
            step(2, "web에서 내부 호스트 4대 ICMP 응답 확인.",
                 "for h in 1 80 100 201; do ping -c 1 -W 1 10.20.30.$h > /dev/null 2>&1 && echo 10.20.30.$h UP || echo 10.20.30.$h DOWN; done",
                 "web",
                 "4대 내부 도달 가능성. 에이전트가 ping sweep으로 시작하는 전형.",
                 "UP"),
            step(3, "secu에서 최근 내부→내부 SSH 시도를 auth.log로 확인.",
                 "sudo tail -50 /var/log/auth.log | grep -Ei 'sshd|Failed|Accepted' | tail -20",
                 "secu",
                 "내부 SSH 시도 증거. 정상 관리자 vs 공격자 측면이동 구분은 *소스 IP 화이트리스트*로.",
                 ""),
            step(4, "Wazuh의 SSH 관련 경보 확인 (rule 5700대).",
                 "sudo jq -c 'select(.rule.id | tostring | startswith(\"57\"))' /var/ossec/logs/alerts/alerts.json 2>/dev/null | tail -3 || echo 'no_recent_ssh_alerts'",
                 "siem",
                 "Wazuh 5700대 룰(SSH). 실제 공격 시 5712(multiple failures)·5720(brute) 급증.",
                 ""),
            step(5, "web에 지속성 시뮬 — authorized_keys 변화 감시 시작.",
                 "sudo auditctl -w /home -p wa -k home_write && sudo auditctl -l | grep home_write",
                 "web",
                 "Persistence T1098 감시. 실제 공격 시 ~/.ssh/authorized_keys 추가가 핵심.",
                 "home_write"),
            step(6, "web에 가짜 persistence 시뮬 — .ssh 디렉토리 생성.",
                 "mkdir -p ~/.ssh && echo '# test entry $(date +%s)' >> ~/.ssh/authorized_keys && ls -la ~/.ssh/",
                 "web",
                 "의도적으로 authorized_keys 수정 이벤트 발생. auditd 추적 대상.",
                 "authorized_keys"),
            step(7, "auditd로 해당 이벤트 조회.",
                 "sleep 2 && sudo ausearch -k home_write --start recent 2>/dev/null | tail -20 | head -20",
                 "web",
                 "이벤트가 감사 로그에 잡혔는지 확인. 이것이 w11 Purple에서 Bastion이 볼 신호.",
                 ""),
            step(8, "Bastion Skill YAML 명세 초안 작성 (`detect_internal_scan`).",
                 "mkdir -p ~/ccc/skills && cat > ~/ccc/skills/detect_internal_scan.yaml <<'Y'\nskill_id: detect_internal_scan\nversion: 0.1\npurpose: 내부 대역 10.20.30.0/24 내에서 측면이동 정찰 탐지\ninputs:\n  - source: secu_tcpdump\n    window_sec: 300\nlogic:\n  - aggregate by (src_ip, dst_ip, dst_port)\n  - count distinct dst_ip per src, distinct dst_port per src\nthresholds:\n  distinct_dst: 3\n  distinct_port: 20\nexceptions:\n  - src_ip_in: admin_whitelist.source_ips\noutputs:\n  alert_level: 10\n  actions: [tar_pit_10m, wazuh_alert]\nfailure_mode:\n  false_positive_mitigation: shadow_mode_24h\nY\ncat ~/ccc/skills/detect_internal_scan.yaml",
                 "bastion",
                 "w11 Purple에서 Bastion에 *실제로 등록*될 스킬 명세. 임계값의 근거가 이 주차의 관찰 데이터.",
                 "detect_internal_scan"),
            step(9, "Bastion Skill 명세 리뷰 체크리스트 문서 작성.",
                 "cat > ~/ccc/artifacts/w05/review-checklist.md <<'MD'\n- [ ] purpose가 구체적 시나리오 기술\n- [ ] thresholds 근거(관찰 데이터) 명시\n- [ ] exceptions(화이트리스트) 반영\n- [ ] failure_mode 롤백 경로\n- [ ] test_cases 긍정·부정 양면\nMD\ncat ~/ccc/artifacts/w05/review-checklist.md",
                 "bastion",
                 "짝꿍 리뷰용 체크리스트. 교차 리뷰 습관 형성.",
                 "thresholds"),
            step(10, "admin_whitelist.yaml 샘플 작성.",
                 "mkdir -p ~/ccc/data/bastion && cat > ~/ccc/data/bastion/admin_whitelist.yaml <<'Y'\nadmins:\n  - user: alice\n    source_ips: [10.20.30.50, 10.20.30.51]\n    allowed_hosts: [bastion, secu, web, siem]\n    time_window: {start: \"09:00\", end: \"19:00\", tz: \"Asia/Seoul\"}\nY\ncat ~/ccc/data/bastion/admin_whitelist.yaml",
                 "bastion",
                 "관리자 화이트리스트. w11에서 오탐 방지의 1차 장치.",
                 "alice"),
            step(11, "experience 저장.",
                 "echo '{\"id\":\"w05-lm\",\"finding\":\"internal_scan_pattern\",\"signals\":[\"arp_lookup\",\"ssh_fail_burst\"]}' > ~/ccc/data/bastion/experience/w05-lm.json && cat ~/ccc/data/bastion/experience/w05-lm.json",
                 "bastion",
                 "w05 경험 로그.",
                 "internal_scan_pattern"),
            step(12, "임시 auditd 룰 정리.",
                 "sudo auditctl -W /home -p wa -k home_write 2>&1 | head -1 || true && echo cleanup_done",
                 "web",
                 "실습 후 룰 정리. 영속화는 /etc/audit/rules.d/ 사용.",
                 "cleanup_done"),
        ],
    },
    6: {
        "title": "회피·다형성 — 변형 진화 탐지",
        "description": "같은 의미·다른 표면의 페이로드를 연속 투입해 WAF 반응을 비교하고, 변형 진화 탐지 로직을 구현한다.",
        "objectives": [
            "인코딩·분할·타이밍 3축 변형을 직접 만들어 본다",
            "세션 내 페이로드 유사도 진화 함수를 파이썬으로 구현한다",
            "단서 최소화 10개 체크 중 3개를 실제 적용한다",
        ],
        "steps": [
            step(1, "원본 SQLi 페이로드로 WAF 반응 기준선.",
                 "curl -s -o /dev/null -w 'code=%{http_code}\\n' -X POST http://10.20.30.80:8082/rest/user/login -H 'Content-Type: application/json' -d '{\"email\":\"admin\\\" OR 1=1--\",\"password\":\"x\"}'",
                 "web",
                 "1차 페이로드. WAF가 있으면 403, 없으면 다른 코드.",
                 "code=",
                 category="attack"),
            step(2, "인코딩 변형 — URL 이중 인코딩.",
                 "curl -s -o /dev/null -w 'code=%{http_code}\\n' 'http://10.20.30.80:8082/rest/user/login?email=admin%2527%2520OR%25201%253D1--&password=x'",
                 "web",
                 "%25 이중 인코딩. 디코딩 1회만 하는 WAF는 놓치기도 한다.",
                 "code=",
                 category="attack"),
            step(3, "인코딩 변형 — Unicode full-width.",
                 "curl -s -o /dev/null -w 'code=%{http_code}\\n' 'http://10.20.30.80:8082/rest/user/login?email=admin＇ＯＲ１＝１--&password=x'",
                 "web",
                 "Unicode full-width로 우회 시도. CRS의 일부 룰만 처리 가능.",
                 "code=",
                 category="attack"),
            step(4, "분할 변형 — 주석으로 공백 분할.",
                 "curl -s -o /dev/null -w 'code=%{http_code}\\n' 'http://10.20.30.80:8082/rest/user/login?email=admin%27/**/OR/**/1=1--&password=x'",
                 "web",
                 "/**/로 토큰 분할. 고전 우회 기법.",
                 "code=",
                 category="attack"),
            step(5, "타이밍 변형 — 1초 간격으로 같은 페이로드 반복.",
                 "for i in 1 2 3; do curl -s -o /dev/null -w 'try='$i' code=%{http_code}\\n' http://10.20.30.80:8082/rest/user/login -d '{\"email\":\"a\"}' -H 'Content-Type: application/json'; sleep 1; done",
                 "web",
                 "타이밍 축 변형. 속도만으로는 회피 약함.",
                 "try=",
                 category="attack"),
            step(6, "ModSec 감사 로그에서 룰 매칭 분포 재조사.",
                 "sudo tail -100 /var/log/bunkerweb/modsec_audit.log 2>/dev/null | grep -oE 'id \"[0-9]+\"' | sort | uniq -c | sort -rn | head || echo 'no_modsec_events'",
                 "web",
                 "어떤 변형이 어느 룰에 걸렸는지 분포. *CRS 942xxx*가 SQLi 카테고리.",
                 ""),
            step(7, "페이로드 변형 진화 탐지 함수 작성.",
                 "cat > ~/ccc/scripts/evolve.py <<'PY'\nfrom difflib import SequenceMatcher\ndef evolving(bodies):\n    diffs = [1-SequenceMatcher(None,a,b).ratio() for a,b in zip(bodies, bodies[1:])]\n    count = sum(1 for d in diffs if 0.05 < d < 0.4)\n    return count >= 5, diffs\nbodies=[\"admin OR 1=1\",\"admin' OR 1=1--\",\"admin'/**/OR/**/1=1\",\"admin'+OR+1=1\",\"admin%27%20OR%201=1\",\"admin' UNION SELECT 1\"]\nok, diffs = evolving(bodies)\nprint('evolving', ok, 'diffs', [round(d,2) for d in diffs])\nPY\npython3 ~/ccc/scripts/evolve.py",
                 "bastion",
                 "부분 변형 탐지. 0.05~0.4는 '점진적' 변화. 5회+면 에이전트 회피 시도 의심.",
                 "evolving"),
            step(8, "단서 최소화 #1 — Apache ServerTokens Prod 설정 여부 확인.",
                 "sudo grep -i ServerTokens /etc/apache2/conf-enabled/security.conf 2>/dev/null || echo 'default_Full'",
                 "web",
                 "기본은 Full(버전 노출). Prod로 바꿔야 단서 최소화.",
                 ""),
            step(9, "단서 최소화 #2 — 에러 페이지 커스텀 확인.",
                 "ls -la /var/www/html/error.html 2>/dev/null && echo 'error_page_ok' || echo 'no_custom_error'",
                 "web",
                 "w04에서 만든 error.html 재사용. 500/403/404를 같은 페이지로.",
                 "error"),
            step(10, "단서 최소화 #3 — ModSec 응답에 룰 ID 노출 여부 확인.",
                 "curl -si http://10.20.30.80:8082/ 2>/dev/null | grep -Ei 'modsec|rule|apache|server:' | head -5",
                 "web",
                 "응답 헤더에 ModSec·Apache 버전 노출되면 안 됨. 노출 시 obfuscate 설정 필요.",
                 ""),
            step(11, "단서 최소화 체크리스트 저장.",
                 "cat > ~/ccc/artifacts/w06/clue-min.md <<'MD'\n# 단서 최소화 10개 체크\n- [x] ServerTokens Prod\n- [x] 커스텀 error 페이지\n- [x] ModSec rule ID 숨김\n- [ ] 세션 토큰 난수성\n- [ ] 404/500 통일\n- [ ] CAPTCHA 난수화\n- [ ] 로그인 실패 메시지 통일\n- [ ] CORS 정책 일관성\n- [ ] 관리 페이지 경로 은닉 금지(대신 MFA)\n- [ ] Rate-limit 응답 난수화\nMD\ncat ~/ccc/artifacts/w06/clue-min.md",
                 "bastion",
                 "10개 체크 중 3개 적용. 나머지 7개는 후속 주차 또는 조직 적용 시.",
                 "단서 최소화"),
            step(12, "experience 저장.",
                 "echo '{\"id\":\"w06-evasion\",\"variants_tried\":5,\"waf_hit_rate\":\"TBD\"}' > ~/ccc/data/bastion/experience/w06-evasion.json && cat ~/ccc/data/bastion/experience/w06-evasion.json",
                 "bastion",
                 "변형 시도 기록.",
                 "variants"),
        ],
    },
    7: {
        "title": "규모화 — 다중 에이전트 시뮬레이션",
        "description": "3~5개 병렬 요청을 내서 세션 클러스터링·트리아지 우선순위를 직접 적용한다.",
        "objectives": [
            "3개 역할 분할 공격 트래픽을 생성한다",
            "세션 클러스터링 알고리즘을 파이썬으로 구현한다",
            "경보 트리아지 P0~P3 분류를 실제 데이터에 적용한다",
        ],
        "steps": [
            step(1, "세션 A — 정찰성 요청(3분 내 15경로).",
                 "for p in / /about /login /admin /api /static/logo.png /robots.txt /sitemap.xml /rest /rest/user /rest/products /api/v1 /api/v2 /docs /.well-known; do curl -s -o /dev/null http://10.20.30.80$p; done; echo session_A_done",
                 "web",
                 "세션 A(정찰) 트래픽. ReqBurst 지문 유발.",
                 "session_A_done",
                 category="recon"),
            step(2, "세션 B — 로그인 브루트 시도(10회).",
                 "for i in $(seq 1 10); do curl -s -o /dev/null -X POST http://10.20.30.80:3000/rest/user/login -H 'Content-Type: application/json' -d '{\"email\":\"u'$i'@t.com\",\"password\":\"pwd'$i'\"}'; done; echo session_B_done",
                 "web",
                 "세션 B(브루트) 트래픽. Credential Access 신호.",
                 "session_B_done",
                 category="attack"),
            step(3, "세션 C — API 경로 열거(6경로).",
                 "for p in /api /rest /internal /admin /actuator /metrics; do curl -s -o /dev/null -w '%{http_code} '$p'\\n' http://10.20.30.80$p; done; echo session_C_done",
                 "web",
                 "세션 C(API 탐색) 트래픽.",
                 "session_C_done",
                 category="recon"),
            step(4, "access.log에서 3세션 트래픽이 시간대에 겹치는지 확인.",
                 "sudo tail -60 /var/log/apache2/access.log | awk '{print $4}' | sort -u | tail -5",
                 "web",
                 "시간대 분포. 동시성이 중요 — 같은 창 안에 3세션이 겹치면 클러스터 후보.",
                 ""),
            step(5, "세션 클러스터링 스크립트 작성(IP·UA·경로 유사).",
                 "cat > ~/ccc/scripts/cluster.py <<'PY'\ndef cluster(sessions):\n    groups = {}\n    for s in sessions:\n        key = (s.get('ja3','?'), s.get('ua_class','?'), s.get('ip_24','?'))\n        groups.setdefault(key, []).append(s)\n    return {k:v for k,v in groups.items() if len(v)>=2}\nprint('cluster_test', cluster([{'ja3':'x','ua_class':'curl','ip_24':'10.20.30','id':'s1'},\n                                {'ja3':'x','ua_class':'curl','ip_24':'10.20.30','id':'s2'},\n                                {'ja3':'y','ua_class':'browser','ip_24':'10.20.30','id':'s3'}]))\nPY\npython3 ~/ccc/scripts/cluster.py",
                 "bastion",
                 "세션 클러스터링 기본. JA3·UA·IP/24 앙상블.",
                 "cluster_test"),
            step(6, "트리아지 P0~P3 분류 스크립트 작성.",
                 "cat > ~/ccc/scripts/triage.py <<'PY'\ndef triage(alert):\n    if alert.get('success') and alert.get('sensitive_data'): return 'P0'\n    if alert.get('cluster_size', 1) >= 3: return 'P1'\n    if alert.get('signature_matched'): return 'P2'\n    return 'P3'\nfor a in [{'success':True, 'sensitive_data':True}, {'cluster_size':4}, {'signature_matched':True}, {}]:\n    print(triage(a), a)\nPY\npython3 ~/ccc/scripts/triage.py",
                 "bastion",
                 "경보 우선순위 결정의 기본 로직.",
                 "P0"),
            step(7, "노이즈 스톰 감지 스크립트 작성.",
                 "cat > ~/ccc/scripts/noise.py <<'PY'\ndef noise_storm(alert_count_5min, baseline=30):\n    return alert_count_5min > baseline * 5\nprint(noise_storm(200))  # True\nprint(noise_storm(10))   # False\nPY\npython3 ~/ccc/scripts/noise.py",
                 "bastion",
                 "경보 5배 급증 → 노이즈 스톰. 조용한 세션을 오히려 상향.",
                 "True"),
            step(8, "CorrelationEngine 인터페이스 설계 문서.",
                 "cat > ~/ccc/artifacts/w07/engine.md <<'MD'\n# CorrelationEngine API\n```python\nclass CorrelationEngine:\n    def ingest(self, event): ...\n    def cluster(self, window=300): ...\n    def score_cluster(self, cluster): ...\n    def triage(self, cluster): ...\n    def emit_action(self, cluster, priority): ...\n```\nMD\ncat ~/ccc/artifacts/w07/engine.md",
                 "bastion",
                 "w11에서 Bastion에 실제 구현할 엔진 API. 지금은 *인터페이스*만 고정.",
                 "CorrelationEngine"),
            step(9, "세션 간 유사도 임계값 설정 문서.",
                 "cat > ~/ccc/artifacts/w07/thresholds.md <<'MD'\n| 축 | 느슨 | 표준 | 엄격 |\n|---|---|---|---|\n| JA3 | 일치 | 일치 | 일치 |\n| UA | 일치 | 클래스 | 카테고리 |\n| IAT p-value | >0.1 | >0.2 | >0.3 |\n| 경로 Jaccard | >0.3 | >0.5 | >0.7 |\nMD\ncat ~/ccc/artifacts/w07/thresholds.md",
                 "bastion",
                 "표준 시작 → 오탐률에 따라 조정. w12 Canary 트래픽으로 검증.",
                 "임계"),
            step(10, "experience 저장.",
                 "echo '{\"id\":\"w07-scale\",\"sessions_launched\":3,\"cluster_detected\":true,\"noise_storm\":false}' > ~/ccc/data/bastion/experience/w07-scale.json && cat ~/ccc/data/bastion/experience/w07-scale.json",
                 "bastion",
                 "멀티세션 실습 결과 기록.",
                 "cluster_detected"),
            step(11, "3세션 타임라인 요약 생성.",
                 "sudo tail -100 /var/log/apache2/access.log | awk '{print $4, $1, $7}' | tail -30 > ~/ccc/artifacts/w07/timeline.txt && wc -l ~/ccc/artifacts/w07/timeline.txt",
                 "web",
                 "IP·경로·시간을 하나로 묶은 원본 타임라인.",
                 ""),
        ],
    },
    8: {
        "title": "중간평가 — Blue IR CTF",
        "description": "주어진 번들의 아티팩트로부터 타임라인·에이전트 점수·ATT&CK 매핑·방어 3층 판정·차단 권고·Bastion 스킬을 도출한다.",
        "objectives": [
            "불완전한 아티팩트에서 공격 시나리오를 재구성한다",
            "SMART 기준의 스킬 명세를 작성한다",
            "채점 루브릭 점수 산출과 자기 평가를 수행한다",
        ],
        "steps": [
            step(1, "평가 번들 디렉토리 구조 확인(강사 배포).",
                 "mkdir -p /opt/ctf/w08/$(whoami)/{server-logs,pcap,artifacts} && ls /opt/ctf/w08/$(whoami) || echo 'bundle_path_ready'",
                 "bastion",
                 "번들이 미배포면 디렉토리만. 실제 수업 시 강사가 파일 배치.",
                 "bundle_path_ready"),
            step(2, "번들의 access.log(예시) 분포 확인.",
                 "echo 'sample' > /tmp/sample_access.log && awk '{c[\"200\"]++} END {for(k in c) print k, c[k]}' /tmp/sample_access.log",
                 "bastion",
                 "실제 번들에선 /opt/ctf/w08/$(whoami)/server-logs/access.log 사용.",
                 "200"),
            step(3, "pcap 파일 IAT 평균 계산 함수 준비.",
                 "cat > ~/ccc/scripts/pcap_iat.sh <<'S'\n#!/bin/bash\nf=${1:-/tmp/sample.pcap}\n[ -f $f ] || { echo file_missing; exit 1; }\ntshark -r $f -Y 'http.request' -T fields -e frame.time_epoch 2>/dev/null | awk 'NR>1{print $1-p} {p=$1}' | awk '{sum+=$1;n++} END{if(n) print \"iat_avg\", sum/n}'\nS\nchmod +x ~/ccc/scripts/pcap_iat.sh && echo script_ready",
                 "bastion",
                 "pcap IAT 분석 도구 준비. CTF 분석에 활용.",
                 "script_ready"),
            step(4, "answer.md 템플릿 작성.",
                 "mkdir -p ~/ctf-w08 && cat > ~/ctf-w08/answers.md <<'MD'\n# W08 Report\n## 1. Timeline\n## 2. Agent Score (>=5 metrics)\n## 3. ATT&CK Mapping (>=5)\n## 4. Defense Layer Verdict (가장 약한 층 + 근거)\n## 5. 3 Block Recommendations\n## 6. Skill Spec (YAML)\nMD\ncat ~/ctf-w08/answers.md",
                 "bastion",
                 "답안 틀. 6개 필수 질문에 답변.",
                 "Timeline"),
            step(5, "Skill 명세 YAML 스켈레톤.",
                 "cat > ~/ctf-w08/skill.yaml <<'Y'\nskill_id: detect_agent_ctf_<your_id>\nversion: 0.1\npurpose: <구체 시나리오>\ntriggers_on: <wazuh_rule_id or log_pattern>\ninputs:\n  - source: <wazuh|apache|secu>\n    filter: <...>\nlogic:\n  - step: <...>\nthresholds:\n  - <name>: <value + 근거>\nexceptions: []\noutputs:\n  alert_level: <1..15>\n  actions: []\nfailure_mode:\n  false_positive_mitigation: <...>\ntest_cases:\n  - name: <...>\n    given: <...>\n    expected: <...>\nY\ncat ~/ctf-w08/skill.yaml",
                 "bastion",
                 "완성도 있는 스킬 명세. w11에서 실제 Bastion에 등록.",
                 "skill_id"),
            step(6, "ATT&CK 매핑 양식.",
                 "cat > ~/ctf-w08/attck.md <<'MD'\n| Tactic | Technique | 증거 파일:라인 |\n|---|---|---|\n| TA0043 | T1595.002 | access.log:<line> |\n| TA0001 | T1190 | access.log:<line> |\n| TA0006 | T1110 | auth.log:<line> |\n| TA0007 | T1046 | secu_tcpdump:<packet#> |\n| TA0009 | T1005 | wazuh:<alert_id> |\nMD\ncat ~/ctf-w08/attck.md",
                 "bastion",
                 "최소 5건 매핑. 증거 참조 필수.",
                 "TA0043"),
            step(7, "방어 3층 평가 양식.",
                 "cat > ~/ctf-w08/defense-layers.md <<'MD'\n## A층 (WAF·레이트리밋)\n- 403 비율: <계산>\n- 평가: <약/중/강>\n## B층 (SIEM·IDS)\n- rule.level>=10 경보 수: <계산>\n- 평가: <약/중/강>\n## C층 (기만)\n- 허니 이벤트 발생: <예/아니오>\n- 평가: <약/중/강>\n**가장 약한 층**: <A/B/C>, 근거: <숫자>\nMD\ncat ~/ctf-w08/defense-layers.md",
                 "bastion",
                 "숫자 근거가 없으면 감점. 3층 모두 측정치 필수.",
                 "가장 약한"),
            step(8, "차단 권고 3건 템플릿.",
                 "cat > ~/ctf-w08/blocks.md <<'MD'\n1. 긴급 nft 룰: <구체 명령>\n2. WAF 임시 패치: <룰 추가 예>\n3. 세션 격리: <기준·방법>\nMD\ncat ~/ctf-w08/blocks.md",
                 "bastion",
                 "구체성 부족 시 감점. SMART 기준 유지.",
                 "nft"),
            step(9, "시각화 — 간단 타임라인 그림(Mermaid).",
                 "cat > ~/ctf-w08/timeline.md <<'MD'\n```mermaid\ntimeline\n  title 공격 타임라인\n  section 정찰\n    T+00:01 : recon\n  section 악용\n    T+00:10 : exploit\n```\nMD\ncat ~/ctf-w08/timeline.md",
                 "bastion",
                 "시각화 가산점(+5). Mermaid·plantuml·plotly 등 자유.",
                 "mermaid"),
            step(10, "채점 루브릭 자기 점검.",
                 "cat > ~/ctf-w08/self-grade.md <<'MD'\n| 항목 | 내 점수 | 근거 |\n|---|---|---|\n| 타임라인(20) | | |\n| Agent Score(15) | | |\n| ATT&CK(15) | | |\n| 3층 판정(10) | | |\n| 차단 권고(10) | | |\n| 스킬 명세(15) | | |\n| 보고 품질(15) | | |\n| **합계(100)** | | |\nMD\ncat ~/ctf-w08/self-grade.md",
                 "bastion",
                 "자기 평가가 곧 다음 주차 개선 포인트.",
                 "합계"),
            step(11, "제출 패키지 생성.",
                 "cd ~/ctf-w08 && tar czf ~/ccc/artifacts/w08-submission.tgz * && ls -la ~/ccc/artifacts/w08-submission.tgz",
                 "bastion",
                 "제출 tar. 강사에게 전달.",
                 "w08-submission.tgz"),
            step(12, "experience 저장.",
                 "echo '{\"id\":\"w08-ctf\",\"submitted\":true,\"self_grade\":\"TBD\"}' > ~/ccc/data/bastion/experience/w08-ctf.json && cat ~/ccc/data/bastion/experience/w08-ctf.json",
                 "bastion",
                 "중간평가 완료 기록. w11 Purple 입력.",
                 "submitted"),
        ],
    },
    9: {
        "title": "탐지 룰 엔지니어링 — SIGMA → Wazuh",
        "description": "w8에서 설계한 스킬을 SIGMA 룰로 변환해 Wazuh에 적용하고 회귀 테스트까지 실행한다.",
        "objectives": [
            "SIGMA 룰 1건을 작성해 Wazuh XML로 수동 변환한다",
            "wazuh-logtest로 룰 동작을 Phase 3 수준까지 검증한다",
            "회귀 데이터셋에 대한 정밀도·재현율을 측정한다",
        ],
        "steps": [
            step(1, "siem VM의 현재 local_rules.xml 백업.",
                 "sudo cp /var/ossec/etc/rules/local_rules.xml /tmp/local_rules.xml.bak && ls -la /tmp/local_rules.xml.bak",
                 "siem",
                 "수정 전 원본 보존. 롤백용.",
                 "local_rules.xml.bak"),
            step(2, "SIGMA 룰 초안 작성.",
                 "mkdir -p ~/sigma && cat > ~/sigma/agent_burst.yml <<'Y'\ntitle: Agent-like request burst on JuiceShop\nstatus: experimental\nlogsource:\n  product: apache\n  service: access\ndetection:\n  selection:\n    cs-uri-stem|contains:\n      - \"/rest/\"\n  timeframe: 120s\n  condition: selection | count() by c-ip > 60\nfalsepositives:\n  - 내부 모니터링 bots\nlevel: medium\nY\ncat ~/sigma/agent_burst.yml",
                 "siem",
                 "SIGMA 구조. timeframe·count·falsepositives 필수.",
                 "Agent-like"),
            step(3, "Wazuh 룰로 *수동* 변환해 local_rules.xml에 추가.",
                 "sudo bash -c \"cat >> /var/ossec/etc/rules/local_rules.xml <<'X'\n\n<group name=\\\"agent_ir\\\">\n  <rule id=\\\"100110\\\" level=\\\"5\\\">\n    <if_sid>31108</if_sid>\n    <description>Apache access /rest/ endpoint</description>\n  </rule>\n  <rule id=\\\"100111\\\" level=\\\"10\\\" frequency=\\\"60\\\" timeframe=\\\"120\\\">\n    <if_matched_sid>100110</if_matched_sid>\n    <same_source_ip/>\n    <description>Agent-like burst (60+/120s on /rest/)</description>\n    <mitre><id>T1595.002</id></mitre>\n  </rule>\n</group>\nX\"\nsudo tail -20 /var/ossec/etc/rules/local_rules.xml",
                 "siem",
                 "SIGMA → Wazuh 수동 변환. `if_matched_sid`·`frequency`·`timeframe` 사용.",
                 "agent_ir"),
            step(4, "Wazuh 룰 문법 검증.",
                 "sudo /var/ossec/bin/wazuh-analysisd -t 2>&1 | tail -5",
                 "siem",
                 "문법 오류 있으면 *전체 분석 데몬 기동 실패*. 반드시 검증 후 재시작.",
                 ""),
            step(5, "문법 OK면 Wazuh manager 재시작.",
                 "sudo systemctl restart wazuh-manager && sleep 3 && systemctl is-active wazuh-manager",
                 "siem",
                 "재시작 후 active 확인.",
                 "active"),
            step(6, "wazuh-logtest로 샘플 로그 투입 검증.",
                 "echo '10.20.30.80 - - [19/Apr/2026:10:00:00 +0900] \"GET /rest/user/login HTTP/1.1\" 200 123' | sudo /var/ossec/bin/wazuh-logtest 2>&1 | tail -30 | head -30 || echo 'logtest_sample_run'",
                 "siem",
                 "Phase 1~3 매칭 확인. Phase 3에 100110/100111 중 하나라도 뜨면 성공.",
                 "Phase"),
            step(7, "회귀 데이터셋 pcap 재생 시뮬 (w3에서 생성된 pcap).",
                 "[ -f /tmp/w01-baseline.pcap ] && tcpreplay --help 2>&1 | head -3 || echo 'tcpreplay_maybe_missing'",
                 "secu",
                 "tcpreplay로 pcap 재생. 실제 회귀 테스트에서 활용. 도구 없으면 설치.",
                 ""),
            step(8, "정밀도·재현율 계산 스크립트.",
                 "cat > ~/ccc/scripts/metrics.py <<'PY'\ndef metrics(tp, fp, fn):\n    p = tp/(tp+fp) if (tp+fp) else 0\n    r = tp/(tp+fn) if (tp+fn) else 0\n    return p, r\nprint('precision,recall', metrics(18, 2, 5))\nPY\npython3 ~/ccc/scripts/metrics.py",
                 "bastion",
                 "P = TP/(TP+FP), R = TP/(TP+FN). 목표 P>=0.9, R>=0.7.",
                 "precision"),
            step(9, "탐지 지연 측정 스크립트.",
                 "cat > ~/ccc/scripts/latency.py <<'PY'\ndef latency(attack_ts, alert_ts):\n    return (alert_ts - attack_ts).total_seconds()\nprint('목표 p50 <= 10s')\nPY\npython3 ~/ccc/scripts/latency.py",
                 "bastion",
                 "공격 요청 시각 ↔ 경보 발생 시각. 중앙값 <=10s 목표.",
                 "목표"),
            step(10, "회귀 지표 리포트 템플릿.",
                 "cat > ~/ccc/artifacts/w09/regression.md <<'MD'\n| 지표 | 목표 | 내 결과 |\n|---|---|---|\n| Precision | >=90% | |\n| Recall | >=70% | |\n| Detection Latency p50 | <=10s | |\n| FP/일 | <=2 | |\nMD\ncat ~/ccc/artifacts/w09/regression.md",
                 "bastion",
                 "w11 Purple Round 1에서 이 지표를 기준으로 Before/After 비교.",
                 "Precision"),
            step(11, "detection-regression.md 자동 생성 스크립트.",
                 "cat > ~/ccc/scripts/regression_cron.sh <<'S'\n#!/bin/bash\nDATE=$(date -Iseconds)\necho \"# Regression report $DATE\" > ~/ccc/docs/detection-regression.md\necho \"(metrics here)\" >> ~/ccc/docs/detection-regression.md\nS\nchmod +x ~/ccc/scripts/regression_cron.sh && echo cron_ready",
                 "bastion",
                 "매주 금요일 cron으로 실행. 정밀도 하락 시 Slack 알림은 다음 주차에서.",
                 "cron_ready"),
            step(12, "experience 저장.",
                 "echo '{\"id\":\"w09-rule\",\"sigma_yml\":\"agent_burst.yml\",\"wazuh_rule_id\":100111}' > ~/ccc/data/bastion/experience/w09-rule.json && cat ~/ccc/data/bastion/experience/w09-rule.json",
                 "bastion",
                 "탐지 룰 엔지니어링 결과 기록. w11 Purple Round 1의 Blue 초기 상태.",
                 "wazuh_rule_id"),
        ],
    },
    10: {
        "title": "기만·지연 — 허니토큰과 tar-pit",
        "description": "정상 트래픽에 투명하지만 에이전트에겐 *토큰 비용*을 큰 폭으로 증가시키는 기만·지연 방어를 구축한다.",
        "objectives": [
            "허니 자산을 web에 배포하고 Wazuh 고신뢰 룰로 연결한다",
            "Nginx tar-pit 설정을 단계적으로 적용한다",
            "공격자 ROI 계산 수식을 이해하고 예제로 계산한다",
        ],
        "steps": [
            step(1, "가짜 관리자 페이지 배포.",
                 "sudo bash -c 'cat > /var/www/html/fake_admin.html <<H\n<!DOCTYPE html>\n<html><body><h1>Internal Admin Console</h1>\n<!-- API_KEY=HONEY_87af3b1c_DO_NOT_REMOVE -->\n<form>...</form>\n</body></html>\nH' && ls -la /var/www/html/fake_admin.html",
                 "web",
                 "허니 페이지. 주석에 허니 토큰 포함 — 이 값이 어디선가 재관측되면 확정 공격.",
                 "fake_admin.html"),
            step(2, "Apache alias 추가.",
                 "sudo bash -c 'cat > /etc/apache2/conf-available/honey.conf <<C\nAlias /admin-portal /var/www/html/fake_admin.html\n<Location /admin-portal>\n  Require all granted\n</Location>\nC' && sudo a2enconf honey 2>&1 | tail -3 && sudo systemctl reload apache2 2>&1 | tail -3",
                 "web",
                 "허니 경로 활성. 실 관리자는 이 경로 존재 여부 *모름* → 접근만으로도 고신뢰.",
                 "honey"),
            step(3, "curl로 허니 페이지 접근 테스트.",
                 "curl -s http://10.20.30.80/admin-portal | head -5",
                 "web",
                 "정상 응답 확인. access.log에 기록됨.",
                 "Internal"),
            step(4, "Wazuh 룰 — 허니 접근 경보(rule 100300).",
                 "sudo bash -c \"cat >> /var/ossec/etc/rules/local_rules.xml <<'X'\n<group name=\\\"honey\\\">\n  <rule id=\\\"100300\\\" level=\\\"15\\\">\n    <if_sid>31108</if_sid>\n    <match>/admin-portal</match>\n    <description>Honeypot admin-portal accessed — confirmed attacker</description>\n  </rule>\n</group>\nX\" && sudo /var/ossec/bin/wazuh-analysisd -t 2>&1 | tail -3",
                 "siem",
                 "레벨 15 고신뢰. 접근 자체가 공격 확정.",
                 ""),
            step(5, "Wazuh 룰 — 허니 토큰 재관측(rule 100301).",
                 "sudo bash -c \"cat >> /var/ossec/etc/rules/local_rules.xml <<'X'\n  <rule id=\\\"100301\\\" level=\\\"15\\\">\n    <regex>HONEY_87af3b1c_DO_NOT_REMOVE</regex>\n    <description>Honey credential reused — confirmed attacker (post-capture)</description>\n  </rule>\nX\" && sudo systemctl reload wazuh-manager",
                 "siem",
                 "재관측 룰. 허니 토큰이 *다른 곳*에 나타나면 공격자가 이전에 탈취한 증거.",
                 ""),
            step(6, "tar-pit용 의심 IP 리스트 초안.",
                 "sudo bash -c 'cat > /etc/nginx/suspect_ips.conf <<C\n# Bastion이 동적 갱신할 파일\n10.20.30.99 1;\nC'\nls -la /etc/nginx/suspect_ips.conf",
                 "web",
                 "의심 IP를 Bastion이 동적 갱신. 이 파일 변경 시 nginx reload.",
                 "suspect_ips"),
            step(7, "지연 프로파일 문서.",
                 "cat > ~/ccc/artifacts/w10/delay-profile.md <<'MD'\n| 의심 점수 | 지연 | 비고 |\n|---|---|---|\n| <0.4 | 0ms | 정상 |\n| 0.4-0.6 | 200ms | 미세 |\n| 0.6-0.8 | 1-3s | 작은 짐 |\n| >0.8 | 10-30s | tar-pit |\nMD\ncat ~/ccc/artifacts/w10/delay-profile.md",
                 "bastion",
                 "단계별 지연. 운영 환경에서 정상 사용자는 0.4 이하 유지.",
                 "지연"),
            step(8, "공격자 ROI 계산 예시 스크립트.",
                 "cat > ~/ccc/scripts/roi.py <<'PY'\ndef roi(tokens, price=0.000015, success_prob=0.8, value=1000):\n    cost = tokens * price\n    return success_prob*value - cost\nbase = roi(1_000_000)\nwith_tarpit = roi(5_000_000, success_prob=0.4)  # 5배 토큰 + 성공률 반감\nprint('base_roi', round(base,2), 'with_tarpit', round(with_tarpit,2))\nPY\npython3 ~/ccc/scripts/roi.py",
                 "bastion",
                 "공격자 ROI 계산. tar-pit 적용 시 토큰 소모 증가 + 성공률 감소의 *이중 효과*.",
                 "base_roi"),
            step(9, "3단계 배포 계획 문서.",
                 "cat > ~/ccc/artifacts/w10/3-step-deploy.md <<'MD'\n- 1단계(1주): Shadow — 지연 없이 로그만\n- 2단계(1주): Soft — 500ms 지연\n- 3단계(운영): Full — 10~30s tar-pit\n각 단계에서 오탐률·SLA 영향 측정 후 다음 단계로.\nMD\ncat ~/ccc/artifacts/w10/3-step-deploy.md",
                 "bastion",
                 "운영 리스크를 단계적으로 수용. 갑자기 tar-pit 켜면 정상 사용자 피해.",
                 "Shadow"),
            step(10, "허니 자산 *버전 관리* 정책.",
                 "cat > ~/ccc/artifacts/w10/honey-version-policy.md <<'MD'\n- 월 1회 토큰·경로 갱신\n- 과거 버전은 *recall 룰* 유지(이전 유출 탐지)\n- 갱신 주기 이력 기록\nMD\ncat ~/ccc/artifacts/w10/honey-version-policy.md",
                 "bastion",
                 "허니 공개 유출 대비. 정기 갱신 없이는 *이미 아는 허니*를 공격자가 회피.",
                 "월 1회"),
            step(11, "법적 체크리스트.",
                 "cat > ~/ccc/artifacts/w10/legal-ops.md <<'MD'\n- [ ] 허니 토큰이 *진짜 시스템*에서 사용 불가한지 확인\n- [ ] 허니 자산은 운영 문서에 공개하지 않음\n- [ ] SLA 영향 모니터링 (tar-pit 대상)\n- [ ] 실습 종료 후 미끼 청소 절차\n- [ ] 감사 로그 장기 보존\nMD\ncat ~/ccc/artifacts/w10/legal-ops.md",
                 "bastion",
                 "법적·운영 체크. 특히 첫 항목 위반 시 공격 수단 제공 책임.",
                 "청소"),
            step(12, "experience 저장.",
                 "echo '{\"id\":\"w10-deception\",\"honey_path\":\"/admin-portal\",\"rules_added\":[100300,100301],\"tar_pit_stage\":\"shadow\"}' > ~/ccc/data/bastion/experience/w10-deception.json && cat ~/ccc/data/bastion/experience/w10-deception.json",
                 "bastion",
                 "기만·지연 방어 적용 기록.",
                 "honey_path"),
        ],
    },
    11: {
        "title": "Purple Round 1 — Claude Code 코치 + Bastion 업그레이드",
        "description": "w1~w10 결과를 종합해 첫 Purple Round을 실행하고, 코치 출력을 Bastion skill/playbook에 실제 반영한다.",
        "objectives": [
            "Round의 5단계를 시간 내 완결한다",
            "놓친 사건을 A/B/C/D로 분류한다",
            "코치 출력 중 *선택한 것만* Bastion 자산으로 변환한다",
        ],
        "steps": [
            step(1, "Round 초기 Bastion 자산 스냅샷.",
                 "ls ~/ccc/skills/ ~/ccc/playbooks/agent_ir/ ~/ccc/data/bastion/experience/ 2>/dev/null | tee ~/ccc/artifacts/w11-round1/pre-snapshot.txt | head",
                 "bastion",
                 "Round 전 자산 목록. After와 diff를 낸다.",
                 ""),
            step(2, "공방 시나리오 실행 준비 — 3분할 관전 화면 체크.",
                 "echo '화면 1: Claude Code 세션\\n화면 2: Bastion TUI reasoning\\n화면 3: Wazuh Discover' > ~/ccc/artifacts/w11-round1/screens.md && cat ~/ccc/artifacts/w11-round1/screens.md",
                 "bastion",
                 "관전 3분할. 공격-방어 비대칭성을 체감.",
                 "Wazuh"),
            step(3, "공방 실행 중 secu pcap 캡처(5분).",
                 "sudo timeout 60 tcpdump -i any -nn -w /tmp/w11-round1.pcap 'host 10.20.30.80' 2>/dev/null; ls -la /tmp/w11-round1.pcap",
                 "secu",
                 "Round 트래픽 증거. 분석·복기의 원본.",
                 "w11-round1.pcap"),
            step(4, "Round 종료 후 forensic 디렉토리.",
                 "mkdir -p ~/ccc/artifacts/w11-round1/forensic && echo 'T+0: recon start\\nT+5: SQLi attempt\\nT+8: WAF block\\nT+12: JWT analysis\\nT+20: admin token forged' > ~/ccc/artifacts/w11-round1/forensic/timeline.md && cat ~/ccc/artifacts/w11-round1/forensic/timeline.md",
                 "bastion",
                 "타임라인 초해상도. 실제 공방에서 관찰된 것으로 교체.",
                 "SQLi"),
            step(5, "놓친 사건 A/B/C/D 분류.",
                 "cat > ~/ccc/artifacts/w11-round1/forensic/missed_events.csv <<'C'\ntype,event,reason\nA,recon phase,no alert raised\nB,jwt forgery,alert 30s after success\nC,honey access,classified as benign\nD,nft block failed,sudo permission issue\nC\ncat ~/ccc/artifacts/w11-round1/forensic/missed_events.csv",
                 "bastion",
                 "4분류 양식. 각 유형별 대응 방향이 다름.",
                 "recon phase"),
            step(6, "코치 모드 프롬프트 준비.",
                 "cat > ~/ccc/artifacts/w11-round1/forensic/coach-prompt.md <<'MD'\n지금까지의 세션은 공방전이었다. 너는 Red였다.\n이제 Blue를 돕는 코치다. 다음을 한 쪽:\n1. 미탐지 3건 + 각각 탐지 로직\n2. 지연 탐지 + 조기 신호\n3. 오탐 처리 + 분류 오류 원인\n4. Bastion 추가 스킬 1개 명세\n제약: 새 공격 금지. 기존 세션 범위에서만.\nMD\ncat ~/ccc/artifacts/w11-round1/forensic/coach-prompt.md",
                 "bastion",
                 "코치 모드 전환 프롬프트. Red를 복기자로 역할 전환.",
                 "코치"),
            step(7, "Bastion에 새 스킬 추가 (detect_agent_fp_burst).",
                 "mkdir -p ~/ccc/packages/bastion/skills && cat > ~/ccc/packages/bastion/skills/detect_agent_fp_burst.py <<'PY'\ndef detect(session):\n    return session.get('iat_cov', 1.0) < 0.3 and session.get('path_div', 0) >= 10\nPY\ncat ~/ccc/packages/bastion/skills/detect_agent_fp_burst.py",
                 "bastion",
                 "w2 agent_score 구현체 기반 스킬. Round 1의 대표 업그레이드.",
                 "detect_agent_fp_burst"),
            step(8, "Playbook YAML 등록.",
                 "mkdir -p ~/ccc/playbooks/agent_ir && cat > ~/ccc/playbooks/agent_ir/agent-fp.yaml <<'Y'\nplaybook_id: pb-agent-fp\ntriggers: { wazuh_rule_id: 100111 }\nsteps:\n  - skill: detect_agent_fp_burst\n  - skill: tar_pit_inject\n    args: { duration_s: 10 }\nrollback: [unblock_nft]\nY\ncat ~/ccc/playbooks/agent_ir/agent-fp.yaml",
                 "bastion",
                 "Playbook 1건. trigger + steps + rollback.",
                 "pb-agent-fp"),
            step(9, "Experience 엔트리 — Round 1 결과.",
                 "echo '{\"id\":\"w11-round1\",\"skill\":\"detect_agent_fp_burst\",\"outcome\":\"success\"}' > ~/ccc/data/bastion/experience/w11-round1.json && cat ~/ccc/data/bastion/experience/w11-round1.json",
                 "bastion",
                 "경험 로그. 반복되면 w12에서 자동 승격.",
                 "w11-round1"),
            step(10, "Round 재테스트 트래픽(짧게).",
                 "for i in $(seq 1 15); do curl -s -o /dev/null -X POST http://10.20.30.80/rest/user/login -H 'Content-Type: application/json' -d '{\"email\":\"r'$i'\"}'; done; echo round1_retest_done",
                 "web",
                 "업그레이드 후 같은 공격이 이제 막히는지 빠르게 검증.",
                 "round1_retest_done",
                 category="attack"),
            step(11, "Bastion 자산 diff 작성.",
                 "cat > ~/ccc/artifacts/w11-round1/asset-diff.md <<'MD'\n## Added Skills\n- detect_agent_fp_burst\n## Added Playbooks\n- pb-agent-fp\n## Metrics delta\n- 탐지 지연 중앙값: 25s → 8s\n- 미탐지 단계 수: 4 → 1\nMD\ncat ~/ccc/artifacts/w11-round1/asset-diff.md",
                 "bastion",
                 "자산 변화 정량 기록. w13 보고서의 기본 재료.",
                 "Added"),
            step(12, "Round 1 메트릭.",
                 "cat > ~/ccc/artifacts/w11-round1/metrics.md <<'MD'\n| 지표 | Before | After |\n|---|---|---|\n| 탐지 지연 p50 | 25s | 8s |\n| 미탐지 | 4건 | 1건 |\n| 오탐 | 0 | 0 |\n| Bastion 자산 증가 | 0 | +1 skill / +1 pb |\nMD\ncat ~/ccc/artifacts/w11-round1/metrics.md",
                 "bastion",
                 "Round 성공 판정의 근거. 자산 증가 없으면 *의미 없는 Round*.",
                 "Before"),
        ],
    },
    12: {
        "title": "Purple Round 2 — Experience → Playbook 자동 승격",
        "description": "반복 Experience를 클러스터링해 Playbook 후보로 자동 승격하는 파이프라인을 구현한다.",
        "objectives": [
            "bastion_promote.py를 실제 Experience 데이터에 적용한다",
            "Shadow mode·Canary 트래픽·롤백 3중 안전장치를 설계한다",
            "승격된 Playbook의 24시간 관찰 계획을 만든다",
        ],
        "steps": [
            step(1, "현재 Experience 파일 목록·개수.",
                 "ls ~/ccc/data/bastion/experience/*.json 2>/dev/null | wc -l && ls ~/ccc/data/bastion/experience/ | head",
                 "bastion",
                 "클러스터링 입력 데이터셋 점검.",
                 ""),
            step(2, "클러스터링 스크립트 작성.",
                 "cat > ~/ccc/scripts/bastion_promote.py <<'PY'\nimport json, glob, collections\nbuckets = collections.defaultdict(list)\nfor f in glob.glob('$HOME/ccc/data/bastion/experience/*.json'.replace('$HOME', __import__('os').path.expanduser('~'))):\n    try:\n        data = open(f).read().strip()\n        # single-line or multi-line JSON\n        for line in data.splitlines() if '\\n' in data else [data]:\n            if not line.strip(): continue\n            e = json.loads(line)\n            key = e.get('skill') or e.get('id','-')\n            buckets[key].append(e)\n    except Exception as ex:\n        print('skip', f, ex)\nprint('clusters:')\nfor k,v in buckets.items():\n    print(' ', k, len(v))\nPY\npython3 ~/ccc/scripts/bastion_promote.py",
                 "bastion",
                 "현재 Experience를 skill 키로 그룹화. 반복 나타나는 skill이 승격 후보.",
                 "clusters"),
            step(3, "승격 점수 계산 함수.",
                 "cat > ~/ccc/scripts/promotion_score.py <<'PY'\ndef promotion_score(cluster):\n    succ = sum(1 for e in cluster if e.get('outcome') == 'success')\n    return succ/len(cluster) if cluster else 0\nsample = [{'outcome':'success'}]*8 + [{'outcome':'fail'}]*2\nprint('score', promotion_score(sample))  # 0.8\nPY\npython3 ~/ccc/scripts/promotion_score.py",
                 "bastion",
                 "성공률. 0.8+ && 5건+이 승격 조건.",
                 "0.8"),
            step(4, "부작용 점수 계산.",
                 "cat > ~/ccc/scripts/side_effect.py <<'PY'\ndef side_effect_score(cluster):\n    fp = sum(1 for e in cluster if e.get('fp_flag'))\n    slow = sum(1 for e in cluster if e.get('elapsed_s',0) > 10)\n    canary = sum(1 for e in cluster if e.get('hit_canary'))\n    tot = len(cluster) or 1\n    return (fp*3 + slow + canary*5) / tot\ntest = [{'fp_flag':True},{'elapsed_s':15},{'hit_canary':True}]\nprint('side_effect', side_effect_score(test))  # (3+1+5)/3\nPY\npython3 ~/ccc/scripts/side_effect.py",
                 "bastion",
                 "부작용 누적 임계. <0.3이면 승격 가능.",
                 "side_effect"),
            step(5, "승격 후보 YAML 드래프트.",
                 "mkdir -p ~/ccc/playbooks/agent_ir && cat > ~/ccc/playbooks/agent_ir/_candidate_pb_auto.yaml <<'Y'\nplaybook_id: pb-auto-fp-burst\nsource_experiences: 7\navg_success: 0.86\nstatus: shadow\ntriggers: { wazuh_rule_id: 100111 }\nsteps:\n  - skill: detect_agent_fp_burst\n    args: {window: 180}\n  - skill: tar_pit_inject\n    args: {duration_s: 10}\n  - skill: nft_block\n    args: {ttl: 86400}\nverify:\n  - alert_count_after_5m: \"<=1\"\nrollback: [unblock_nft]\nY\ncat ~/ccc/playbooks/agent_ir/_candidate_pb_auto.yaml",
                 "bastion",
                 "자동 승격 후보. *shadow* 상태로 시작.",
                 "shadow"),
            step(6, "Canary 트래픽 스크립트.",
                 "cat > ~/ccc/scripts/canary.py <<'PY'\nimport requests, time\ndef canary():\n    results = []\n    for scenario in [{'name':'normal_get','url':'http://10.20.30.80/'},\n                     {'name':'api_health','url':'http://10.20.30.80/health'}]:\n        try:\n            r = requests.get(scenario['url'], timeout=5)\n            results.append((scenario['name'], r.status_code))\n        except Exception as e:\n            results.append((scenario['name'], 'ERROR'))\n    return results\nprint(canary())\nPY\npython3 ~/ccc/scripts/canary.py 2>&1 | head -5",
                 "bastion",
                 "정상 트래픽 시뮬. 자동 차단되면 Playbook 문제.",
                 ""),
            step(7, "롤백 조건 문서.",
                 "cat > ~/ccc/artifacts/w12-round2/rollback-trigger.md <<'MD'\n- FP 비율 > 2% → 즉시 롤백\n- Canary 실패 1회 이상 → 즉시 롤백\n- 성능 영향 > 500ms → 즉시 롤백\n- 모든 경우 review queue 복귀\nMD\nmkdir -p ~/ccc/artifacts/w12-round2 && cat ~/ccc/artifacts/w12-round2/rollback-trigger.md",
                 "bastion",
                 "롤백 자동화 조건. 본 중 하나라도 위배되면 관리자 승인 없이 되돌림.",
                 "롤백"),
            step(8, "TUI 리뷰 큐 sqlite 스키마.",
                 "cat > ~/ccc/scripts/review_queue.sql <<'S'\nCREATE TABLE IF NOT EXISTS review_queue (\n  id INTEGER PRIMARY KEY,\n  playbook_id TEXT,\n  status TEXT, -- pending|approved|rejected\n  created_at TEXT,\n  reviewer TEXT,\n  reviewed_at TEXT,\n  notes TEXT\n);\nS\nmkdir -p ~/ccc/data/bastion && sqlite3 ~/ccc/data/bastion/review.db < ~/ccc/scripts/review_queue.sql 2>&1 | head -3 || echo 'sqlite3_maybe_missing'",
                 "bastion",
                 "리뷰 큐 저장소. 승격 후보가 여기 쌓이고 학생이 *수동* 승인.",
                 ""),
            step(9, "Round 2 실행 트래픽(w11과 동일 시나리오).",
                 "for i in $(seq 1 20); do curl -s -o /dev/null http://10.20.30.80/rest/user/login -X POST -d '{\"email\":\"r2-'$i'\"}' -H 'Content-Type: application/json'; done; echo round2_done",
                 "web",
                 "Round 2 공격 트래픽. Bastion 자산 증가로 인해 탐지·대응이 더 빨라야 정상.",
                 "round2_done",
                 category="attack"),
            step(10, "Round 2 메트릭 비교 기록.",
                 "cat > ~/ccc/artifacts/w12-round2/metrics.md <<'MD'\n| 지표 | Round 1 | Round 2 |\n|---|---|---|\n| 탐지 지연 p50 | 8s | 6s |\n| 미탐지 단계 | 1 | 0 |\n| 자동 대응 발동 | 2 | 4 |\n| 분석가 개입 | 3 | 1 |\nMD\ncat ~/ccc/artifacts/w12-round2/metrics.md",
                 "bastion",
                 "Before/After 비교. 자동 대응 증가가 핵심 지표.",
                 "Round"),
            step(11, "nogo-auto list — 자동 승격 금지 Playbook 목록.",
                 "cat > ~/ccc/data/bastion/nogo-auto.yaml <<'Y'\n# 이 목록의 Playbook은 자동 활성화 금지 (사람 승인 필수)\n- 외부 IP 장기 차단\n- 인증 서비스 변경\n- 정책 변경\n- 데이터 격리\n- 서비스 재시작\nY\ncat ~/ccc/data/bastion/nogo-auto.yaml",
                 "bastion",
                 "영구 사람 승인 Playbook 목록. 잘못 자동화되면 재앙.",
                 "외부 IP"),
            step(12, "experience 저장.",
                 "echo '{\"id\":\"w12-round2\",\"auto_promoted\":1,\"shadow_mode\":true,\"canary_ok\":true}' > ~/ccc/data/bastion/experience/w12-round2.json && cat ~/ccc/data/bastion/experience/w12-round2.json",
                 "bastion",
                 "Round 2 결과. w13 보고서의 핵심 근거.",
                 "auto_promoted"),
        ],
    },
    13: {
        "title": "사고 보고서 — 에이전트 IR 특수 섹션",
        "description": "전통 NIST SP 800-61 IR 보고서에 모델·프롬프트·Transient Tool·의사결정 로그 섹션을 추가한 에이전트 IR 보고서 템플릿을 완성한다.",
        "objectives": [
            "보고서의 9개 섹션을 본인 Round 결과로 채운다",
            "의사결정 로그 마스킹을 실제 샘플에 적용한다",
            "해시 봉인·오프사이트 복제 절차를 실행한다",
        ],
        "steps": [
            step(1, "보고서 골격 생성.",
                 "mkdir -p ~/ccc/reports/w13 && cat > ~/ccc/reports/w13/report.md <<'MD'\n# Agent IR Incident Report (Draft)\n## 1. Executive Summary\n## 2. 사건 개요\n### 2.1 타임라인\n### 2.2 영향 범위\n## 3. 공격자 프로파일\n### 3.1 Model Info\n### 3.2 Prompt Chain\n### 3.3 Transient Tools\n## 4. 탐지·분석\n## 5. 대응 (Bastion 의사결정 로그)\n## 6. 복구·검증\n## 7. 학습 (Purple·Bastion 자산 diff)\n## 8. 법적·규제\n## 부록 A. transcript (비식별)\n## 부록 B. skill/playbook diff\n## 부록 C. IOC/IOA\nMD\nwc -l ~/ccc/reports/w13/report.md",
                 "bastion",
                 "표준 9섹션 골격. 빈 구조도 좋은 보고서의 시작.",
                 "1"),
            step(2, "섹션 1 Executive Summary(샘플).",
                 "cat >> ~/ccc/reports/w13/report.md <<'MD'\n\n<!-- Executive Summary -->\n6개월 잠복 APT 관찰 (D+2). Bastion 자동 차단으로 외부 유출 없음.\n주요 자산 회전 완료. 리빌드 계획 승인 요청.\nMD\ntail -10 ~/ccc/reports/w13/report.md",
                 "bastion",
                 "의사결정자에게 3분 내 전달되는 요지.",
                 "Executive"),
            step(3, "섹션 3.1 — 모델 정보 채우기.",
                 "cat >> ~/ccc/reports/w13/report.md <<'MD'\n\n<!-- 3.1 Model Info -->\n| 항목 | 값 |\n|---|---|\n| 모델명 | (식별된) |\n| 버전 | (식별된) |\n| API 제공자 | (제공자 또는 self-hosted) |\n| Tool-use 활성 | 예 |\nMD\ntail -10 ~/ccc/reports/w13/report.md",
                 "bastion",
                 "전통 보고서에 없는 *에이전트 IR 전용* 섹션.",
                 "Model"),
            step(4, "섹션 3.3 — Transient Tool 스냅샷.",
                 "cat >> ~/ccc/reports/w13/report.md <<'MD'\n\n<!-- 3.3 Transient Tools -->\n| 파일 | 수명 | 해시 |\n|---|---|---|\n| /tmp/exp_v1.py | 3min | sha256:... |\n| /tmp/exp_v3.py | 12min | sha256:... |\n| /tmp/dumper.py | 5min | sha256:... |\nMD\ntail -10 ~/ccc/reports/w13/report.md",
                 "bastion",
                 "공격 세션 내 생성된 도구들. 파일은 사라져도 *기록*은 남아야.",
                 "Transient"),
            step(5, "의사결정 로그 마스킹 샘플.",
                 "cat > ~/ccc/reports/w13/decision-sample.json <<'J'\n{\n  \"ts\": \"2026-04-19T01:02:03+0900\",\n  \"decision\": \"block_ip\",\n  \"src\": \"10.xxx.xxx.50\",\n  \"reason\": \"agent_score=0.83, JWT anomaly\",\n  \"user_email\": \"[REDACTED_EMAIL]\",\n  \"model_chain\": \"(요약) 허니 경로 접근 감지 → 차단 권고\"\n}\nJ\ncat ~/ccc/reports/w13/decision-sample.json",
                 "bastion",
                 "IP·이메일 마스킹. 모델 추론 체인은 요약.",
                 "REDACTED"),
            step(6, "해시 봉인 샘플.",
                 "mkdir -p ~/ccc/reports/w13/evidence && echo 'sample pcap' > ~/ccc/reports/w13/evidence/attack.pcap && sha256sum ~/ccc/reports/w13/evidence/attack.pcap > ~/ccc/reports/w13/evidence/SHA256SUMS && cat ~/ccc/reports/w13/evidence/SHA256SUMS",
                 "bastion",
                 "증적 무결성. 사건 직후 봉인해야 향후 위변조 검증 가능.",
                 "attack.pcap"),
            step(7, "증적 체크리스트.",
                 "cat > ~/ccc/reports/w13/evidence-checklist.md <<'MD'\n- [x] pcap sha256 봉인\n- [x] Wazuh alerts json 추출\n- [ ] 오프사이트 복제\n- [x] 마스킹 적용\n- [ ] 법무팀 접근 감사 로그\nMD\ncat ~/ccc/reports/w13/evidence-checklist.md",
                 "bastion",
                 "증적 절차. 체크되지 않은 항목은 *수집 실패*가 아닌 *추가 작업*으로.",
                 "봉인"),
            step(8, "섹션 7 — 자산 diff 삽입.",
                 "cp ~/ccc/artifacts/w11-round1/asset-diff.md ~/ccc/reports/w13/ 2>/dev/null; cat ~/ccc/reports/w13/asset-diff.md 2>/dev/null | head -15 || echo 'asset-diff_placeholder'",
                 "bastion",
                 "w11 자산 diff를 보고서에 첨부.",
                 ""),
            step(9, "법적·규제 섹션(한국 기준).",
                 "cat > ~/ccc/reports/w13/legal.md <<'MD'\n- GDPR 제33조 72시간 통지 검토\n- 개인정보보호법 제34조 유출 통지 검토\n- ISMS-P 증적 보관 3년\n- 정보통신망법 제48조의2 접근 기록 6개월\nMD\ncat ~/ccc/reports/w13/legal.md",
                 "bastion",
                 "법적 고려사항 목록. 해당 여부는 법무팀과 협의.",
                 "GDPR"),
            step(10, "보고서 품질 자가 평가.",
                 "cat > ~/ccc/reports/w13/self-rubric.md <<'MD'\n| 항목 | 5점 | 3점 | 1점 |\n|---|---|---|---|\n| Executive Summary | 3분 이해 | 대부분 | 기술어만 |\n| 타임라인 | 초 해상도 | 분 | 대략 |\n| Attacker Profile | 모델·프롬프트·도구 분리 | 부분 | 통합 |\n| Decision log | 마스킹·요약·주석 | 일부 | 덤프 |\n| Asset diff | 정량·증거 | 정성 | 없음 |\n| Legal | 조항 인용·통지 | 일반론 | 없음 |\n**내 점수**: __/30\nMD\ncat ~/ccc/reports/w13/self-rubric.md",
                 "bastion",
                 "21점 이하면 재작성. 6개 항목 각 5점.",
                 "재작성"),
            step(11, "외부 공유용 *익명화* 사본 생성.",
                 "sed 's/10\\.[0-9]*\\.[0-9]*\\.[0-9]*/10.XXX.XXX.XXX/g; s/admin@example.com/user@example.org/g' ~/ccc/reports/w13/report.md > ~/ccc/reports/w13/report-anonymized.md && wc -l ~/ccc/reports/w13/report-anonymized.md",
                 "bastion",
                 "내부 IP·이메일 일괄 마스킹. 외부 공유 전에는 사람 리뷰 1회 필수.",
                 ""),
            step(12, "experience 저장.",
                 "echo '{\"id\":\"w13-report\",\"sections\":9,\"self_grade\":\"TBD\",\"evidence_sealed\":true}' > ~/ccc/data/bastion/experience/w13-report.json && cat ~/ccc/data/bastion/experience/w13-report.json",
                 "bastion",
                 "보고서 작성 완료 기록.",
                 "sections"),
        ],
    },
    14: {
        "title": "모의 실사고 — 다단계 Agentic APT 대응",
        "description": "5개 에이전트의 킬체인 공격을 Bastion + 학생이 대응하고 보고서 초안을 마무리한다.",
        "objectives": [
            "5단계 킬체인을 관전·대응한다",
            "세션 클러스터링이 실제로 발동하는지 확인한다",
            "2시간 공격 대비 24시간 방어의 템포 차이를 체감한다",
        ],
        "steps": [
            step(1, "Blue 초기 상태 — Bastion 자산 리스트.",
                 "ls ~/ccc/skills/ ~/ccc/playbooks/agent_ir/ 2>/dev/null | wc -l",
                 "bastion",
                 "Round 시작 전 자산 수. After와 diff.",
                 ""),
            step(2, "Wazuh dashboard 응답 확인.",
                 "curl -sk -o /dev/null -w '%{http_code}\\n' https://10.20.30.100/",
                 "siem",
                 "Blue 감각기관이 살아 있는지.",
                 ""),
            step(3, "R1 정찰 트래픽 시뮬.",
                 "for p in / /api /rest /admin /score-board; do curl -s -o /dev/null http://10.20.30.80$p; done; echo R1_recon_done",
                 "web",
                 "5경로 정찰. ReqBurst 신호 유발.",
                 "R1_recon_done",
                 category="recon"),
            step(4, "R2 SQLi 시도 시뮬.",
                 "curl -s -o /dev/null -w 'code=%{http_code}\\n' -X POST http://10.20.30.80:8082/rest/user/login -H 'Content-Type: application/json' -d '{\"email\":\"admin\\\" OR 1=1--\",\"password\":\"x\"}'",
                 "web",
                 "R2 웹 악용. WAF 반응 확인.",
                 "code=",
                 category="attack"),
            step(5, "R5 지속성 시뮬 — authorized_keys 추가.",
                 "mkdir -p ~/.ssh && echo '# r5 persistence $(date +%s)' >> ~/.ssh/authorized_keys && ls -la ~/.ssh/authorized_keys",
                 "web",
                 "지속성 심기. auditd로 추적 가능해야.",
                 "authorized_keys"),
            step(6, "R3 측면이동 시도.",
                 "for dst in 1 100 201; do timeout 2 nc -zv 10.20.30.$dst 22 2>&1 | head -1 || echo 'port22_closed_or_filtered'; done",
                 "web",
                 "R3 내부 스캔. 3호스트 22포트 시도.",
                 "22",
                 category="pivot"),
            step(7, "R4 데이터 접근 시도.",
                 "curl -s -o /dev/null -w '%{http_code}\\n' http://10.20.30.80/api/users",
                 "web",
                 "R4 데이터 유출 시도.",
                 "",
                 category="exfiltration"),
            step(8, "Bastion 자동 대응 발동 수 (Wazuh alerts 최근).",
                 "sudo jq -c 'select(.rule.level>=10)' /var/ossec/logs/alerts/alerts.json 2>/dev/null | tail -10 | wc -l",
                 "siem",
                 "고위험 경보 수. 5킬체인 단계마다 하나씩 이상 발생해야.",
                 ""),
            step(9, "최종 trained metrics 저장.",
                 "mkdir -p ~/ccc/artifacts/w14 && cat > ~/ccc/artifacts/w14/metrics.md <<'MD'\n| 항목 | w11 시작 | w14 종료 | 차이 |\n|---|---|---|---|\n| Skill 수 | 0 | 1 | +1 |\n| Playbook 수 | 0 | 1 | +1 |\n| Experience 수 | 0 | 13 | +13 |\n| 자동 대응 발동 누적 | 0 | (측정) | |\nMD\ncat ~/ccc/artifacts/w14/metrics.md",
                 "bastion",
                 "w11~w14의 자산 변화. 증가가 적으면 Round 효과 의문.",
                 "w11"),
            step(10, "w14 보고서 초안 확장.",
                 "cp ~/ccc/reports/w13/report.md ~/ccc/reports/w14-report.md 2>/dev/null && echo '\\n## w14 Multi-agent APT Response' >> ~/ccc/reports/w14-report.md && tail -5 ~/ccc/reports/w14-report.md",
                 "bastion",
                 "w13 보고서를 *확장*하는 형태로 w14 추가.",
                 "APT"),
            step(11, "과정 회고 초안 1쪽.",
                 "cat > ~/ccc/artifacts/w14/course-retro.md <<'MD'\n# 과정 회고 (초안)\n## 가장 놀라운 관찰\n- \n## 막지 못한 공격\n- \n## Bastion이 배운 것\n- \n## 나에게 남는 질문\n- \nMD\ncat ~/ccc/artifacts/w14/course-retro.md",
                 "bastion",
                 "w15에서 완성. 회고는 과정의 *산출물 중 가장 정직한 것*.",
                 "회고"),
            step(12, "experience 저장.",
                 "echo '{\"id\":\"w14-apt\",\"red_agents\":5,\"kill_chain_stages\":5,\"bastion_blocks\":\"TBD\"}' > ~/ccc/data/bastion/experience/w14-apt.json && cat ~/ccc/data/bastion/experience/w14-apt.json",
                 "bastion",
                 "모의 실사고 기록. 기말 보고서에 활용.",
                 "kill_chain"),
        ],
    },
    15: {
        "title": "기말 — Mythos-readiness + 30/90/365 작전 계획",
        "description": "기말 공방 + 레벨 자가 진단 + 30/90/365일 조직 적용 계획.",
        "objectives": [
            "기말 Round 5단계를 대응한다",
            "Mythos-readiness L0~L5 자가 판정에 증거를 첨부한다",
            "조직 도입 로드맵을 의사결정자 브리핑 1쪽으로 만든다",
        ],
        "steps": [
            step(1, "최종 Bastion 자산 스냅샷.",
                 "ls ~/ccc/skills/*.py ~/ccc/skills/*.yaml ~/ccc/playbooks/agent_ir/*.yaml 2>/dev/null | tee ~/ccc/final/asset-snapshot.txt | wc -l",
                 "bastion",
                 "학기 말 최종 자산 수.",
                 ""),
            step(2, "기말 공방 관전 준비.",
                 "mkdir -p ~/ccc/final && echo '3분할 화면 + Canary 실행 + pcap 캡처' > ~/ccc/final/final-setup.md && cat ~/ccc/final/final-setup.md",
                 "bastion",
                 "기말 환경 체크.",
                 "Canary"),
            step(3, "기말 공방 트래픽 시뮬.",
                 "for i in $(seq 1 30); do curl -s -o /dev/null http://10.20.30.80/rest/user/login -X POST -d '{\"email\":\"final-'$i'\"}' -H 'Content-Type: application/json'; done; echo final_attack_sim_done",
                 "web",
                 "강사 커스텀 공격 시나리오.",
                 "final_attack_sim_done",
                 category="attack"),
            step(4, "Mythos-readiness L1 증거.",
                 "cat > ~/ccc/final/mythos-l1.md <<'MD'\nL1 Observer 증거\n- SIEM에서 에이전트 관련 이벤트 질의 가능: (링크)\n- alerts.json에 에이전트 룰 매칭 이력: (파일)\n- 외부 egress 30일 보존: (정책)\nMD\ncat ~/ccc/final/mythos-l1.md",
                 "bastion",
                 "L1 증거. 실제 파일·정책 링크 필요.",
                 "L1"),
            step(5, "Mythos-readiness L2~L4 증거 양식.",
                 "cat > ~/ccc/final/mythos-all.md <<'MD'\n| Level | 증거 |\n|---|---|\n| L1 Observer | |\n| L2 Reactor | |\n| L3 Defender | |\n| L4 Co-evolver | |\n| L5 Mythos-ready | |\nMD\ncat ~/ccc/final/mythos-all.md",
                 "bastion",
                 "모든 레벨 증거 정리. 실습 수준으로는 L3~L4, 조직 수준으로는 L1~L2 일반적.",
                 "Observer"),
            step(6, "30일 조치 계획.",
                 "cat > ~/ccc/final/plan-30.md <<'MD'\n# 30일 조치\n- 에이전트 호출 가시성 (로깅·프록시)\n- 핵심 시스템 egress default-deny\n- 본 과목의 skill 1~2개 운영 SIEM 이식\nMD\ncat ~/ccc/final/plan-30.md",
                 "bastion",
                 "즉시 실행 가능한 조치. 예산 최소.",
                 "30일"),
            step(7, "90일 조치 계획.",
                 "cat > ~/ccc/final/plan-90.md <<'MD'\n# 90일 조치\n- VulnOps 전담 인력 1명\n- Purple 프로세스 월 1회 시범\n- 허니토큰·tar-pit 일부 적용\nMD\ncat ~/ccc/final/plan-90.md",
                 "bastion",
                 "중기 조치. 예산·인력 중간.",
                 "90일"),
            step(8, "365일 조치 계획.",
                 "cat > ~/ccc/final/plan-365.md <<'MD'\n# 365일 조치\n- Co-evolution 자동 승격 루프 운영\n- OpenCTI 연동 확장\n- Mythos-readiness L3 이상 진입\nMD\ncat ~/ccc/final/plan-365.md",
                 "bastion",
                 "장기 조치. 전사 이해 필요.",
                 "365일"),
            step(9, "의사결정자 브리핑 1쪽.",
                 "cat > ~/ccc/final/exec-brief.md <<'MD'\n# Agent IR 도입 — 30/90/365\n## 한 줄\n우리 조직 L1→L3 이행. 12개월 비용 ~$XXX K. 미조치 시 리스크: Dependency Confusion 1건에 $Y M 손실 가능.\n## 요청\n- 예산: $XXX K\n- 인력: N명 FTE\n- 정책 승인: egress 제한·JIT 특권\nMD\ncat ~/ccc/final/exec-brief.md",
                 "bastion",
                 "의사결정자용. 숫자·요청 3개가 핵심.",
                 "도입"),
            step(10, "과정 회고 보고서.",
                 "cat > ~/ccc/final/course-retrospective.md <<'MD'\n# C19 회고\n## 근본적 통찰 1개\n- Agent 시대에는 Round의 '승·패'가 아니라 Bastion의 '학습'이 성공.\n## 즉시 조치 1개\n- (조직에 돌아가 다음 주 실행)\n## 과정 개선 제안 1개\n- (교수자에게)\nMD\ncat ~/ccc/final/course-retrospective.md",
                 "bastion",
                 "회고는 과정의 *마지막 반영*. 3문항 명확.",
                 "근본적"),
            step(11, "최종 제출 패키지.",
                 "cd ~/ccc/final && tar czf ~/ccc/artifacts/w15-final.tgz * && ls -la ~/ccc/artifacts/w15-final.tgz",
                 "bastion",
                 "기말 제출. 모든 산출물 포함.",
                 "w15-final.tgz"),
            step(12, "experience — 과정 종료.",
                 "echo '{\"id\":\"w15-final\",\"completed\":true,\"mythos_self\":\"L3 체험 / L2 조직\",\"ts\":\"'$(date -Iseconds)'\"}' > ~/ccc/data/bastion/experience/w15-final.json && cat ~/ccc/data/bastion/experience/w15-final.json",
                 "bastion",
                 "최종 경험 기록. 다음 코호트의 *레퍼런스*가 된다.",
                 "completed"),
        ],
    },
}


RISK = {"secu":"medium","web":"low","siem":"low","bastion":"low"}


def build_lab(week, version):
    spec = WEEKS[week]
    course = f"agent-ir-{version}"
    title = spec["title"] + (" (AI 지원)" if version == "ai" else " (Non-AI)")
    descr = spec["description"]
    if version == "ai":
        descr += " AI SubAgent가 자동으로 명령을 실행·검증합니다."
    else:
        descr += " 학생이 각 단계를 수동으로 수행하고 결과를 기록합니다."

    steps_out = []
    for s in spec["steps"]:
        cli = s["_cli"]
        vm = s["_vm"]
        vtype = s["_vtype"]
        expect = s["_expect"]
        instruction = s["instruction"]
        if version == "ai":
            answer = f"🤖 프롬프트: {instruction}\n📎 참고 (CLI): {cli}"
            bastion_prompt = instruction
        else:
            # Non-AI: CLI만. 프롬프트 prefix 절대 금지.
            answer = cli
            bastion_prompt = ""
        out = {
            "order": s["order"],
            "instruction": instruction,
            "hint": s["hint"],
            "category": s["category"],
            "points": s["points"],
            "answer": answer,
            "answer_detail": s["answer_detail"],
            "verify": {"type": vtype, "expect": expect, "field": "stdout"},
            "target_vm": vm,
            "script": cli,
            "risk_level": RISK.get(vm, "low"),
            "bastion_prompt": bastion_prompt,
        }
        steps_out.append(out)

    return {
        "lab_id": f"{course}-week{week:02d}",
        "title": title,
        "version": version,
        "course": course,
        "week": week,
        "description": descr,
        "difficulty": "hard",
        "duration_minutes": 150,
        "objectives": spec["objectives"],
        "pass_threshold": 0.6,
        "steps": steps_out,
    }


def main():
    labs_dir = os.path.join(ROOT, "contents", "labs")
    for w in range(1, 16):
        for version in ("ai", "nonai"):
            lab = build_lab(w, version)
            outdir = os.path.join(labs_dir, f"agent-ir-{version}")
            os.makedirs(outdir, exist_ok=True)
            path = os.path.join(outdir, f"week{w:02d}.yaml")
            with open(path, "w", encoding="utf-8") as f:
                yaml.dump(lab, f, allow_unicode=True, sort_keys=False, width=1000)
            print(f"wrote {path} ({len(lab['steps'])} steps)")


if __name__ == "__main__":
    main()
