#!/usr/bin/env python3
"""secops(보안 솔루션 운영) 과정의 실습 YAML을 강의 주제에 맞게 재생성.

문제: 기존 secops-ai/secops-nonai 실습이 compliance 과정과 뒤섞인 내용(보안 정책, 접근
통제, 계정 관리 등)으로 되어 있어 강의(nftables, Suricata, WAF, Wazuh, OpenCTI)와 불일치.

본 스크립트는 주차별 스펙(SPECS)에 맞춰 non-ai / ai YAML 을 새로 쓴다.
- non-ai: shell 명령어 중심. verify는 output_contains.
- ai: 동일 step에 bastion_prompt 필드 추가 + target_vm/risk_level 포함.

사용:
  python3 scripts/regen_secops_labs.py           # 전체 재생성
  python3 scripts/regen_secops_labs.py --week 2  # 특정 주차만
"""
from __future__ import annotations
import argparse, os, yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LABS = os.path.join(ROOT, "contents", "labs")

# 각 주차 스펙:
# - title: 실습 타이틀
# - description: 간단 설명
# - objectives: 학습 목표 리스트
# - difficulty, duration
# - steps: [(category, instruction, hint, answer_cmd, verify_expect, target_vm, risk, bastion_prompt)]
SPECS = {
    1: {
        "title": "보안 솔루션 인프라 점검",
        "description": "실습 환경의 보안 솔루션(nftables, Suricata, ModSecurity, Wazuh, OpenCTI)이 각 VM에 어떻게 배치·동작하는지 확인한다.",
        "objectives": [
            "실습 인프라 VM의 역할과 배포된 보안 솔루션을 파악한다",
            "각 보안 솔루션이 실제로 동작하는지 명령어로 확인한다",
            "솔루션별 주요 로그와 설정 파일 위치를 확인한다",
        ],
        "difficulty": "easy",
        "duration": 120,
        "steps": [
            ("survey", "secu VM(10.20.30.1)의 nftables 테이블 목록을 확인하시오.", "nft list tables",
             "nft list tables", "table", "secu", "low",
             "secu VM의 nftables 테이블 목록을 확인해줘"),
            ("survey", "secu VM에서 Suricata 서비스 상태를 확인하시오.", "systemctl is-active suricata",
             "systemctl status suricata --no-pager | head -15", "suricata", "secu", "low",
             "secu VM의 Suricata 서비스 상태를 확인해줘"),
            ("survey", "web VM(10.20.30.80)에서 Apache + ModSecurity 모듈 로드 상태를 확인하시오.", "apachectl -M | grep security",
             "apachectl -M 2>/dev/null | grep -i security", "security", "web", "low",
             "web VM의 Apache ModSecurity 모듈이 로드되어 있는지 확인해줘"),
            ("survey", "siem VM(10.20.30.100)에서 Wazuh Manager 서비스 상태를 확인하시오.", "systemctl is-active wazuh-manager",
             "systemctl is-active wazuh-manager || echo inactive", "active", "siem", "low",
             "siem VM의 Wazuh Manager 서비스가 동작 중인지 확인해줘"),
            ("survey", "siem VM에서 Wazuh Indexer(OpenSearch) 포트(9200) 리스닝 상태를 확인하시오.", "ss -tlnp | grep 9200",
             "ss -tlnp 2>/dev/null | grep -E ':9200|wazuh'", "9200", "siem", "low",
             "siem VM에서 Wazuh Indexer가 9200 포트로 리스닝하는지 확인해줘"),
            ("survey", "siem VM에서 OpenCTI 서비스(또는 docker 컨테이너) 상태를 확인하시오.", "docker ps | grep opencti",
             "docker ps --format '{{.Names}}\\t{{.Status}}' 2>/dev/null | grep -i opencti || systemctl is-active opencti", "opencti", "siem", "low",
             "siem VM에서 OpenCTI가 동작 중인지 확인해줘"),
            ("survey", "attacker VM(10.20.30.201)에서 secu VM으로 ping이 가능한지 확인하시오.", "ping -c 2 10.20.30.1",
             "ping -c 2 10.20.30.1", "bytes", "attacker", "low",
             "attacker VM에서 secu VM(10.20.30.1)으로 ping 테스트를 수행해줘"),
            ("analysis", "secu VM에서 Suricata 기본 룰셋 수(/etc/suricata/rules 내 .rules 파일 합계)를 확인하시오.", "ls /etc/suricata/rules/*.rules 2>/dev/null | wc -l",
             "ls /etc/suricata/rules/*.rules 2>/dev/null | wc -l", "", "secu", "low",
             "secu VM의 Suricata 룰 파일 개수를 확인해줘"),
            ("analysis", "web VM에서 ModSecurity CRS 룰 디렉터리 목록을 확인하시오.", "ls /etc/modsecurity/crs/rules/ 2>/dev/null | head",
             "ls /etc/modsecurity/crs/rules/ 2>/dev/null | head -5 || ls /usr/share/modsecurity-crs/rules/ 2>/dev/null | head -5", "rules", "web", "low",
             "web VM의 ModSecurity CRS 룰 디렉터리 내용을 확인해줘"),
            ("analysis", "siem VM에서 Wazuh Manager의 최근 alert 파일 존재 여부를 확인하시오.", "ls /var/ossec/logs/alerts/ 2>/dev/null | head",
             "ls /var/ossec/logs/alerts/ 2>/dev/null | head -3", "alert", "siem", "low",
             "siem VM의 Wazuh alerts 로그 디렉터리를 확인해줘"),
        ],
    },
    2: {
        "title": "nftables 방화벽 기초",
        "description": "nftables로 간단한 방화벽 테이블/체인/룰을 작성하고 input/output/forward 체인의 동작을 확인한다.",
        "objectives": [
            "nftables의 테이블/체인/룰 개념을 이해한다",
            "input 체인에서 특정 포트를 허용/차단할 수 있다",
            "룰 추가·삭제·확인 명령어를 숙지한다",
        ],
        "difficulty": "easy",
        "duration": 120,
        "steps": [
            ("configure", "secu VM에 inet 계열 테이블 'lab'을 생성하시오.", "nft add table inet lab",
             "sudo nft add table inet lab", "", "secu", "low",
             "secu VM에 'inet lab' nftables 테이블을 만들어줘"),
            ("configure", "lab 테이블에 input 체인(hook input, priority 0, policy accept)을 생성하시오.", "nft add chain …",
             "sudo nft add chain inet lab input '{ type filter hook input priority 0 \\; policy accept \\; }'", "", "secu", "low",
             "secu VM의 lab 테이블에 input hook 체인을 만들어줘"),
            ("configure", "lab 테이블 input 체인에 tcp 포트 23(telnet) 차단 룰을 추가하시오.", "nft add rule inet lab input tcp dport 23 drop",
             "sudo nft add rule inet lab input tcp dport 23 drop", "drop", "secu", "low",
             "secu VM의 lab.input에 telnet(tcp/23) 차단 룰을 추가해줘"),
            ("verify", "nft list table inet lab 으로 작성한 룰을 확인하시오.", "nft list table inet lab",
             "sudo nft list table inet lab", "dport 23", "secu", "low",
             "secu VM의 lab 테이블 룰셋을 출력해줘"),
            ("configure", "established, related 연결을 허용하는 상태 기반 룰을 input 체인 맨 앞에 삽입하시오.", "nft insert rule …",
             "sudo nft insert rule inet lab input ct state established,related accept", "established", "secu", "low",
             "secu VM에서 lab.input 체인 맨 앞에 ct state established,related accept 룰을 삽입해줘"),
            ("configure", "loopback(lo)에서 들어오는 트래픽을 허용하는 룰을 추가하시오.", "iifname lo accept",
             "sudo nft add rule inet lab input iifname lo accept", "lo", "secu", "low",
             "secu VM의 lab.input 체인에 loopback 인터페이스 허용 룰을 추가해줘"),
            ("configure", "tcp 22(ssh) 포트를 허용하는 룰을 추가하시오.", "tcp dport 22 accept",
             "sudo nft add rule inet lab input tcp dport 22 accept", "dport 22", "secu", "low",
             "secu VM의 lab.input 체인에 ssh(tcp/22) 허용 룰을 추가해줘"),
            ("verify", "전체 룰셋(모든 테이블)을 nft list ruleset 명령으로 확인하시오.", "nft list ruleset",
             "sudo nft list ruleset", "table inet lab", "secu", "low",
             "secu VM의 nftables 전체 룰셋을 확인해줘"),
            ("cleanup", "실습 종료 후 lab 테이블을 삭제하시오.", "nft delete table inet lab",
             "sudo nft delete table inet lab", "", "secu", "low",
             "secu VM의 inet lab nftables 테이블을 삭제해줘"),
            ("verify", "lab 테이블이 삭제되었는지 nft list tables 로 확인하시오.", "nft list tables",
             "sudo nft list tables | grep -v ' lab$' | tail", "table", "secu", "low",
             "secu VM에서 nftables 테이블 목록을 확인해줘"),
        ],
    },
    3: {
        "title": "nftables 실전 — NAT, 화이트리스트, 레이트리밋",
        "description": "masquerade NAT, 화이트리스트/블랙리스트, 연결 레이트리밋 등 실전 nftables 기법을 적용한다.",
        "objectives": [
            "masquerade NAT 룰을 작성할 수 있다",
            "set(ip saddr) 기반 화이트리스트·블랙리스트를 구성할 수 있다",
            "ct state new limit으로 레이트리밋을 적용할 수 있다",
        ],
        "difficulty": "medium",
        "duration": 120,
        "steps": [
            ("configure", "secu VM에 inet 'whitelist' 테이블을 만들고 input 체인을 생성하시오.", "nft add table; nft add chain",
             "sudo nft add table inet whitelist && sudo nft add chain inet whitelist input '{ type filter hook input priority 0 \\; policy drop \\; }'", "whitelist", "secu", "medium",
             "secu VM에 whitelist 테이블과 policy drop의 input 체인을 만들어줘"),
            ("configure", "whitelist 테이블에 set 'allowed_ips'(type ipv4_addr)를 생성하시오.", "nft add set …",
             "sudo nft add set inet whitelist allowed_ips '{ type ipv4_addr \\; }'", "allowed_ips", "secu", "low",
             "secu VM whitelist 테이블에 ipv4 set 'allowed_ips'를 만들어줘"),
            ("configure", "allowed_ips set에 10.20.30.201(attacker)을 추가하시오.", "nft add element …",
             "sudo nft add element inet whitelist allowed_ips '{ 10.20.30.201 }'", "10.20.30.201", "secu", "low",
             "secu VM whitelist.allowed_ips set에 10.20.30.201을 추가해줘"),
            ("configure", "input 체인에서 allowed_ips 에 속하는 소스만 accept 하도록 룰을 추가하시오.", "ip saddr @allowed_ips accept",
             "sudo nft add rule inet whitelist input ip saddr @allowed_ips accept", "allowed_ips", "secu", "medium",
             "secu VM whitelist.input 체인에 allowed_ips set 기반 accept 룰을 추가해줘"),
            ("configure", "SSH tcp/22에 대해 ct state new limit rate 3/minute 를 적용해 브루트포스를 완화하시오.", "tcp dport 22 ct state new limit rate 3/minute",
             "sudo nft add rule inet whitelist input tcp dport 22 ct state new limit rate 3/minute accept", "limit rate", "secu", "medium",
             "secu VM whitelist.input에 SSH 브루트포스 방지용 레이트리밋 룰을 추가해줘"),
            ("configure", "NAT 테이블과 postrouting 체인을 생성하고 masquerade 룰을 추가하시오.", "type nat hook postrouting",
             "sudo nft add table inet nat && sudo nft add chain inet nat postrouting '{ type nat hook postrouting priority 100 \\; }' && sudo nft add rule inet nat postrouting oifname \"ens33\" masquerade", "masquerade", "secu", "medium",
             "secu VM에 NAT 테이블을 만들고 ens33 인터페이스로 나가는 트래픽에 masquerade를 적용해줘"),
            ("verify", "작성한 whitelist 테이블의 룰셋을 확인하시오.", "nft list table inet whitelist",
             "sudo nft list table inet whitelist", "accept", "secu", "low",
             "secu VM whitelist 테이블 룰셋을 보여줘"),
            ("verify", "NAT 테이블의 postrouting 체인에 masquerade가 적용됐는지 확인하시오.", "nft list table inet nat",
             "sudo nft list table inet nat", "masquerade", "secu", "low",
             "secu VM nat 테이블의 postrouting 룰을 확인해줘"),
            ("cleanup", "실습 종료 후 whitelist, nat 테이블을 모두 삭제하시오.", "nft delete table …",
             "sudo nft delete table inet whitelist ; sudo nft delete table inet nat", "", "secu", "medium",
             "secu VM에서 whitelist와 nat 테이블을 모두 삭제해줘"),
            ("analysis", "nftables 테이블 목록을 확인해 정리되었는지 검증하시오.", "nft list tables",
             "sudo nft list tables", "table", "secu", "low",
             "secu VM nftables 테이블 목록을 확인해줘"),
        ],
    },
    4: {
        "title": "Suricata IPS 설치·구성",
        "description": "Suricata의 기본 설정, 인터페이스·규칙 경로, 초기 동작을 확인하고 기본 룰로 간단한 탐지를 수행한다.",
        "objectives": [
            "Suricata 서비스 설치·구성 상태를 확인할 수 있다",
            "suricata.yaml의 HOME_NET, 인터페이스 설정을 이해한다",
            "간단한 테스트 룰로 eve.json에 알람이 기록되는 것을 검증할 수 있다",
        ],
        "difficulty": "easy",
        "duration": 120,
        "steps": [
            ("survey", "secu VM에 Suricata가 설치되어 있는지 확인하시오.", "suricata -V",
             "suricata -V 2>&1 | head", "Suricata", "secu", "low",
             "secu VM의 Suricata 설치 버전을 확인해줘"),
            ("survey", "/etc/suricata/suricata.yaml 에서 HOME_NET 값을 확인하시오.", "grep HOME_NET /etc/suricata/suricata.yaml",
             "grep -n HOME_NET /etc/suricata/suricata.yaml | head", "HOME_NET", "secu", "low",
             "secu VM의 suricata.yaml에서 HOME_NET 설정을 확인해줘"),
            ("survey", "Suricata가 사용 중인 네트워크 인터페이스(af-packet section)를 확인하시오.", "awk '/af-packet/,/pcap/' /etc/suricata/suricata.yaml",
             "awk '/af-packet/,/pcap:/' /etc/suricata/suricata.yaml | head -15", "interface", "secu", "low",
             "secu VM의 suricata.yaml에서 af-packet 설정을 확인해줘"),
            ("configure", "/etc/suricata/rules/local.rules 에 'alert icmp any any -> any any (msg:\"ICMP ping\"; sid:1000001; rev:1;)' 룰을 추가하시오.", "echo … | sudo tee -a",
             "echo 'alert icmp any any -> any any (msg:\"ICMP ping\"; sid:1000001; rev:1;)' | sudo tee -a /etc/suricata/rules/local.rules", "ICMP", "secu", "medium",
             "secu VM의 suricata local.rules에 ICMP ping 탐지 룰(sid 1000001)을 추가해줘"),
            ("configure", "local.rules 가 suricata.yaml의 rule-files 섹션에 포함되어 있는지 확인하시오.", "grep local.rules /etc/suricata/suricata.yaml",
             "grep -n local.rules /etc/suricata/suricata.yaml || echo 'not referenced'", "local.rules", "secu", "low",
             "secu VM의 suricata.yaml에 local.rules가 참조되어 있는지 확인해줘"),
            ("configure", "Suricata 설정 파일 문법을 --test-config 로 검증하시오.", "suricata -T -c /etc/suricata/suricata.yaml",
             "sudo suricata -T -c /etc/suricata/suricata.yaml 2>&1 | tail -5", "configuration", "secu", "medium",
             "secu VM에서 suricata -T로 설정 파일 문법 검증을 해줘"),
            ("configure", "Suricata 서비스를 재시작해 새 룰을 로드하시오.", "systemctl restart suricata",
             "sudo systemctl restart suricata && sleep 2 && systemctl is-active suricata", "active", "secu", "high",
             "secu VM의 Suricata 서비스를 재시작해줘"),
            ("verify", "attacker VM에서 secu VM으로 ping을 3회 보내 ICMP 트래픽을 발생시키시오.", "ping -c 3 10.20.30.1",
             "ping -c 3 10.20.30.1", "bytes", "attacker", "low",
             "attacker VM에서 10.20.30.1로 ping을 3회 보내줘"),
            ("verify", "secu VM의 /var/log/suricata/eve.json 마지막 20줄에서 ICMP 알람을 찾으시오.", "tail /var/log/suricata/eve.json | grep ICMP",
             "sudo tail -50 /var/log/suricata/eve.json | grep -i 'ICMP ping' | head", "ICMP", "secu", "low",
             "secu VM의 suricata eve.json에서 ICMP ping 알람 항목을 찾아줘"),
            ("cleanup", "추가한 ICMP 테스트 룰(sid:1000001)을 local.rules 에서 제거하시오.", "sed -i '/sid:1000001/d' …",
             "sudo sed -i '/sid:1000001/d' /etc/suricata/rules/local.rules && sudo systemctl reload suricata", "", "secu", "medium",
             "secu VM local.rules에서 sid:1000001 룰을 삭제하고 suricata를 reload 해줘"),
        ],
    },
    5: {
        "title": "Suricata 룰 작성",
        "description": "content, pcre, flow, flowbits 등 Suricata 룰 키워드를 활용해 HTTP·TCP 탐지 룰을 작성한다.",
        "objectives": [
            "Suricata 룰 문법 (action protocol src → dst opts) 을 이해한다",
            "HTTP 요청에서 특정 User-Agent 를 탐지하는 룰을 작성할 수 있다",
            "suricata -T 로 룰 문법을 검증하고 eve.json 에서 매칭을 확인한다",
        ],
        "difficulty": "medium",
        "duration": 120,
        "steps": [
            ("configure", "local.rules 에 HTTP User-Agent 'BadBot'을 탐지하는 룰(sid:1000101)을 추가하시오.", "content:\"BadBot\"; http_user_agent;",
             "echo 'alert http any any -> any any (msg:\"Suspicious UA BadBot\"; content:\"BadBot\"; http_user_agent; sid:1000101; rev:1;)' | sudo tee -a /etc/suricata/rules/local.rules", "BadBot", "secu", "medium",
             "secu VM local.rules에 User-Agent=BadBot 탐지 HTTP 룰(sid 1000101)을 추가해줘"),
            ("configure", "SQL Injection 간단 룰 — URI에 'union select' 포함 탐지(sid:1000102)을 추가하시오.", "content:\"union select\"; http_uri;",
             "echo 'alert http any any -> any any (msg:\"SQLi union select\"; content:\"union select\"; nocase; http_uri; sid:1000102; rev:1;)' | sudo tee -a /etc/suricata/rules/local.rules", "union", "secu", "medium",
             "secu VM local.rules에 URI의 'union select' SQL Injection 탐지 룰(sid 1000102)을 추가해줘"),
            ("configure", "TCP 445 포트로 향하는 트래픽을 단순 탐지하는 룰(sid:1000103)을 추가하시오.", "tcp any any -> any 445 …",
             "echo 'alert tcp any any -> any 445 (msg:\"SMB traffic\"; sid:1000103; rev:1;)' | sudo tee -a /etc/suricata/rules/local.rules", "445", "secu", "low",
             "secu VM local.rules에 TCP 445(SMB) 트래픽 탐지 룰(sid 1000103)을 추가해줘"),
            ("verify", "suricata -T 로 룰 문법을 검증하시오.", "sudo suricata -T",
             "sudo suricata -T -c /etc/suricata/suricata.yaml 2>&1 | tail -5", "configuration", "secu", "medium",
             "secu VM에서 suricata 설정/룰 문법 검증을 실행해줘"),
            ("configure", "Suricata를 재로드하시오.", "systemctl reload suricata",
             "sudo systemctl reload suricata && systemctl is-active suricata", "active", "secu", "medium",
             "secu VM의 Suricata 서비스를 reload 해줘"),
            ("verify", "attacker VM에서 web VM으로 User-Agent BadBot 이 포함된 curl 요청을 보내시오.", "curl -A BadBot http://10.20.30.80/",
             "curl -sS -A BadBot http://10.20.30.80/ -o /dev/null && echo sent", "sent", "attacker", "medium",
             "attacker VM에서 web VM(10.20.30.80)으로 User-Agent=BadBot curl 요청을 보내줘"),
            ("verify", "secu VM eve.json 에서 BadBot 관련 알람을 확인하시오.", "grep BadBot /var/log/suricata/eve.json",
             "sudo tail -100 /var/log/suricata/eve.json | grep -i BadBot | head", "BadBot", "secu", "low",
             "secu VM의 suricata eve.json에서 BadBot 알람을 찾아줘"),
            ("verify", "attacker VM에서 URI에 'union select'을 포함한 HTTP 요청을 보내시오.", "curl '…?id=1 union select 1,2'",
             "curl -sS 'http://10.20.30.80/?id=1%20union%20select%201,2' -o /dev/null && echo sent", "sent", "attacker", "medium",
             "attacker VM에서 web VM으로 URI에 'union select'가 포함된 curl 요청을 보내줘"),
            ("verify", "secu VM eve.json 에서 SQLi union select 알람을 확인하시오.", "grep -i 'union' /var/log/suricata/eve.json",
             "sudo tail -200 /var/log/suricata/eve.json | grep -i 'union select' | head", "union", "secu", "low",
             "secu VM의 suricata eve.json에서 SQL Injection union select 알람을 찾아줘"),
            ("cleanup", "추가한 3개 룰을 local.rules 에서 제거하고 suricata를 reload 하시오.", "sed … sid:100010[1-3]",
             "sudo sed -i '/sid:100010[1-3]/d' /etc/suricata/rules/local.rules && sudo systemctl reload suricata", "", "secu", "medium",
             "secu VM local.rules에서 sid 1000101~1000103을 삭제하고 suricata reload 해줘"),
        ],
    },
    6: {
        "title": "Suricata 운영 — 튜닝·알람 분석",
        "description": "suricata-update로 룰셋을 갱신하고, stats.log / fast.log / eve.json 을 활용해 운영 상태를 점검한다.",
        "objectives": [
            "suricata-update 로 공식 룰셋을 갱신할 수 있다",
            "eve.json 을 jq로 파싱해 상위 signature/source 를 추출한다",
            "성능 통계(stats.log)를 확인해 drop/loss를 모니터링한다",
        ],
        "difficulty": "medium",
        "duration": 120,
        "steps": [
            ("configure", "secu VM에서 suricata-update list-sources 로 사용 가능한 룰셋 소스를 확인하시오.", "suricata-update list-sources",
             "sudo suricata-update list-sources 2>&1 | head", "source", "secu", "medium",
             "secu VM에서 suricata-update list-sources 를 실행해 사용 가능한 룰셋 소스를 보여줘"),
            ("configure", "et/open 룰셋을 enable 하시오.", "suricata-update enable-source et/open",
             "sudo suricata-update enable-source et/open 2>&1 | tail", "et/open", "secu", "medium",
             "secu VM에서 suricata-update에 et/open 룰셋을 enable 해줘"),
            ("configure", "suricata-update 를 실행해 룰셋을 다운로드·병합하시오.", "sudo suricata-update",
             "sudo suricata-update 2>&1 | tail -10", "rules", "secu", "medium",
             "secu VM에서 suricata-update 를 실행해 룰셋을 갱신해줘"),
            ("verify", "갱신된 룰 파일 위치(/var/lib/suricata/rules/suricata.rules)의 룰 개수를 확인하시오.", "wc -l /var/lib/suricata/rules/suricata.rules",
             "sudo wc -l /var/lib/suricata/rules/suricata.rules", "", "secu", "low",
             "secu VM의 갱신된 suricata.rules 파일 룰 개수를 확인해줘"),
            ("analysis", "eve.json 의 최근 50줄에서 event_type=alert 만 필터링해 상위 5개 signature 를 집계하시오.", "jq 필터 + sort | uniq",
             "sudo tail -500 /var/log/suricata/eve.json | jq -r 'select(.event_type==\"alert\") | .alert.signature' 2>/dev/null | sort | uniq -c | sort -rn | head", "alert", "secu", "low",
             "secu VM eve.json에서 최근 alert event 중 상위 5개 signature를 집계해줘"),
            ("analysis", "eve.json 에서 alert 를 가장 많이 발생시킨 source IP top 5 를 추출하시오.", "jq '.src_ip' …",
             "sudo tail -500 /var/log/suricata/eve.json | jq -r 'select(.event_type==\"alert\") | .src_ip' 2>/dev/null | sort | uniq -c | sort -rn | head", "", "secu", "low",
             "secu VM eve.json에서 alert를 많이 발생시킨 source IP top 5를 추출해줘"),
            ("analysis", "/var/log/suricata/stats.log 에서 'kernel_drops' 항목을 확인해 drop 여부를 점검하시오.", "grep kernel_drops …",
             "sudo grep kernel_drops /var/log/suricata/stats.log | tail", "kernel_drops", "secu", "low",
             "secu VM의 suricata stats.log에서 kernel_drops 수치를 확인해줘"),
            ("analysis", "/var/log/suricata/fast.log 마지막 20줄을 출력해 최근 알람을 확인하시오.", "tail -20 /var/log/suricata/fast.log",
             "sudo tail -20 /var/log/suricata/fast.log", "", "secu", "low",
             "secu VM의 suricata fast.log 마지막 20줄을 보여줘"),
            ("tuning", "suricata.yaml의 threshold 설정 파일 경로를 확인하시오.", "grep threshold-file /etc/suricata/suricata.yaml",
             "grep -n threshold-file /etc/suricata/suricata.yaml", "threshold", "secu", "low",
             "secu VM suricata.yaml에서 threshold-file 설정 경로를 찾아줘"),
            ("verify", "suricatasc 로 Suricata 엔진의 uptime 을 질의하시오.", "suricatasc -c uptime",
             "sudo suricatasc -c uptime 2>&1 | head", "uptime", "secu", "low",
             "secu VM에서 suricatasc 를 사용해 Suricata uptime을 조회해줘"),
        ],
    },
    7: {
        "title": "Apache + ModSecurity WAF",
        "description": "web VM의 Apache + ModSecurity WAF 구성을 점검하고 CRS 룰로 SQLi/XSS 탐지가 작동하는지 검증한다.",
        "objectives": [
            "ModSecurity의 기본 구성·엔진 on/off·감사 로그 위치를 확인한다",
            "OWASP CRS 룰로 SQLi/XSS 차단을 테스트한다",
            "/var/log/apache2/modsec_audit.log 에서 차단 기록을 확인한다",
        ],
        "difficulty": "medium",
        "duration": 120,
        "steps": [
            ("survey", "web VM에서 Apache + ModSecurity가 동작 중인지 확인하시오.", "apachectl -M | grep -i security",
             "apachectl -M 2>/dev/null | grep -i security", "security", "web", "low",
             "web VM의 Apache에 ModSecurity 모듈이 로드됐는지 확인해줘"),
            ("survey", "modsecurity.conf 에서 SecRuleEngine 값을 확인하시오.", "grep SecRuleEngine …",
             "sudo grep -H SecRuleEngine /etc/modsecurity/modsecurity.conf /etc/apache2/mods-enabled/security2.conf 2>/dev/null", "SecRuleEngine", "web", "low",
             "web VM에서 ModSecurity SecRuleEngine 설정 값을 확인해줘"),
            ("survey", "OWASP CRS 디렉터리의 룰 파일 개수를 확인하시오.", "ls /usr/share/modsecurity-crs/rules | wc -l",
             "ls /usr/share/modsecurity-crs/rules/ 2>/dev/null | wc -l || ls /etc/modsecurity/crs/rules 2>/dev/null | wc -l", "", "web", "low",
             "web VM의 ModSecurity CRS 룰 파일 개수를 세어줘"),
            ("configure", "SecRuleEngine 이 DetectionOnly 라면 On 으로 바꾸시오(이미 On 이면 건너뜀).", "sed … SecRuleEngine",
             "sudo sed -i 's/^SecRuleEngine DetectionOnly/SecRuleEngine On/' /etc/modsecurity/modsecurity.conf 2>/dev/null ; grep SecRuleEngine /etc/modsecurity/modsecurity.conf", "SecRuleEngine", "web", "high",
             "web VM의 ModSecurity SecRuleEngine을 On으로 설정해줘"),
            ("configure", "Apache를 재시작해 설정을 반영하시오.", "systemctl restart apache2",
             "sudo systemctl restart apache2 && systemctl is-active apache2", "active", "web", "high",
             "web VM의 Apache 서비스를 재시작해줘"),
            ("verify", "attacker VM에서 SQL Injection payload로 테스트 요청을 보내시오 (403 차단 확인).", "curl -o /dev/null -w '%{http_code}' '…union select…'",
             "curl -sS -o /dev/null -w '%{http_code}\\n' 'http://10.20.30.80/?id=1%20union%20select%201,2'", "403", "attacker", "medium",
             "attacker VM에서 web VM으로 'union select' SQLi payload를 curl로 보내고 HTTP 응답 코드를 보여줘"),
            ("verify", "attacker VM에서 XSS payload 요청을 보내 차단 응답을 확인하시오.", "curl -w '%{http_code}' '…<script>…'",
             "curl -sS -o /dev/null -w '%{http_code}\\n' 'http://10.20.30.80/?q=%3Cscript%3Ealert(1)%3C%2Fscript%3E'", "403", "attacker", "medium",
             "attacker VM에서 web VM으로 <script>alert(1)</script> XSS payload를 curl로 보내고 응답 코드를 보여줘"),
            ("analysis", "web VM에서 modsec_audit.log 마지막 30줄을 확인해 차단 기록을 찾으시오.", "tail /var/log/apache2/modsec_audit.log",
             "sudo tail -30 /var/log/apache2/modsec_audit.log 2>/dev/null | head -20", "ModSec", "web", "low",
             "web VM의 modsec_audit.log 최근 30줄을 보여줘"),
            ("analysis", "modsec_audit.log 에서 rule id 942(SQLi)에 해당하는 이벤트를 카운트하시오.", "grep -c '942'",
             "sudo grep -c '\\[id \\\"942' /var/log/apache2/modsec_audit.log 2>/dev/null", "", "web", "low",
             "web VM의 modsec_audit.log에서 rule id 942 관련 이벤트 개수를 세어줘"),
            ("verify", "정상 GET 요청(/ 루트)이 200 으로 응답하는지 확인하시오(정상 트래픽 미차단 검증).", "curl -w '%{http_code}' http://10.20.30.80/",
             "curl -sS -o /dev/null -w '%{http_code}\\n' http://10.20.30.80/", "200", "attacker", "low",
             "attacker VM에서 web VM의 / 루트를 curl로 요청하고 응답 코드를 보여줘"),
        ],
    },
    8: {
        "title": "중간고사 — 방화벽 + IPS 구성 실기",
        "description": "nftables와 Suricata를 조합해 실전 보안 인프라의 일부를 구성하고 검증한다.",
        "objectives": [
            "nftables로 기본 방어선(화이트리스트+SSH 레이트리밋)을 구축한다",
            "Suricata 커스텀 룰로 특정 공격 패턴을 탐지한다",
            "두 솔루션의 로그를 상호 검증한다",
        ],
        "difficulty": "hard",
        "duration": 150,
        "steps": [
            ("configure", "secu VM에 'exam' nftables 테이블과 policy drop input 체인을 만드시오.", "nft add table inet exam; nft add chain …",
             "sudo nft add table inet exam && sudo nft add chain inet exam input '{ type filter hook input priority 0 \\; policy drop \\; }'", "exam", "secu", "medium",
             "secu VM에 'inet exam' 테이블과 policy drop의 input 체인을 만들어줘"),
            ("configure", "established,related 상태와 loopback 을 허용하시오.", "ct state established,related accept; iifname lo accept",
             "sudo nft add rule inet exam input ct state established,related accept && sudo nft add rule inet exam input iifname lo accept", "lo", "secu", "medium",
             "secu VM exam.input 체인에 established 연결과 loopback 허용 룰을 추가해줘"),
            ("configure", "소스 IP 10.20.30.0/24 에서 SSH(22) 를 허용하되 new 연결은 5/minute 로 제한하시오.", "ip saddr 10.20.30.0/24 tcp dport 22 ct state new limit rate 5/minute accept",
             "sudo nft add rule inet exam input ip saddr 10.20.30.0/24 tcp dport 22 ct state new limit rate 5/minute accept", "limit rate", "secu", "medium",
             "secu VM exam.input에 10.20.30.0/24에서 SSH new 연결을 5/minute로 제한하는 룰을 추가해줘"),
            ("configure", "icmp echo-request 를 허용하는 룰을 추가하시오.", "icmp type echo-request accept",
             "sudo nft add rule inet exam input icmp type echo-request accept", "echo-request", "secu", "low",
             "secu VM exam.input에 ICMP echo-request 허용 룰을 추가해줘"),
            ("configure", "Suricata local.rules 에 '.exe' 파일 요청 탐지 룰(sid:1000201)을 추가하시오.", "content:\".exe\"; http_uri;",
             "echo 'alert http any any -> any any (msg:\"Exam Rule - exe download\"; content:\".exe\"; http_uri; sid:1000201; rev:1;)' | sudo tee -a /etc/suricata/rules/local.rules && sudo systemctl reload suricata", "1000201", "secu", "medium",
             "secu VM local.rules에 http_uri에 '.exe'가 포함된 요청을 탐지하는 룰(sid 1000201)을 추가하고 reload 해줘"),
            ("verify", "exam 테이블 전체 룰셋을 확인하시오.", "nft list table inet exam",
             "sudo nft list table inet exam", "exam", "secu", "low",
             "secu VM의 exam 테이블 룰셋을 보여줘"),
            ("verify", "attacker VM에서 secu 로 ping 이 성공하는지 확인하시오(허용 룰 검증).", "ping -c 2 10.20.30.1",
             "ping -c 2 10.20.30.1", "bytes", "attacker", "low",
             "attacker VM에서 secu VM으로 ping 2회를 보내 응답을 확인해줘"),
            ("verify", "attacker VM에서 web VM으로 '/malware.exe' 요청을 보내시오(Suricata 룰 트리거).", "curl '/malware.exe'",
             "curl -sS -o /dev/null -w '%{http_code}\\n' http://10.20.30.80/malware.exe", "", "attacker", "medium",
             "attacker VM에서 web VM(10.20.30.80)으로 /malware.exe 경로에 curl 요청을 보내줘"),
            ("verify", "secu VM eve.json 에서 sid:1000201 알람이 기록됐는지 확인하시오.", "grep 1000201 /var/log/suricata/eve.json",
             "sudo grep -c '\"signature_id\":1000201' /var/log/suricata/eve.json 2>/dev/null || sudo grep 1000201 /var/log/suricata/eve.json | head", "1000201", "secu", "low",
             "secu VM의 suricata eve.json에서 sid 1000201 알람을 찾아줘"),
            ("cleanup", "실습 종료: exam 테이블과 sid:1000201 룰을 모두 제거하고 reload 하시오.", "nft delete table; sed …",
             "sudo nft delete table inet exam && sudo sed -i '/sid:1000201/d' /etc/suricata/rules/local.rules && sudo systemctl reload suricata", "", "secu", "medium",
             "secu VM에서 exam 테이블과 sid 1000201 룰을 삭제하고 suricata reload 해줘"),
        ],
    },
    9: {
        "title": "Wazuh SIEM 설치·구성",
        "description": "Wazuh Manager·Indexer·Dashboard 구성 상태를 확인하고 siem의 agent 목록을 조회한다.",
        "objectives": [
            "Wazuh Manager/Indexer/Dashboard/agent 서비스 상태를 확인한다",
            "/var/ossec/etc/ossec.conf 의 주요 설정을 이해한다",
            "agent_control / wazuh-wui 로 에이전트 목록을 조회한다",
        ],
        "difficulty": "medium",
        "duration": 120,
        "steps": [
            ("survey", "siem VM에서 Wazuh Manager 서비스 상태를 확인하시오.", "systemctl is-active wazuh-manager",
             "systemctl is-active wazuh-manager", "active", "siem", "low",
             "siem VM의 wazuh-manager 서비스 상태를 확인해줘"),
            ("survey", "Wazuh Indexer 서비스 상태를 확인하시오.", "systemctl is-active wazuh-indexer",
             "systemctl is-active wazuh-indexer || echo inactive", "", "siem", "low",
             "siem VM의 wazuh-indexer 서비스 상태를 확인해줘"),
            ("survey", "Wazuh Dashboard 서비스 상태를 확인하시오.", "systemctl is-active wazuh-dashboard",
             "systemctl is-active wazuh-dashboard || echo inactive", "", "siem", "low",
             "siem VM의 wazuh-dashboard 서비스 상태를 확인해줘"),
            ("survey", "wazuh-control info 로 Wazuh 버전·설치 정보를 확인하시오.", "/var/ossec/bin/wazuh-control info",
             "sudo /var/ossec/bin/wazuh-control info 2>&1 | head", "WAZUH", "siem", "low",
             "siem VM에서 wazuh-control info 로 설치 정보를 확인해줘"),
            ("survey", "agent_control -l 로 등록된 에이전트 목록을 조회하시오.", "/var/ossec/bin/agent_control -l",
             "sudo /var/ossec/bin/agent_control -l 2>&1 | head", "", "siem", "low",
             "siem VM에서 agent_control -l 로 에이전트 목록을 보여줘"),
            ("survey", "/var/ossec/etc/ossec.conf 에서 <global> 섹션을 확인하시오.", "awk '/<global>/,/<\\/global>/' …",
             "sudo awk '/<global>/,/<\\/global>/' /var/ossec/etc/ossec.conf | head -20", "global", "siem", "low",
             "siem VM의 ossec.conf <global> 섹션을 보여줘"),
            ("survey", "ossec.conf 에서 <alerts>/<log_alert_level> 값을 확인하시오.", "grep log_alert_level …",
             "sudo grep -n log_alert_level /var/ossec/etc/ossec.conf", "log_alert_level", "siem", "low",
             "siem VM의 ossec.conf에서 log_alert_level 값을 확인해줘"),
            ("verify", "Wazuh Manager의 최근 alerts.json 2줄을 확인하시오.", "tail -2 /var/ossec/logs/alerts/alerts.json",
             "sudo tail -2 /var/ossec/logs/alerts/alerts.json 2>/dev/null", "", "siem", "low",
             "siem VM의 wazuh alerts.json 최근 2줄을 보여줘"),
            ("verify", "Wazuh Indexer API(9200) 가 응답하는지 확인하시오.", "curl -k https://localhost:9200",
             "curl -sk -o /dev/null -w '%{http_code}\\n' https://localhost:9200 -u admin:admin 2>/dev/null || ss -tlnp | grep 9200", "9200", "siem", "low",
             "siem VM의 Wazuh Indexer(9200) 리스닝/응답 상태를 확인해줘"),
            ("analysis", "최근 1시간 alerts.json 내 alert 수를 집계하시오.", "wc -l alerts.json",
             "sudo wc -l /var/ossec/logs/alerts/alerts.json 2>/dev/null", "", "siem", "low",
             "siem VM의 wazuh alerts.json 라인 수를 확인해줘"),
        ],
    },
    10: {
        "title": "Wazuh 탐지 룰 작성",
        "description": "Wazuh decoder/rule 구조를 이해하고 커스텀 로컬 룰로 SSH 실패, sudo 실행 등을 탐지한다.",
        "objectives": [
            "wazuh rules 디렉터리 구조와 local_rules.xml 의 역할을 이해한다",
            "wazuh-logtest 로 룰 매칭을 테스트한다",
            "reload 후 alerts.json 에서 새 룰이 적용된 결과를 확인한다",
        ],
        "difficulty": "medium",
        "duration": 120,
        "steps": [
            ("survey", "/var/ossec/ruleset/rules 디렉터리의 룰 파일 개수를 확인하시오.", "ls /var/ossec/ruleset/rules | wc -l",
             "sudo ls /var/ossec/ruleset/rules/ 2>/dev/null | wc -l", "", "siem", "low",
             "siem VM의 wazuh ruleset/rules 디렉터리에 있는 룰 파일 개수를 확인해줘"),
            ("survey", "local_rules.xml 의 현재 내용을 확인하시오.", "cat /var/ossec/etc/rules/local_rules.xml",
             "sudo cat /var/ossec/etc/rules/local_rules.xml 2>/dev/null | head -30", "rules", "siem", "low",
             "siem VM의 wazuh local_rules.xml 상단 30줄을 보여줘"),
            ("configure", "local_rules.xml 에 '여러 번 sudo 실패' 탐지 룰(rule id 100100, level 10)을 추가하시오.", "<rule id=\"100100\" level=\"10\">…",
             "sudo bash -c 'cat >> /var/ossec/etc/rules/local_rules.xml <<EOF\n<group name=\"local,syslog,sudo,\">\n  <rule id=\"100100\" level=\"10\" frequency=\"3\" timeframe=\"120\">\n    <if_matched_sid>5402</if_matched_sid>\n    <description>Multiple sudo failures (custom)</description>\n  </rule>\n</group>\nEOF'", "100100", "siem", "medium",
             "siem VM의 wazuh local_rules.xml에 sudo 실패 3회 탐지 룰(rule id 100100, level 10)을 추가해줘"),
            ("verify", "wazuh-analysisd -t 로 룰 문법을 검증하시오.", "sudo /var/ossec/bin/wazuh-analysisd -t",
             "sudo /var/ossec/bin/wazuh-analysisd -t 2>&1 | tail", "Configuration", "siem", "medium",
             "siem VM에서 wazuh-analysisd -t 로 룰 문법 검증을 실행해줘"),
            ("configure", "Wazuh Manager 를 재시작해 새 룰을 로드하시오.", "systemctl restart wazuh-manager",
             "sudo systemctl restart wazuh-manager && systemctl is-active wazuh-manager", "active", "siem", "high",
             "siem VM의 wazuh-manager 서비스를 재시작해줘"),
            ("verify", "wazuh-logtest 로 'Feb 1 12:34:56 host sudo: user : 3 incorrect password attempts' 로그를 넣어 새 룰이 매칭되는지 테스트하시오.", "echo '…' | /var/ossec/bin/wazuh-logtest",
             "echo 'Feb 01 12:34:56 host sudo:    root : 3 incorrect password attempts' | sudo /var/ossec/bin/wazuh-logtest 2>&1 | tail -15", "sudo", "siem", "low",
             "siem VM에서 wazuh-logtest에 'sudo incorrect password attempts' 로그를 넣어 룰 매칭을 테스트해줘"),
            ("analysis", "alerts.json 에서 rule.id=100100 의 최근 항목을 검색하시오.", "grep 100100 …",
             "sudo grep '\"id\":\"100100\"' /var/ossec/logs/alerts/alerts.json 2>/dev/null | tail -5 || echo 'no hits yet'", "", "siem", "low",
             "siem VM의 wazuh alerts.json에서 rule id 100100의 최근 5건을 보여줘"),
            ("analysis", "/var/ossec/logs/ossec.log 의 오류(ERROR) 라인을 5개 출력하시오.", "grep ERROR ossec.log",
             "sudo grep -i ERROR /var/ossec/logs/ossec.log 2>/dev/null | tail -5", "", "siem", "low",
             "siem VM의 wazuh ossec.log에서 ERROR 로그 최근 5건을 보여줘"),
            ("cleanup", "추가했던 custom 룰 그룹을 local_rules.xml 에서 제거하시오.", "sed … 100100",
             "sudo sed -i '/<rule id=\"100100\"/,/<\\/group>/d' /var/ossec/etc/rules/local_rules.xml", "", "siem", "medium",
             "siem VM의 wazuh local_rules.xml에서 rule id 100100 블록을 제거해줘"),
            ("configure", "Wazuh Manager 를 reload(restart) 하여 정리된 상태로 복귀하시오.", "systemctl restart wazuh-manager",
             "sudo systemctl restart wazuh-manager && systemctl is-active wazuh-manager", "active", "siem", "high",
             "siem VM의 wazuh-manager 를 재시작해줘"),
        ],
    },
    11: {
        "title": "Wazuh FIM / SCA / Active Response",
        "description": "File Integrity Monitoring, Security Configuration Assessment, Active Response 기능을 구성·검증한다.",
        "objectives": [
            "FIM(syscheck)이 감시 중인 경로를 확인한다",
            "SCA 모듈의 최근 스캔 결과를 조회한다",
            "Active Response로 악성 IP를 firewall-drop 하는 체인을 확인한다",
        ],
        "difficulty": "medium",
        "duration": 120,
        "steps": [
            ("survey", "ossec.conf의 <syscheck> 섹션에서 감시 디렉터리 목록을 확인하시오.", "grep directories /var/ossec/etc/ossec.conf",
             "sudo grep -E '<directories' /var/ossec/etc/ossec.conf | head -10", "directories", "siem", "low",
             "siem VM의 ossec.conf에서 syscheck 감시 디렉터리 목록을 보여줘"),
            ("verify", "FIM 데이터베이스(/var/ossec/queue/fim/db/fim.db)의 존재를 확인하시오.", "ls -la /var/ossec/queue/fim/db/fim.db",
             "sudo ls -la /var/ossec/queue/fim/db/fim.db 2>/dev/null || echo 'no fim.db'", "fim", "siem", "low",
             "siem VM의 wazuh FIM db 파일 존재 여부를 확인해줘"),
            ("verify", "test 파일 /etc/ccc-fim-test 를 생성해 FIM 이벤트를 발생시키시오.", "sudo touch /etc/ccc-fim-test",
             "sudo touch /etc/ccc-fim-test && ls -la /etc/ccc-fim-test", "ccc-fim", "siem", "medium",
             "siem VM에서 /etc/ccc-fim-test 파일을 생성해 FIM 이벤트를 트리거해줘"),
            ("analysis", "alerts.json 에서 /etc/ccc-fim-test 관련 이벤트를 검색하시오(FIM 이벤트 지연 반영 가능).", "grep ccc-fim-test …",
             "sleep 10 && sudo grep ccc-fim-test /var/ossec/logs/alerts/alerts.json 2>/dev/null | tail", "", "siem", "low",
             "siem VM의 wazuh alerts.json에서 /etc/ccc-fim-test 관련 이벤트를 찾아줘"),
            ("survey", "SCA 모듈의 활성 여부를 ossec.conf 에서 확인하시오.", "grep -A3 '<sca>' /var/ossec/etc/ossec.conf",
             "sudo awk '/<sca>/,/<\\/sca>/' /var/ossec/etc/ossec.conf | head", "sca", "siem", "low",
             "siem VM의 ossec.conf에서 <sca> 섹션 설정을 보여줘"),
            ("analysis", "SCA 최근 스캔 결과(/var/ossec/logs/alerts/alerts.json) 에서 'sca'를 필터링하시오.", "grep sca … alerts.json",
             "sudo grep '\"sca\"' /var/ossec/logs/alerts/alerts.json 2>/dev/null | tail -3", "", "siem", "low",
             "siem VM의 wazuh alerts.json에서 SCA 관련 이벤트 최근 3건을 보여줘"),
            ("survey", "Active Response 설정(<active-response>)에서 command 목록을 확인하시오.", "awk active-response",
             "sudo awk '/<active-response>/,/<\\/active-response>/' /var/ossec/etc/ossec.conf | head -15", "active-response", "siem", "low",
             "siem VM의 ossec.conf에서 active-response 블록 설정을 보여줘"),
            ("configure", "secu VM에 blocklist set (type ipv4_addr) 을 만들고 nftables 에 blocklist drop 룰을 추가하시오.", "nft add set; nft add rule",
             "sudo nft add table inet filter 2>/dev/null ; sudo nft 'add set inet filter blocklist { type ipv4_addr \\; }' 2>/dev/null ; sudo nft add rule inet filter input ip saddr @blocklist drop 2>/dev/null ; sudo nft list set inet filter blocklist", "blocklist", "secu", "medium",
             "secu VM에 filter.blocklist ipv4 set을 만들고 input 체인에 saddr @blocklist drop 룰을 추가해줘"),
            ("configure", "blocklist set 에 10.20.30.201 을 임시로 추가해 공격자 차단을 시뮬레이션하시오.", "nft add element inet filter blocklist { 10.20.30.201 }",
             "sudo nft add element inet filter blocklist '{ 10.20.30.201 }' && sudo nft list set inet filter blocklist", "10.20.30.201", "secu", "medium",
             "secu VM의 filter.blocklist set에 10.20.30.201을 추가해줘"),
            ("cleanup", "blocklist 에서 10.20.30.201을 제거해 원상 복구하시오.", "nft delete element …",
             "sudo nft delete element inet filter blocklist '{ 10.20.30.201 }'", "", "secu", "medium",
             "secu VM의 filter.blocklist set에서 10.20.30.201을 제거해줘"),
        ],
    },
    12: {
        "title": "OpenCTI 설치·구성",
        "description": "siem에 배포된 OpenCTI 컨테이너 구성·초기 상태·포트를 확인한다.",
        "objectives": [
            "docker 기반 OpenCTI 구성을 확인한다",
            "OpenCTI 컨테이너 상태와 포트(8080)를 점검한다",
            "초기 로그에서 에러가 없는지 확인한다",
        ],
        "difficulty": "easy",
        "duration": 90,
        "steps": [
            ("survey", "siem VM에서 docker compose로 관리되는 컨테이너 목록을 확인하시오.", "docker ps",
             "docker ps --format '{{.Names}}\\t{{.Status}}' 2>/dev/null | head", "opencti", "siem", "low",
             "siem VM의 docker 컨테이너 목록을 보여줘"),
            ("survey", "opencti 관련 컨테이너만 필터링하시오.", "docker ps | grep opencti",
             "docker ps --format '{{.Names}}\\t{{.Status}}' 2>/dev/null | grep -i opencti", "opencti", "siem", "low",
             "siem VM에서 opencti 컨테이너만 필터링해서 보여줘"),
            ("survey", "OpenCTI 플랫폼 컨테이너의 최근 로그 20줄을 확인하시오.", "docker logs --tail 20 opencti",
             "docker logs --tail 20 $(docker ps --format '{{.Names}}' | grep -i '^opencti$' | head -1) 2>&1 | tail -20", "", "siem", "low",
             "siem VM의 opencti 플랫폼 컨테이너 로그 20줄을 보여줘"),
            ("survey", "OpenCTI 웹 UI 포트(8080) 가 리스닝 중인지 확인하시오.", "ss -tlnp | grep 8080",
             "ss -tlnp 2>/dev/null | grep ':8080'", "8080", "siem", "low",
             "siem VM에서 8080 포트 리스닝 상태를 확인해줘"),
            ("survey", "OpenCTI 의존 서비스(redis, elastic, rabbitmq, minio) 컨테이너 상태를 확인하시오.", "docker ps | grep -E …",
             "docker ps --format '{{.Names}}\\t{{.Status}}' 2>/dev/null | grep -Ei 'redis|elastic|rabbit|minio'", "", "siem", "low",
             "siem VM에서 OpenCTI 의존 서비스(redis/elastic/rabbit/minio) 컨테이너 상태를 보여줘"),
            ("survey", "OpenCTI docker-compose.yml 파일 위치를 찾으시오.", "find / -name docker-compose.yml 2>/dev/null | grep -i cti",
             "find / -name 'docker-compose*.yml' 2>/dev/null | grep -i cti | head", "compose", "siem", "low",
             "siem VM에서 opencti 관련 docker-compose 파일 위치를 찾아줘"),
            ("verify", "localhost:8080 에 HTTP 요청을 보내 응답 코드를 확인하시오.", "curl -w '%{http_code}' http://localhost:8080",
             "curl -sS -o /dev/null -w '%{http_code}\\n' http://localhost:8080", "", "siem", "low",
             "siem VM에서 http://localhost:8080 에 curl 요청을 보내 응답 코드를 보여줘"),
            ("analysis", "OpenCTI 플랫폼 컨테이너에서 'ERROR' 로그를 최근 50줄에서 카운트하시오.", "docker logs … | grep ERROR",
             "docker logs --tail 50 $(docker ps --format '{{.Names}}' | grep -i '^opencti$' | head -1) 2>&1 | grep -c ERROR", "", "siem", "low",
             "siem VM opencti 플랫폼 로그에서 ERROR 횟수를 세어줘"),
            ("analysis", "컨테이너별 CPU/Memory 사용량(docker stats --no-stream)을 조회하시오.", "docker stats --no-stream",
             "docker stats --no-stream --format '{{.Name}}\\t{{.CPUPerc}}\\t{{.MemUsage}}' 2>/dev/null | head", "", "siem", "low",
             "siem VM의 docker stats로 컨테이너별 CPU/메모리 사용량을 보여줘"),
            ("verify", "OpenCTI 재기동이 필요하지 않은지 컨테이너 재시작 횟수를 확인하시오.", "docker inspect … RestartCount",
             "docker inspect $(docker ps --format '{{.Names}}' | grep -i opencti | head -1) --format '{{.RestartCount}}' 2>/dev/null", "", "siem", "low",
             "siem VM의 opencti 컨테이너 재시작 횟수를 확인해줘"),
        ],
    },
    13: {
        "title": "OpenCTI 위협 인텔리전스 활용",
        "description": "OpenCTI에 CTI feed를 연동하고 IOC(악성 IP)를 nftables blocklist 와 연계한다.",
        "objectives": [
            "OpenCTI GraphQL API 구조를 이해한다",
            "IOC를 조회해 nftables set에 주입하는 파이프라인을 설계한다",
            "CTI 기반 차단 룰이 적용되는 것을 검증한다",
        ],
        "difficulty": "medium",
        "duration": 120,
        "steps": [
            ("survey", "OpenCTI GraphQL 엔드포인트(/graphql) 가 응답하는지 확인하시오.", "curl -X POST /graphql",
             "curl -sS -o /dev/null -w '%{http_code}\\n' -X POST http://localhost:8080/graphql -H 'Content-Type: application/json' -d '{\"query\":\"{ about { version } }\"}'", "", "siem", "low",
             "siem VM의 OpenCTI /graphql 엔드포인트에 POST 테스트 요청을 보내 응답 코드를 보여줘"),
            ("configure", "secu VM에 cti 전용 blocklist set 'cti_ips'(filter 테이블) 를 만드시오.", "nft add set inet filter cti_ips",
             "sudo nft add table inet filter 2>/dev/null ; sudo nft 'add set inet filter cti_ips { type ipv4_addr \\; }' 2>/dev/null && sudo nft list set inet filter cti_ips", "cti_ips", "secu", "medium",
             "secu VM에 filter.cti_ips ipv4 set을 생성해줘"),
            ("configure", "filter.input 체인 초기에 ip saddr @cti_ips drop 룰을 추가하시오.", "nft insert rule …",
             "sudo nft add chain inet filter input '{ type filter hook input priority 0 \\; }' 2>/dev/null ; sudo nft insert rule inet filter input ip saddr @cti_ips drop", "cti_ips", "secu", "medium",
             "secu VM filter.input 체인 맨 앞에 @cti_ips set 기반 drop 룰을 추가해줘"),
            ("verify", "작성한 cti_ips set의 현재 원소를 확인하시오.", "nft list set inet filter cti_ips",
             "sudo nft list set inet filter cti_ips", "cti_ips", "secu", "low",
             "secu VM filter.cti_ips set의 원소 목록을 확인해줘"),
            ("configure", "샘플 악성 IP 203.0.113.66 을 cti_ips 에 주입하시오(OpenCTI 조회 결과를 가정).", "nft add element inet filter cti_ips { 203.0.113.66 }",
             "sudo nft add element inet filter cti_ips '{ 203.0.113.66 }' && sudo nft list set inet filter cti_ips", "203.0.113.66", "secu", "medium",
             "secu VM filter.cti_ips set에 203.0.113.66을 추가해줘"),
            ("verify", "203.0.113.66 가 blocklist 로 등록됐는지 확인하시오.", "nft list set inet filter cti_ips",
             "sudo nft list set inet filter cti_ips", "203.0.113.66", "secu", "low",
             "secu VM filter.cti_ips set의 내용을 다시 확인해줘"),
            ("analysis", "OpenCTI 컨테이너에서 최근 5개 Indicator 생성 이벤트 로그를 조회하시오(platform 컨테이너 로그).", "docker logs | grep Indicator",
             "docker logs --tail 200 $(docker ps --format '{{.Names}}' | grep -i '^opencti$' | head -1) 2>&1 | grep -i indicator | tail -5", "", "siem", "low",
             "siem VM의 OpenCTI 플랫폼 로그에서 Indicator 관련 로그 최근 5건을 보여줘"),
            ("survey", "OpenCTI connectors 컨테이너 목록을 확인하시오.", "docker ps | grep connector",
             "docker ps --format '{{.Names}}\\t{{.Status}}' 2>/dev/null | grep -i connector | head", "", "siem", "low",
             "siem VM에서 opencti connector 관련 컨테이너 목록을 보여줘"),
            ("cleanup", "샘플 IP 203.0.113.66 을 cti_ips 에서 제거하시오.", "nft delete element …",
             "sudo nft delete element inet filter cti_ips '{ 203.0.113.66 }'", "", "secu", "medium",
             "secu VM filter.cti_ips set에서 203.0.113.66을 제거해줘"),
            ("analysis", "filter.input 체인의 현재 룰을 확인해 정리 상태를 점검하시오.", "nft list chain inet filter input",
             "sudo nft list chain inet filter input", "cti_ips", "secu", "low",
             "secu VM filter.input 체인의 룰을 확인해줘"),
        ],
    },
    14: {
        "title": "통합 보안 아키텍처 — 방화벽·IPS·SIEM·CTI 연계",
        "description": "각 보안 솔루션의 이벤트가 Wazuh SIEM으로 수렴되고 CTI와 연계되는 흐름을 점검한다.",
        "objectives": [
            "Suricata → Wazuh 로 eve.json 이 수집되는지 확인한다",
            "ModSecurity → Wazuh 감사 로그 수집 경로를 확인한다",
            "CTI → nftables 차단 체인까지 이어지는 end-to-end 흐름을 검증한다",
        ],
        "difficulty": "hard",
        "duration": 120,
        "steps": [
            ("survey", "secu VM에서 suricata eve.json 이 /var/log/suricata/eve.json 으로 기록되는지 확인하시오.", "ls -la /var/log/suricata/eve.json",
             "sudo ls -la /var/log/suricata/eve.json 2>/dev/null", "eve.json", "secu", "low",
             "secu VM의 suricata eve.json 파일 존재·크기를 확인해줘"),
            ("survey", "secu VM에 wazuh-agent 가 설치되어 있는지 확인하시오.", "systemctl is-active wazuh-agent",
             "systemctl is-active wazuh-agent || /var/ossec/bin/wazuh-control status 2>/dev/null | head", "wazuh", "secu", "low",
             "secu VM에 wazuh-agent가 동작 중인지 확인해줘"),
            ("survey", "secu VM 의 ossec.conf 에서 eve.json 을 수집하는 <localfile> 설정을 확인하시오.", "grep eve.json /var/ossec/etc/ossec.conf",
             "sudo grep -A2 -B1 eve.json /var/ossec/etc/ossec.conf 2>/dev/null | head", "eve.json", "secu", "low",
             "secu VM ossec.conf에서 eve.json 을 수집하는 localfile 설정을 보여줘"),
            ("verify", "siem VM에서 attacker IP(10.20.30.201)에 대한 최근 wazuh alert를 조회하시오.", "grep 10.20.30.201 alerts.json",
             "sudo grep 10.20.30.201 /var/ossec/logs/alerts/alerts.json 2>/dev/null | tail -3", "", "siem", "low",
             "siem VM의 wazuh alerts.json에서 10.20.30.201 관련 최근 alert를 보여줘"),
            ("survey", "web VM의 ossec.conf 에서 modsec_audit.log 수집 설정을 확인하시오.", "grep modsec_audit ossec.conf",
             "sudo grep -B1 -A2 modsec_audit /var/ossec/etc/ossec.conf 2>/dev/null | head", "modsec", "web", "low",
             "web VM ossec.conf에서 modsec_audit.log 수집 localfile 설정을 보여줘"),
            ("verify", "attacker VM에서 '<script>alert(1)</script>' payload로 web VM에 요청을 보내 전체 체인을 트리거하시오.", "curl …",
             "curl -sS -o /dev/null -w '%{http_code}\\n' 'http://10.20.30.80/?q=%3Cscript%3Ealert(1)%3C%2Fscript%3E'", "", "attacker", "medium",
             "attacker VM에서 web VM으로 <script>alert(1)</script> XSS 요청을 보내줘"),
            ("analysis", "siem VM alerts.json 에서 XSS 또는 Cross-Site 관련 이벤트를 검색하시오.", "grep -i xss alerts.json",
             "sudo grep -iE 'XSS|Cross-Site|script' /var/ossec/logs/alerts/alerts.json 2>/dev/null | tail -3", "", "siem", "low",
             "siem VM wazuh alerts.json에서 XSS/Cross-Site 관련 이벤트 최근 3건을 찾아줘"),
            ("analysis", "secu VM nftables 의 전체 테이블 목록에서 filter/blocklist/cti_ips 관련 상태를 확인하시오.", "nft list tables",
             "sudo nft list tables", "filter", "secu", "low",
             "secu VM의 nftables 전체 테이블 목록을 보여줘"),
            ("verify", "secu VM의 Suricata 서비스와 wazuh-agent 서비스 모두 active 인지 확인하시오.", "systemctl is-active …",
             "systemctl is-active suricata wazuh-agent 2>&1", "active", "secu", "low",
             "secu VM에서 suricata와 wazuh-agent 서비스 상태를 동시에 확인해줘"),
            ("reporting", "siem VM alerts.json 의 최근 100건에서 rule.level 별 분포를 집계하시오.", "jq '.rule.level' …",
             "sudo tail -100 /var/ossec/logs/alerts/alerts.json 2>/dev/null | jq -r '.rule.level' 2>/dev/null | sort | uniq -c", "", "siem", "low",
             "siem VM wazuh alerts.json 최근 100건에서 rule.level 별 분포를 집계해줘"),
        ],
    },
    15: {
        "title": "기말고사 — 보안 인프라 구축 종합 실기",
        "description": "nftables + Suricata + Wazuh + OpenCTI 연계를 활용해 공격 탐지·차단·기록 end-to-end 시나리오를 구성한다.",
        "objectives": [
            "nftables 'final' 테이블로 화이트리스트·블랙리스트 구조를 설계한다",
            "Suricata 커스텀 룰로 특정 공격을 탐지한다",
            "Wazuh alerts.json 에서 공격 이벤트를 확인한다",
        ],
        "difficulty": "hard",
        "duration": 180,
        "steps": [
            ("configure", "secu VM에 inet 'final' 테이블을 만들고 input 체인(policy drop)을 생성하시오.", "nft add table; nft add chain",
             "sudo nft add table inet final && sudo nft add chain inet final input '{ type filter hook input priority 0 \\; policy drop \\; }'", "final", "secu", "medium",
             "secu VM에 'inet final' 테이블과 policy drop의 input 체인을 만들어줘"),
            ("configure", "final 테이블에 whitelist_ips set 을 만들어 10.20.30.0/24 를 허용하시오.", "nft add set + element",
             "sudo nft 'add set inet final whitelist_ips { type ipv4_addr \\; flags interval \\; }' && sudo nft add element inet final whitelist_ips '{ 10.20.30.0/24 }' && sudo nft add rule inet final input ip saddr @whitelist_ips accept", "whitelist_ips", "secu", "medium",
             "secu VM final 테이블에 whitelist_ips set(10.20.30.0/24)을 만들고 input 체인에 @whitelist_ips accept 룰을 추가해줘"),
            ("configure", "final 테이블에 blacklist_ips set 을 만들고 input 체인 맨 앞에 drop 룰을 insert 하시오.", "nft insert rule … @blacklist_ips drop",
             "sudo nft 'add set inet final blacklist_ips { type ipv4_addr \\; }' && sudo nft insert rule inet final input ip saddr @blacklist_ips drop", "blacklist_ips", "secu", "medium",
             "secu VM final 테이블에 blacklist_ips set을 만들고 input 체인 맨 앞에 drop 룰을 삽입해줘"),
            ("configure", "Suricata local.rules 에 '.php?cmd=' 탐지 룰(sid:1000301) 을 추가하고 reload 하시오.", "content:\"cmd=\"; http_uri;",
             "echo 'alert http any any -> any any (msg:\"Final exam - cmd injection\"; content:\"cmd=\"; http_uri; sid:1000301; rev:1;)' | sudo tee -a /etc/suricata/rules/local.rules && sudo systemctl reload suricata", "1000301", "secu", "medium",
             "secu VM local.rules에 http_uri에 'cmd='가 포함된 요청을 탐지하는 룰(sid 1000301)을 추가하고 suricata reload 해줘"),
            ("verify", "attacker VM에서 web VM으로 /index.php?cmd=ls 요청을 보내 Suricata 탐지를 유도하시오.", "curl /index.php?cmd=ls",
             "curl -sS -o /dev/null -w '%{http_code}\\n' 'http://10.20.30.80/index.php?cmd=ls'", "", "attacker", "medium",
             "attacker VM에서 web VM으로 /index.php?cmd=ls 요청을 보내줘"),
            ("verify", "secu VM eve.json 에서 sid:1000301 알람을 확인하시오.", "grep 1000301 eve.json",
             "sudo grep '\"signature_id\":1000301' /var/log/suricata/eve.json 2>/dev/null | tail -3 || sudo grep 1000301 /var/log/suricata/eve.json | tail", "1000301", "secu", "low",
             "secu VM의 suricata eve.json에서 sid 1000301 알람을 찾아줘"),
            ("verify", "siem VM alerts.json 에서 sid 1000301 혹은 cmd injection 관련 이벤트를 검색하시오.", "grep cmd alerts.json",
             "sudo grep -i 'cmd injection\\|1000301' /var/ossec/logs/alerts/alerts.json 2>/dev/null | tail", "", "siem", "low",
             "siem VM wazuh alerts.json에서 cmd injection 또는 sid 1000301 관련 이벤트를 찾아줘"),
            ("configure", "CTI 결과를 가정해 blacklist_ips set에 203.0.113.77 을 주입하시오.", "nft add element inet final blacklist_ips { 203.0.113.77 }",
             "sudo nft add element inet final blacklist_ips '{ 203.0.113.77 }' && sudo nft list set inet final blacklist_ips", "203.0.113.77", "secu", "medium",
             "secu VM final 테이블 blacklist_ips set에 203.0.113.77을 추가해줘"),
            ("verify", "final 테이블 전체 룰셋을 확인해 구성 무결성을 점검하시오.", "nft list table inet final",
             "sudo nft list table inet final", "final", "secu", "low",
             "secu VM의 final 테이블 전체 룰셋을 출력해줘"),
            ("cleanup", "실습 종료: final 테이블 삭제 + sid:1000301 룰 삭제 + suricata reload 를 수행하시오.", "nft delete table; sed; reload",
             "sudo nft delete table inet final && sudo sed -i '/sid:1000301/d' /etc/suricata/rules/local.rules && sudo systemctl reload suricata", "", "secu", "high",
             "secu VM에서 final 테이블 삭제, sid 1000301 룰 삭제, suricata reload를 모두 수행해줘"),
        ],
    },
}


def build_lab(course: str, version: str, week: int, spec: dict) -> dict:
    lab_id = f"{course}-week{week:02d}"
    pass_threshold = 0.6
    steps = []
    for i, st in enumerate(spec["steps"], 1):
        category, instruction, hint, answer_cmd, verify_expect, target_vm, risk, prompt = st
        step = {
            "order": i,
            "instruction": instruction,
            "hint": hint,
            "category": category,
            "points": 10,
            "answer": answer_cmd,
            "answer_detail": f"{spec['title']}: {instruction}",
            "verify": {"type": "output_contains", "expect": verify_expect, "field": "stdout"},
            "target_vm": target_vm,
        }
        if version == "ai":
            step["script"] = answer_cmd
            step["risk_level"] = risk
            step["bastion_prompt"] = prompt
        steps.append(step)
    # Multi-task aggregate (order=99)
    mt_prompt_body = "\n".join(
        f"{i+1}) {st[7] if version=='ai' else st[1]}" for i, st in enumerate(spec["steps"][:5])
    )
    mt = {
        "order": 99,
        "instruction": "[Multi-task] 이번 주 핵심 작업 5개를 한 번에 수행하라.",
        "hint": "복합 작업은 bastion이 순서대로 계획하고 실행해야 한다",
        "category": "multi_task",
        "points": 50,
        "verify": {"type": "output_contains", "expect": "", "field": "stdout"},
        "target_vm": spec["steps"][0][5],
        "answer": "",
        "answer_detail": "",
    }
    if version == "ai":
        mt["risk_level"] = "low"
        mt["bastion_prompt"] = (
            f"secu/web/siem VM 전반에 대해 다음 작업들을 순서대로 수행해줘:\n{mt_prompt_body}"
        )
    steps.append(mt)

    return {
        "lab_id": lab_id,
        "title": spec["title"] + (" (AI 지원)" if version == "ai" else ""),
        "version": "ai" if version == "ai" else "non-ai",
        "course": course,
        "week": week,
        "description": spec["description"],
        "difficulty": spec["difficulty"],
        "duration_minutes": spec["duration"],
        "objectives": spec["objectives"],
        "pass_threshold": pass_threshold,
        "steps": steps,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--week", type=int)
    args = ap.parse_args()

    weeks = [args.week] if args.week else sorted(SPECS.keys())
    for w in weeks:
        spec = SPECS[w]
        for course, version in (("secops-nonai", "nonai"), ("secops-ai", "ai")):
            path = os.path.join(LABS, course, f"week{w:02d}.yaml")
            doc = build_lab(course, version, w, spec)
            with open(path, "w") as f:
                yaml.safe_dump(doc, f, allow_unicode=True, sort_keys=False,
                               default_flow_style=False)
            print(f"wrote {path}  ({len(doc['steps'])} steps)")


if __name__ == "__main__":
    main()
